### ISSUE TITLE
I can see the number of publications related to this dataset

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#100]
Implement this as a separate attribute in the Librecat search index (pre-calculated) and pass it on via the librecat REST API

**Comment by nicolasfranck** [comment]
i.e. only on detail view page, not a listing page

**Comment by nics** [comment]
also on listing pages

**Comment by nics** [comment]
publication search results en detailpagina’s tonen het aantal related datasets (related), dataset search results en detailpagina’s tonen het aantal related publications (incoming related)

**Comment by nicolasfranck** [comment]
> Implement this as a separate attribute in the Librecat search index (pre-calculated) and pass it on via the librecat REST API

it is only enrichment, not?

**Comment by nics** [comment]
yes

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/594

**Comment by nicolasfranck** [comment]
For publications there is now `related_dataset_count`
For datasets `related_publication_count`

Only available on listing page

**Comment by nics** [comment]
resolved by #120
