### ISSUE TITLE
If a file was uploaded but no access level was set, the pills shows an error "Select access level".

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#102]

**Comment by nicolasfranck** [comment]
default should be NOT to set a default access level -> should be validated by librecat.

**Comment by nicolasfranck** [comment]
@netsensei how did you manage to do this? Field `access_level` is required for every `file` entry, and it should be one of a list of fixed values. 

See https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/config/schemas.yml#L226
See https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/config/schemas.yml#L159

So I see no way to update this as such without getting a validation error
