### ISSUE TITLE
retrieve dataset: keep "deleted" records in the list?

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#103]
Deleting a publication from the web interface is actually a
soft delete (status is set to deleted). So the publication
is not gone, the files still exist and the record identifier
can still be present in table `related_publications`.

Filter on retrieval?

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/589

**Comment by nics** [comment]
ok
