### ISSUE TITLE
Announcement in Biblio when editing an author: case 01GS74TTVPJYAXHMZM3GNFHVDE

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#1047]
# Bug description

Announcement in Biblio when editing an author: case 01GS74TTVPJYAXHMZM3GNFHVDE

Goal: remove first author role

Reported by Marthe, who tried to complete the action herself.
Related: https://github.com/ugent-library/biblio-backoffice/issues/875

**Comment by nics** [comment]
fixed
