### ISSUE TITLE
only show research_data to reviewers in librecat, remove from add publication page, remove from import

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#106]
- [x] only show research_data to reviewers in librecat
- [x] remove from add publication page
- [x] remove from import

**Comment by sdebodt** [comment]
Will existing research data records be available as draft datasets in the new biblio, such that we can manually complete the metadata of these datasets?
FYI, I checked with Thomas and in the majority of research data records, the data itself is already available elsewhere (i.e. in a public data repository).

**Comment by nics** [comment]
@sdebodt yes they will be but their status will remain the same
