### ISSUE TITLE
Route `/dataset/:id` should check if publication is really of type `research_data`

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#108]
To fix either in LibreCat or in biblio-backend.

Now you can fill in any id.

**Comment by nics** [comment]
and vice versa for publications

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/librecat/issues/590

**Comment by nicolasfranck** [comment]
cf. https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/591/files

**Comment by nics** [comment]
ok
