### ISSUE TITLE
metadata for datasets to be retrieved through DOI and DataCite service

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#111]
**Describe the improvement**
Currently, the DOI is resolved through CrossRef. However, CrossRef does not contain (all) DOIs for datasets. Instead, the API of DataCite needs to be retrieved. At this point, it is not necessary to check the resourceType. In first instance, the data curator can judge whether a resourceType can be accepted. Later, validation rules can be implemented if that shows to be valuable.

DataCite REST-API: https://support.datacite.org/docs/api 

**To Reproduce**
1. Go to 'Add dataset'
2. Enter DOI for dataset '10.1594/PANGAEA.937928'
3. Error is given: [{"code":"import_by_id.id_not_found","title":"Unable to find records for id 10.1594/PANGAEA.937928","source":{}}]

**Expected behavior**
DataCite REST-API call is done with given DOI and metadata is returned and entered into biblio form

**Comment by nics** [comment]
The api now uses datacite for datasets, and still gives the error

**Comment by sdebodt** [comment]
related to https://github.com/ugent-library/biblio-backend/issues/112 and the fact that I used a "dataset in review" as an example.

10.1594/PANGAEA.933230  works well.

Sorry for the confusion.

**Comment by nics** [comment]
resolved by c4b33ecdfd93410cc68698cd4489b8a76b61db02
