### ISSUE TITLE
Link out to data at external data repository through persistent identifier

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#112]
**Describe the improvement**
Although also a URL to the repository or any other URL can be provided, only use the persistent identifier to link out from Biblio to the data in an external repository. e.g. using link https://doi.pangaea.de/10.1594/PANGAEA.938165 with label "https://doi.pangaea.de/10.1594/PANGAEA.938165"

If you want to keep the image next to the dataset summary and use this to link out to the data as well, also use link https://doi.pangaea.de/10.1594/PANGAEA.938165 to do so.

**Comment by nics** [comment]
We now use doi.org to resolve the doi

**Comment by sdebodt** [comment]
indeed, needs to be doi.org (e.g. https://doi.org/10.1594/PANGAEA.933380). The example I shared above was a dataset in review and apparently has a different domain in the PANGEAE repository at that point.

**Comment by nics** [comment]
resolved by 4d122ca4845662bf88fa3bf17538949f65548abb
