### ISSUE TITLE
Use a smaller search index doc

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#1131]
## Enhancement
We currently store and retrieve the whole record in the search index. This is not necessary, since refactoring the search code we only need to store the record id.

## Solution

Change indexedPublication and indexedDataset to only contain the fields we need.
Update the es6 mappings and reindex.

## Publication fields needed

- id (string)
- date_created (date)
- date_updated (date)
- year (date)
- identifier ([]string, contains doi, isbn, issn, eisbn, eissn, wos_id)
- title (string)
- faculty_id ([]string)
- organization_id ([]string, contains all id's from the tree, including faculty)
- contributor ([]string)
- reviewer_tag ([]string)
- wos_type ([]string)
- classification (string)
- status (string)
- type (string)
- vabb_type (string)
- publication_status (string)
- locked (bool)
- extern (bool)
- file_relation ([]string)
- message (bool)
- legacy (bool)

same all field rules

## Dataset fields needed

- id (string)
- date_created (date)
- date_updated (date)
- year (date)
- identifier ([]string, contains doi, isbn, issn, eisbn, eissn, wos_id)
- identifier_type ([]string, contains name of identifiers present)
- title (string)
- faculty_id ([]string)
- organization_id ([]string, contains all id's from the tree, including faculty)
- contributor ([]string)
- reviewer_tag ([]string)
- status (string)
- locked (bool)
- message (bool)

same all field rules

**Comment by nicolasfranck** [comment]
Notes:

* what do you mean by "same all field rules"
* dates in elasticsearch are formatted strings

**Comment by nicolasfranck** [comment]
Notes about datasets:

* field `doi` is used as a filter in order to detect duplicates
