### ISSUE TITLE
some projects available in ResearchExplorer cannot be found in "Add project"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#127]
**Describe the improvement**
When I want to add projects which I found in Research Explorer based on the title mentioned there, in some cases, the search function of the "Add project" pop-up does not give results.

examples:
- https://research.ugent.be/web/result/project/ac8ee4fb-4420-11eb-809b-01df1efbbcb6/details/3g002321-does-liana-proliferation-cool-down-tropical-forests/en, searching with "does liana"
- https://research.ugent.be/web/result/project/2148b194-45ba-4276-af77-2b9693c7e54c/details/179l05620-ecotoxicologically-responsible-removal-of-plant-protection-products-from-water-from-the-vegetable-and-potato-processing-industry/en, searching with "Ecotoxicologically responsible"

**To Reproduce**
1. Go to 'publication/dataset page'
2. Click on 'Add project'
3. Fill in search terms mentioned above in search text box
4. No projects are matching, no results are given.

**Expected behavior**
I expect that I am able to add any project to a publication/dataset which is available in Research Explorer/GISMO.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/142605914-b33251c5-3b7d-4124-9755-17e49f9e7bc3.png)

**Comment by sdebodt** [comment]
Possibly issue with parsing of project info or delay on provision of projects.
Will be handled elsewhere.

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/13

**Comment by nics** [comment]
project syncing has been improved - with production data these are findable

**Comment by sdebodt** [comment]
I cannot find the above listed projects through the "Add project" pop-up of https://backend.bibliotest.ugent.be/ and https://backend.biblio.ugent.be/.

**Comment by nics** [comment]
both are found with the above search terms on https://backend.biblio.ugent.be/ (dev is not always up to date with the most recent projects - sync is still manual)

**Comment by sdebodt** [comment]
I did some additional tests in prod and all projects that I tried could be found.
