### ISSUE TITLE
check helper and feedback text

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#130]
**Describe the improvement**
Check whether help, info, feedback messages are ok.

e.g. at the end of an "add" workflow
e.g. behind "i" icon next to a metadata field

@sdebodt to ask input from Anniek, Myriam

**Comment by sdebodt** [comment]
identified tasks:

- [ ] #140

**Comment by nics** [comment]
i'm going to close this, all the tasks are existing issues
