### ISSUE TITLE
publication file not found

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#134]
**Describe the improvement**
When I want to view the full text file added to a publication, I get an error saying that the publication file is not found (see screenshot). I tried this with publications with different access levels (open/UGent access). I get this error when trying to view full text files of publications that are available in the production version of Biblio.

examples:
- Biblio ID: 1864599
- Biblio ID: 212389

**To Reproduce**
1. Go to 'publication' page
2. Click on 'Full text' tab
3. Click on file name of full text file

**Expected behavior**
I expect to get a view of the file or the ability to download the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143228895-67beae00-e0b0-47f7-a9ab-c196e4e31654.png)

**Comment by nicolasfranck** [comment]
@sdebodt this is probably because the original data storage is not available on eliot1,
merely the metadata. Newly added files should work though.

**Comment by sdebodt** [comment]
@nicolasfranck that is probably the case. To check when moving to production.

**Comment by nics** [comment]
it's because not all existing files are available on the test server
