### ISSUE TITLE
when I proceed to the next step of the add workflow, warn me that I did not save

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#137]
**Describe the improvement**
In the "Add single publication" workflow, when I am editing the metadata but did not save it, I can click on the button "Summary" to proceed to the next step of the workflow and do not receive a warning that my metadata edits are not saved.

**Comment by netsensei** [comment]
Added a warning in 48dfbafe1fd4c01ac79dc9640796e54ea799d083.

If a form section is still open ("save" / "cancel" buttons visible") you will see a warning modal if you hit the "publish to biblio" button. When all form sections are saved / closed, the "Publish to biblio" button will immediately redirect to the next step.
