### ISSUE TITLE
Clicking enter closes popup but does not save

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#138]
**Describe the improvement**
When editing the full text information, for instance, when I add a title and hit enter after typing, the popup closes (or I get an error) while the title is not saved. Hitting enter should, for instance, move my cursor to the next text box or result in a save or result in no action, but should not close the popup without saving.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143243065-6a4c242b-6649-4472-afc8-9a80e9433dba.png)

**Comment by nics** [comment]
resolved by b28056c3c6eb58a41d7e033c24301de54669c1d9
