### ISSUE TITLE
UZ employee cannot log in

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#1382]
# Bug description
1. This person: https://telefoonboek.prd.rad.ugent.be/nl/people/801000591050
2. Gets this error:
![Schermopname__70_](https://github.com/ugent-library/biblio-backoffice/assets/1572885/dd59fab2-03a7-48bc-9fac-7e3dff4c1b6f)
3. I can log in to his account via "View as"

Do we need extra information? I can ask him in the helpdesk.

**Comment by nicolasfranck** [comment]
This person cannot be found in the UGent LDAP.

UZGent is actually problematic: some are in the UGent LDAP, while others aren't,
so hard to make up a policy (e.g. you can specify which external IDP's you want to allow in openid connect)

**Comment by mietcls** [comment]
There is apparently no UZ way to log in. Users can only log in with an UGent account.

What went wrong:
He tried to log in with an UZ mail address instead of his UGent username and password.
Will try to help him like this.
