### ISSUE TITLE
licenses to add to a full text

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#139]
**Describe the improvement**
After adding a full text file, the information on that full text file can be edited. One information field is the license. Currently, the user can use between different CC licenses. Which licenses are expected here?
@sdebodt to check with Myriam

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143243385-0748aaed-738b-4312-8ff6-10d81de60067.png)

**Comment by sdebodt** [comment]
**for open access only:** 

- The dropdown menu should list the CC licenses (if possible, would also be nice to somehow indicate CC0, CC-BY and CC-BY-SA as "open" licenses. Maybe in a tooltip or in some other way?). These licenses can only be selected when the access level is set to  open access.

- In addition to the predefined list of CC licenses in the dropdown, users need to be able to provide custom licenses (i.e. free text field) (e.g. because these are used by some publishers). In this case, no spdx license identifier will be available, so these will be classified as "Other" in FRIS.

Question: how to deal with older versions of CC licenses that have been applied to certain publications (e.g. CC-BY 2.5)?

**for other access levels:**
a box "no license (in copyright)" referring to https://rightsstatements.org/page/InC/1.0/?language=en, to tick or automatically tick the box?

**Comment by sdebodt** [comment]
OK, to revisit later.

**Comment by sdebodt** [comment]
Will you add/have you added the copyright box for non-open access?

**Comment by nics** [comment]
no, do we really need another form field or is the absense of a license enough for now? the form is already too large for some people to grok

**Comment by sdebodt** [comment]
need to check with Myriam whether absence of a license is sufficient
