### ISSUE TITLE
Add message to complete publication access level and full text doc info

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#147]
**Describe the improvement**
"Select the appropriate access level and complete the information on the full text document."

Could this sentence be added on top of the list of full text documents and below the drag and drop area?

related https://github.com/ugent-library/biblio-backend/issues/74

**Comment by nics** [comment]
since 5f4877a5c4cbb9fc47377ad3dc5c16777c8df111 the file edit dialog is opened after file upload
