### ISSUE TITLE
add tooltips and guidance to full text info popup

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#148]
**Describe the improvement**

- [x] tooltip for Relation or rename "Relation" to "Document type"
- [x] tooltip for Publication version: link to https://onderzoektips.ugent.be/en/tips/00001670/#Uploadofafile
- [x] tooltip for "Access level": link to https://onderzoektips.ugent.be/en/tips/00001291/
- [x] rename "Recommended option if... sensitive..." to "Recommended option if the file doesn’t contain any confidential information. Share your work to help other researchers.
- [x] Private access: reviewers means Biblio reviewers? if so add "Biblio"
- [x] tooltip for License: add link to https://onderzoektips.ugent.be/en/tips/00000411/
- [ ] copyright question still needed? (now as part of the license selection drop down)
- [x] remove "Delete" button from popup

@sdebodt to check the above with Anniek and Myriam

**Comment by sdebodt** [comment]
In addition to the above, can the items in the predefined list of publication versions be renamed? 

- [ ] published version --> publisher version/version of record (VoR)
- [ ] accepted manuscript --> author accepted manuscript (AAM)
- [ ] author's original --> author's original (AO)
- [ ] corrected version --> corrected version of record (CVoR)

**Comment by sdebodt** [comment]
Add a sentence below "Access level" title to guide users:

"Full text files are set to "UGent access" by default. However, you are strongly encouraged to make publications available in open access where possible."

**Comment by sdebodt** [comment]
- open access:

rename "Recommended option if the file doesn’t contain any confidential information. Share your work to help other researchers." to "Your file will be publicly available, effective immediately. Recommended option if you own copyright, or have permission from the copyright holder(s)/holder of the exclusive license to publish."  (Sorry dat dit nog eens aangepast moet worden)

- UGent access:

Rename "Your file will only be available **for** UGent members" to
"Your file will only be available **to** UGent members."

**Comment by sdebodt** [comment]
I suppose we cannot add clickable links to tooltips, so for license add a sentence below the title "License"

"Select a license to indicate what users are allowed to do with your full text. "

**Comment by nics** [comment]
> Full text files are set to "UGent access" by default. However, you are strongly encouraged to make publications available in open access where possible."

I made the text part of the tooltip
