### ISSUE TITLE
add tooltips and guidance to "Description" tab

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#149]
**Describe the improvement**

- [ ] tooltip for "Classification": The publication will be classified by the Biblio team as part of the bibliographic review process.
- [ ] tooltip for "Web of Science type": "In case that this publication is registered in Web of Science, a Web of Science publication type can be assigned which is different from the publication type of Biblio.

**Comment by nics** [comment]
web of science type should also be readonly probably

**Comment by sdebodt** [comment]
In principle yes, but not urgent. We could identify other fields that can be read-only as well, so I would not change any other fields than the Classification field right now.
