### ISSUE TITLE
change title "Edit Author" to "Edit Editor"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#151]
**Describe the improvement**
When clicking on "Edit" in the "Editors" section,  a popup with title as shown in the screenshot is given.
change title "Edit Author" to "Edit Editor"

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143264900-62d1b407-d378-47e0-9a91-bf8a843652b8.png)

**Comment by nics** [comment]
ok now
