### ISSUE TITLE
change Biblio status facet filter fields to "Draft" and "Validated"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#152]
**Describe the improvement**
facet filter for status should use same terminology as used in the pill shown for individual publications.

replace "private" by "Draft"
replace "public" by "Validated" (or "Published" ?)

Do we need to or can we distinguish status "Published" from status "Validated"? If not, I think "Validated" is not correct for published publications that are not reviewed yet.

**Comment by nicolasfranck** [comment]
interesting, when is something ready for review? @sdebodt @nics 
how is it done in the old backend?

**Comment by nics** [comment]
public and classification == U

**Comment by nicolasfranck** [comment]
strange, so those publications are already visible from the public website?

e.g. https://biblio.ugent.be/publication?classification=U

**Comment by nics** [comment]
yes that's intended

**Comment by nicolasfranck** [comment]
For reviewers add facet for classification? @nics @sdebodt 

Best to keep number of facets low.

**Comment by nics** [comment]
yes later, this issue just needs 2 labels replaced by their translations to close it:

replace "private" by "Draft"
replace "public" by "Validated"

**Comment by nicolasfranck** [comment]
or "public" as "Published"? That is more accurate. Otherwise we'll have a "bug report" rather claiming that the filter does not work as expected

**Comment by nics** [comment]
follow the design for now, we can't just change this ad hoc

**Comment by sdebodt** [comment]
@nicolasfranck @nics for the pills, there are 3 values "Draft", "Validated" and "Public". Will "Public" not appear anymore after this translation?
