### ISSUE TITLE
Improve text in "Summary" step of multiple publications workflow

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#156]
**Describe the improvement**
Replace "Next steps" with "Are you ready to publish?"

When you are not ready to publish all publications, you can save your publications as draft using the "Save all as draft" button and continue later from Overview page. Alternatively, you can click on one of the sections below to complete your submission.

When you are ready to publish, click the "Publish all to Biblio" button. All your publications will be available in Biblio. The publications will undergo a bibliographic review process by the Biblio team. A reviewer of the Biblio team will contact you in case any changes are needed.

Replace button "Publish to Biblio" by "Publish all to Biblio"
Remark: there is no option to select some publications so at the moment it is **all** publications.

**Comment by nics** [comment]
more text needs to be changed
