### ISSUE TITLE
Rename or remove link to go to publications/datasets overview from "add" workflow

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#161]
**Describe the improvement**
When in a "add" workflow, on top of the grey panel with workflow steps, there is a link to go back to the publications/datasets overview page which is named "Biblio publications/datasets".
On other pages, the link to go back to the publications/datasets overview page is named "Publications overview".
Actually, you can click on the publications/datasets buttons in the blue panel to go to this overview.

I would either rename the link to be consistent or remove it in the grey panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143467950-5f8ab1be-1a99-41ed-8bea-a632205c4edb.png)
![image](https://user-images.githubusercontent.com/72742841/143467034-6a6e1ff2-62b4-4284-ad0a-9feee230021b.png)

other pages:
![image](https://user-images.githubusercontent.com/72742841/143467191-ceb43eb9-8802-4b90-bcda-c5ee1f9e32cd.png)

**Comment by nics** [comment]
'biblio/datasets' goes back to all publications/datasets; back 'datasets/publications overview' goes back to your current search results. I think the difference is intentional in the design.

**Comment by sdebodt** [comment]
Ok, it is not obvious that there is a difference in the list of publications depending on the link.
