### ISSUE TITLE
I can create an empty publication

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#163]
**Describe the improvement**
I can proceed through the "add" workflow steps by clicking the blue button on the top right without filling in any info, even not an identifier.

result: Biblio ID: 8630102

I expect the question whether I am sure to continue without giving input.

For datasets, I get the message "Sorry, something went wrong. Could not import the dataset." when not providing an identifier and I cannot proceed. I can also proceed without adding anything to the Description.

**Comment by nics** [comment]
> I can also proceed without adding anything to the Description.
That is intented, a draft has no required fields. You can leave and return later to finish.
