### ISSUE TITLE
disable highlighting of workflow steps in grey bar

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#165]
**Describe the improvement**
I have the tendency to click on the different workflow steps in the grey bar to proceed, instead of clicking the blue button on the top right. When you hoover over the workflow step in the grey bar, it is highlighted, however, clicking it does not result in any action. If no action will be linked to clicking the workflow step in the grey bar, I would remove the highlighting.

Note that action to these workflow steps could be added if we want to allow users to return to previous steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143470478-f210c536-5c2e-45d0-8bc2-5cab7d694d24.png)

**Comment by nics** [comment]
requires fiddling with the design css, going to stick to the prototype here
