### ISSUE TITLE
Manually added publication does not show in overview

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#166]
**Describe the improvement**
I manually created the publication https://eliot1.ugent.be/biblio-backend/publication/8630119. I can browse to it, but I cannot find it in the publications overview.

**Comment by sdebodt** [comment]
It seems that the publication does not appear in the overview when I do not add particular metadata. When I add myself as author + indicate that I am an UGent author, the publication appears in the overview.

I can always browse to the publication using the biblio id in the url, even if it is not shown in the overview.

**Comment by nics** [comment]
creator_id was not set; you could view the publication directly because you have admin rights
