### ISSUE TITLE
Only show "Conference details" if publication type is "Conference Contribution"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#167]
**Describe the improvement**
The "Conference details" metadata section is now also given for, for instance, publications of type "Journal Article". I would expect that this metadata section is only present when the publication type is "Conference Contribution"

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143474005-ed0e7fc0-2868-47f1-a8ea-9561dc2521af.png)

**Additional context**
related issue: https://github.com/ugent-library/biblio-backend/issues/136

**Comment by nics** [comment]
no, is also present in some other types (see biblio.ugent.be/librecat)
