### ISSUE TITLE
Return to list of publications/datasets after wizard should sort by creation date?

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#178]
**Describe the improvement**
After adding one or more publications or datasets,
you are redirected to your list of publication/datasets,
but .. those are sorted by (publication) year.

Shouldn't that be sorted by "Added (newest first)".
That way you are reminded of your own recent
additions.

@sdebodt

**Comment by sdebodt** [comment]
@nicolasfranck as discussed yesterday in the meeting, it would be useful to have a sorting in which the recently added publication/dataset appears on top of the list. I use "Updated (newest first)" as then I also have the publications/datasets edited recently in the beginning of the list.

**Comment by nicolasfranck** [comment]
@nics I see that the backend already has a default sort: `["date_updated.desc", "year.desc"]`. Which is more advanced than what we can get by selecting `Updated (newest first)`.

When no sorting option is selected, the first element in the list is shown, i.e. `Year (newest first)`,
which is not the one selected, but the first element just happened to be on top.
biblio-backend does not know what librecat is choosing as its sorting option.

Either way, a few things are needed:

* let the biblio-backend decide what the default is?
* or let librecat return what the choosen sort option was, so it can be "injected" in the url query, as if the user selected this?
* the list of sort options should be a controlled list of options, not
   just a list that one happens to select correctly. That also gives
   use the opportunity to add further underlying sorting. e.g. when you
   sort on year, then sort on updated, then ..
