### ISSUE TITLE
completeness levels for publications

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#184]
**Describe the improvement**
SImilar to datasets, we want to color the stripes of completeness according to whether mandatory metadata fields are provided.

- 1 stripe (red, incomplete fields): some fields are completed
-
- 2 stripes (green): all mandatory fields are completed, namely at least 1 UGent auteur, at least 1 department or faculty (when department is missing, for already existing publications), Title, Publication year
     - + when journal article: journal title
     - + when Book chapter: book title
     - + when Conference Contribution: Proceedings title, Conference, Conference location, Conference start date, Conference end date

- 3 stripes (green) : all recommended and mandatory fields are completed
     - Journal article: doi, ISSN, volume, issue,  (begin- and end page numbers) or (article number + pages)
     - Book, Issue: ISBN, Publisher, Number of pages
     - Book chapter: ISBN, editors, Publisher, begin- and end page numbers
     - Conference Contribution: editors, Publisher, (begin- and end page numbers) of (article number + pages)

**Comment by nicolasfranck** [comment]
TODO: existence of files is not included in this evaluation

**Comment by nicolasfranck** [comment]
@sdebodt by "issue" you mean "issue editor", right?

**Comment by nicolasfranck** [comment]
btw @sdebodt weten invoerders hoe ze dit schoonheidsideaal kunnen bereiken? ;-) 
Een link naar de documentatie?

**Comment by sdebodt** [comment]
@nicolasfranck, I discussed this with @nics. File upload presence can be added as criteria for 2 stripes.

With Issue, I mean the publication type "Issue" under 'As editor" (see screenshot in https://github.com/ugent-library/biblio-backend/issues/136).

Ideally, users know what is needed for each completeness level.  Possibly, a completeness report (similar to the Summary at the end of an add workflow) could help. That's for 2022 ;-)!
