### ISSUE TITLE
completeness levels for datasets

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#188]
**Describe the improvement**

- 1 stripe: some metadata fields are provided 

- 2 stripes: all mandatory metadata fields are provided

- 3 stripes: all recommended and mandatory fields are provided 

see excel in https://github.com/ugent-library/biblio-backend/issues/126 to see which are mandatory (M and MA) and which are recommended

**Comment by nicolasfranck** [comment]
@sdebodt can you provide the following: 

* what is necessary for level 2 to pass
* what is necessary for level 3 to pass

The existence of "mandatory" fields can only lead to two levels (valid and not valid),
not three. That's why I'm asking.

**Comment by nics** [comment]
@nicolasfranck can you add required asterisks to the dataset fields in the go app?

**Comment by sdebodt** [comment]
For level 2, all mandatory fields are completed (valid). 

For level 3, the above  + also recommended fields are completed (valid).

Which fields are mandatory or recommended is indicated in the "overview of metadata" excel file included in https://github.com/ugent-library/biblio-backend/issues/126.

Does this make sense?

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/636

**Comment by nics** [comment]
ok
