### ISSUE TITLE
more specific error message after DOI submission

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#190]
**Describe the improvement**
Currently, the error message says "Something went wrong...". Specify in the error message what went wrong. Is the DOI not existing, not resolvable to DataCite, not the correct resourceType...

**Comment by nicolasfranck** [comment]
With the current mockup, one can only show the following errors (examples):

* doi is empty
* doi not found in "datasets"
* some internal server error occurred

But, when the datacite record does not provide the necessary information
for the record to be valid (e.g. no `first_name` for an author), there is no
way to express this in a feasible way in this small flash box in the lower left corner
