### ISSUE TITLE
DOI not recognized, dataset not found

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#191]
**Describe the improvement**
The dataset with DOI 10.18739/a29s1km49 can be found in DataCite and has resourceType=dataset but gives an error in biblio
https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.18739/a29s1km49

{
  "id": "https://doi.org/10.18739/a29s1km49",
  "doi": "10.18739/A29S1KM49",
  "url": "https://arcticdata.io/catalog/view/doi:10.18739/A29S1KM49",
  "types": {
    "ris": "DATA",
    "bibtex": "misc",
    "citeproc": "dataset",
    "schemaOrg": "Dataset",
    "resourceTypeGeneral": "Dataset"
  },

![image](https://user-images.githubusercontent.com/72742841/144445901-348ce69e-1244-4131-a99c-dbf72f1393fa.png)

**Comment by nicolasfranck** [comment]
Note to self: use json export instead of xml because xml leads to interpretation problems:

https://search.datacite.org/works/10.18739/a29s1km49

**Comment by nicolasfranck** [comment]
Note to self: `application/ld+json` does not map everything.

Examples:

* no way to differentiate SPDX right uri's. (https://search.datacite.org/works/10.5281/zenodo.3630204)
