### ISSUE TITLE
make DOI of publications uneditable and align publications/datasets

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#197]
**Describe the improvement**
For datasets, a DOI cannot be edited. For publications, a DOI is currently editable, but would change so that it is also readonly for publications.
Publication type is also readonly, I suppose. In this case, the publication type does not appear in the edit view. It would be more consistent to also show the publication type in edit view as readonly.

view:
![image](https://user-images.githubusercontent.com/72742841/144591862-46ff6777-b7b9-44ea-b821-f614d4517d3b.png)

edit:
![image](https://user-images.githubusercontent.com/72742841/144591896-95b96d2b-63e0-4025-95cd-506fec4084c3.png)

**Comment by nics** [comment]
doi should be editable for manually added publications; it should indeed be readonly if the publication was imported, but we can't express that in the datamodel right now

i'll add the readonly type
