### ISSUE TITLE
do not select on resourceType of a dataset

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#206]
**Describe the improvement**
Currently, only datasets with a DOI and resourceType = "dataset" are accepted in the first step of an "add dataset" workflow. Instead, we do not want to apply any filter on resourceType and accept all resources that have a DOI that can be resolved at DataCite. As such, data curators can assess the submitted resources and decide whether the submission is appropriate to biblio. In a later phase, after learning about which resources are typically submitted, we can revisit and decide whether automated filtering based on resourceType can be useful.

**Comment by nicolasfranck** [comment]
Wouldn't it make the import more complex to accept all types? For every type
the mappings could be different.

**Comment by nics** [comment]
No it's a small change, mappings stay the same, just remove the filter on resourcetype

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/625
