### ISSUE TITLE
keywords separated by commas are not recognized as distinct keywords

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#221]
**Describe the improvement**
There should be 3 keywords for this dataset. However, the keywords are given in one line in the edit mode and as 1 pill in the view mode

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/145437052-c244ec05-1e4e-483c-a537-c8dbfd74f8ac.png)

**Comment by nics** [comment]
can you give the doi?

**Comment by sdebodt** [comment]
sorry, forgot to add it

10.5281/zenodo.5749207
Biblio ID: 8630210

**Comment by sdebodt** [comment]
due to formatting of DataCite metadata JSON, I assume. Can be checked later if we want to "correct" these formatting issues.

  "subjects": [
    {
      "subject": "electrical supply, half-hourly, Great Britain"
    }

**Comment by nics** [comment]
resolved by https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/e89807dbce4eecc978e8131c7e91628b90e032f3
