### ISSUE TITLE
records created in the old gui should have no data loss when edited in the new gui

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#228]
- [ ] file level license fields
- [ ] what else ?

**Comment by nicolasfranck** [comment]
Make a list of old fields, and copy them from the old publication record during update in the rest api.

**Comment by nics** [comment]
@nicolasfranck maybe the inverse is safer? copy all fields that are not in the biblio-backend Publication model.

**Comment by nicolasfranck** [comment]
@nics by that you mean: copy all keys from the old publication record that were not provided?

**Comment by nicolasfranck** [comment]
or something like this:

```
$old_publication->{$_} = $new_pub->{$_} for keys %$new_pub;
$model->add($old_pub)
```

for that is what biblio-backend does when it is collecting al of its data,
except for the fact that it does not know about all fields that were not
supplied by the rest api.

**Comment by nics** [comment]
Copy all the fields from the old record that are not part of the model

**Comment by nicolasfranck** [comment]
* urn
* ubi_funded
* translator
* thematic_area
* subject (~keyword?)
* research_group
* related_material
* quality_controlled
* pubmedID
* publication_identifier -> rest_api haalt dit uit (e)-is(x)n -> OK
* publication_date
* popular_science
* pmid -> boolean flag, derived from external_id.pmid.* -> OK
* pacs_class
* original_language
* open_data_release
* nasc
* msc_class
* main_file_link
* link (renamed to url in biblio-backend) -> OK
* jel
* isi -> boolean flag, derived from external.isi.* -> OK
* ipn
* ipc
* intvolume
* genbank
* email
* ddc
* date_approved -> rest_api removes it, but own ugent schema configures it?
* data_reuse_license
* corporate_editor
* citation -> removed by rest_api
* ccs_class
* application_number
* application_date
* applicant
* alternative_id
* accept

**Comment by nics** [comment]
resolved by https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/cccd539e053cc4814269952a6f5c34849e3abe0d
