### ISSUE TITLE
make trailing slashes optional

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#235]
https://eliot1.ugent.be/biblio-backend -> not found
 https://eliot1.ugent.be/biblio-backend/ -> found

**Comment by nicolasfranck** [comment]
that sounds more like a proxy server setting:

```
location /biblio-backend/ {
  proxy_pass http://localhost:3001/
}
location = /biblio-backend {
  rewrite ^ /biblio-backend last;
}
```

**Comment by nics** [comment]
it's a gorilla mux router issue i think
