### ISSUE TITLE
prepare production docker deployment

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#236]
- [x] log streaming
- [x] docker-compose on eliotx
- [x] reverse proxy on persse0 and persse
- [x] Configure a distinct redirect uri in our OIDC provider.

**Comment by netsensei** [comment]
Done.

- Logging via a logging collector agent and persistent storage of logs.
- Production specific configuration settings.

Todo:

- Configure a distinct redirect uri in our OIDC provider.

**Comment by nics** [comment]
urls: backend.bibliotest.ugent.be and backend.biblio.ugent.be
