### ISSUE TITLE
remove requirement "link to publication" to allow publication of dataset

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#242]
**Describe the improvement**
To reduce the number of requirement for the publication of a dataset, remove the requirement to have a publication linked to the dataset. As such, researchers can also add datasets which do not have a publication (yet).

Note: this is a Mandatory if applicable requirement from FRIS

**Comment by nicolasfranck** [comment]
@nics this sounds like a v1 requirement, not? Less requirements..

It is just commenting out a line in librecat

**Comment by nics** [comment]
@nicolasfranck yes my thoughts exactly, will you remove it from the validation? no need to make a pr

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/56ffd7e077fa456416d1fe4c5b4b29eeb9c97320

**Comment by sdebodt** [comment]
wow fast!
