### ISSUE TITLE
investigate whether publisher can be automatically extracted (more often)

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#243]
**Describe the improvement**
publisher is a mandatory (MA) field in the FRIS metadata model. However, it might be tricky for a user to know what is expected here. Adding the tooltip will help. In addition, we can explore whether this field can be extracted (more often) from the DataCite metadata or otherwise.

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/643

**Comment by nicolasfranck** [comment]
I can copy this from the datacite record.

Reimporting data doesn't seem to be a good idea, as that would overwrite manual updates.

What would you like as a tooltip?

**Comment by sdebodt** [comment]
The tooltip is normally already implemented in https://github.com/ugent-library/biblio-backend/issues/230.

I do not want to update existing records to add the publisher. When publisher is missing from these records, it could be due to the fact that this feature was not implemented yet (not sure). 
As you mention sometimes the publisher is available in the DataCite record so in that case it should be extracted. If publisher is not often provided in the DataCite field "Publisher", we could look into options to identify the publisher through other approaches (e.g. Zenodo datasets have "zenodo" include in the DOI (10.5281/zenodo.1246815)).

**Comment by nics** [comment]
publisher gets imported now (dev server)
