### ISSUE TITLE
how to ensure that UGent membership is indicated?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#244]
**Describe the improvement**
Currently, when authors/creators are extracted based on the DOI, the UGent membership of the authors/creators needs to be manually added. Can this be automated? If not, how to draw the user's attention to the fact that this needs to be done?

**Comment by nicolasfranck** [comment]
Automating stuff has the disadvantage that users tend to forget that something was filled in automatically.

The conversion of external users to ugent users is based on a search query on first name and last name,
which is not always correct. What if there is more than one user in the university with the same first and last name?

**Comment by sdebodt** [comment]
Indeed, it is a bit tricky to do it automated. Affiliations might also be messy.
Maybe better to give instructions on what needs to be done when arriving on the "Complete description" page?

I would not follow up on this right away, but something to keep in mind as a future enhancement.

**Comment by sdebodt** [comment]
New feedback indicates also the need to inform people that they need to complete the other tabs (author/creator, linked datasets/publications). Color the tabs to show which ones were addressed?

**Comment by sdebodt** [comment]
address when automation of assignment of affiliation is developed.
at the moment, warn if no UGent author/creator is present.

**Comment by nicolasfranck** [comment]
implement via modal with errors @nicolasfranck

**Comment by nics** [comment]
@nicolasfranck extra librecat validation needed:
* a publication or dataset that is
* public
* not extern
* should have at least one contributor with an id

**Comment by nics** [comment]
ok, shown in the errors modal on publish
