### ISSUE TITLE
simplify error messaging upon publication of dataset

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#246]
**Describe the improvement**
Currently, when a user tries to publish a dataset which is not completed validated, an error is given after clicking the "Publish to Biblio" button. This error message mentions 1 missing field. However, there might be other fields that are missing too. Can all missing  fields be mentioned in 1 error message?

**Comment by nicolasfranck** [comment]
@sdebodt that would be interesting indeed. Unfortunately the message box in the lower right corner is too small for anything longer than a line. It was not meant for any extensive reporting. In a normal scenario you have a full form available where you can show the error next to the input field (after form submission), but in case of the publish button, there is not. This becomes worse once if you want to publish multiple publications/datasets (via the wizard)

**Comment by nics** [comment]
we have plans to replace the message box with something more useful

**Comment by sdebodt** [comment]
ok, would be more efficient to see everything in one go.

**Comment by sdebodt** [comment]
Error messaging:
- on the level of the individual field, when info is entered
- on top of form for errors that do not pertain to one specific field or errors generated when clicking the "Publish to Biblio" button

Do not use flash messages in the lower right corner to share detailed error information.

**Comment by nics** [comment]
a modal is shown now, the error field labels still need some work
