### ISSUE TITLE
open repo linkout in new tab

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#247]
**Describe the improvement**
When clicking on the DOI to go to the dataset in the external data repository, currently, the page opens in the same window. It would be better if the link opens in a new tab.

also for publications as soon as we have this linkout based on DOI.

**Comment by sdebodt** [comment]
Is this fixed? When clicking on "View in external repository" for datasets, there is no new tab opened.

Tested in chrome, IE and Firefox.

**Comment by nicolasfranck** [comment]
@nics probably not deployed yet?
