### ISSUE TITLE
add tick box "no license (in copyright)" for ugent/private access

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#249]
**Describe the improvement**
for ugent/private access levels of publications:
a box "no license (in copyright)" referring to https://rightsstatements.org/page/InC/1.0/?language=en, to tick or automatically tick the box?

see https://github.com/ugent-library/biblio-backend/issues/139

**Comment by sdebodt** [comment]
Over de "no license (in copyright)" optie die nog niet is toegevoegd liet Myriam het onderstaande weten.

"Juridisch gezien is dit strikt genomen niet nodig, omdat de afwezigheid van een CC of andere licentie daar inderdaad op neerkomt. Niettemin zou ik denken dat het toch zinvol is om die optie aan te bieden bij een full text in Biblio, omdat het

- echt expliciet maakt aan de hergebruiker dat die toestemming voor hergebruik moet vragen aan de auteursrechthebbende

- ook een manier kan zijn om onderzoekers extra te sensibiliseren m.b.t. hergebruikrechten en licenties voor publicaties (velen staan er helemaal niet bij stil wat het betekent als een werk wel of geen licentie heeft; of dat niet alleen open toegang belangrijk is, maar ook vrij hergebruik d.m.v. een open licentie; of wat het betekent als ze hun rechten overdragen aan een publisher die verbiedt om een versie onder een CC-licentie te verspreiden via een institutional repository)."

**Comment by sdebodt** [comment]
voorstel is om de box "no license (in copyright)" referring to https://rightsstatements.org/page/InC/1.0/?language=en toe te voegen als optie voor alle access levels (dus niet enkel voor private en UGent access zoals hierboven vermeld).

**Comment by sdebodt** [comment]
first address issue on licenses for datasets.

**Comment by nics** [comment]
ok
