### ISSUE TITLE
research data cannot be found in biblio.ugent.be

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#251]
**Describe the improvement**
When I use the advanced search of bibliio.ugent.be and select the type "Research data", no datasets are returned. We intended to disable adding and editing publications of type "Research data". However, we still need to be able to view registered datasets as this will be the only way to view them for users that are not creators or submitters of the dataset (as long as biblio.ugent.be is not updated).

**Comment by nics** [comment]
it is because they all have status private until they are reviewed again

**Comment by sdebodt** [comment]
right! ok.
