### ISSUE TITLE
how to view complete metadata of dataset?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#252]
**Describe the improvement**
As biblio.ugent.be frontend is developed on top of the old metadata model for datasets (i.e. publications with type "Research data"), some of the metadata provided at registration of the dataset will not be shown in the biblio.ugent.be frontend, as long as that frontend is not updated too.

Are there options to make available more metadata? e.g. providing all metadata as a file in the download section, making small changes to the frontend, redirecting to the biblio-backend interface with adjusted permissions?

**Comment by nics** [comment]
@sdebodt yes this will be added soon https://github.ugent.be/Universiteitsbibliotheek/biblio/issues/16

**Comment by sdebodt** [comment]
OK, do I close this issue here? I do not have access to the biblio repo in the ugent github.

**Comment by nics** [comment]
we can leave it open as a reminder or to make comments

**Comment by sdebodt** [comment]
ok

**Comment by mietcls** [comment]
PR open at https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/30

**Comment by sdebodt** [comment]
update from Nicolas S on Slack on July 14th that some more metadata of datasets is shown in frontend.
example: https://biblio.ugent.be/publication/8718105

what is still missing?

**Comment by mietcls** [comment]
To do: sample test

**Comment by mietcls** [comment]
# Tested 5 records

**Way of testing**
- Looked for a record that was available on all environments
- Took OR eliot OR old back-end as baseline
- Compared to the public view

_Note: I haven’t been able to test records younger than 10 years for all environments, nor with datasets connected._

**Notable difference**
For id **3008329** – **La gramaticalización : perspectivas funcionales**
Differences:
- Status in public: in press
- Status in old back-end: accepted
- Status in eliot: accepted

Any idea why this is the case?

**Test**
- 3437264
    - Studies of jet quenching using isolated-photon plus jet correlations in PbPb and pp collisions at root s(NN)=2.76 TeV
    - Biblio public view https://biblio.ugent.be/publication/3437264
    - Old environment: authors and editors would not load and crashed my browser (too many)
    - Eliot environment https://eliot1.ugent.be/biblio-backend/publication/3437264?redirect-url=%2Fbiblio-backend%2Fcuration%2Fpublication%3Fpage%3D4%26page-size%3D20%26q%3DCabinet%2Bconflicts%2Bin%2BBelgium%26sort%3Ddate-updated-desc 
        - (Authors and editors loaded immediately!)
    - Differences
        - Pages from and Pages to missing -> However pages in total is available, since 1999148 does show the pages in total this is probably a conscious choice
- 3008329
    - La gramaticalización : perspectivas funcionales
    - Biblio public view https://biblio.ugent.be/publication/3008329
    - Eliot 1: https://eliot1.ugent.be/biblio-backend/publication/3008329?redirect-url=%2Fbiblio-backend%2Fcuration%2Fpublication%3Ff%255Bstatus%255D%3Dpublic%26q%3D%26sort%3Dyear-desc
    - Old environment: https://biblio.ugent.be/librecat/record/edit/3008329 
    - Differences
        - Status in public: in press
        - Status in old back-end: accepted
        - Status in eliot: accepted
- 1999148
    - Dialectology and linguistic geography
    - Public view: https://biblio.ugent.be/publication/1999148
    - eliot: https://eliot1.ugent.be/biblio-backend/publication/1999148?redirect-url=%2Fbiblio-backend%2Fcuration%2Fpublication%3Ff%255Bstatus%255D%3Dpublic%26q%3D2020%26sort%3Dyear-desc
    - Old environment: https://biblio.ugent.be/librecat/record/edit/1999148 
    - No differences
- 2117006 
    - A counterfeit community : rederijkers, festive culture and print in renaissance Antwerp
    - Public view: https://biblio.ugent.be/publication/2117006 
    - Eliot: https://eliot1.ugent.be/biblio-backend/publication/2117006?redirect-url=%2Fbiblio-backend%2Fcuration%2Fpublication%3Ff%255Bstatus%255D%3Dpublic%26q%3D2020%26sort%3Dyear-desc 
    - Old environment: https://biblio.ugent.be/librecat/record/edit/2117006 
    - No differences
- 364225 
    - Alternative method to identify susceptibility genes for Crohn's disease through transcriptome analysis
    - Public view: https://biblio.ugent.be/publication/364225 
    - Eliot: https://eliot1.ugent.be/biblio-backend/publication/364225?redirect-url=%2Fbiblio-backend%2Fcuration%2Fpublication%3Fq%3DPersinette%26sort%3Ddate-updated-desc 
    - Old environment: https://biblio.ugent.be/librecat/record/edit/364225 
    - No differences

**Comment by sdebodt** [comment]
This issue is about datasets and whether all metadata of a dataset in the new backend is shown in the old frontend (public website) as for the latter, datasets are displayed as publications of type "Research Data".

**Comment by sdebodt** [comment]
I had a look at some examples.

- https://biblio.ugent.be/publication/8718105
- https://biblio.ugent.be/publication/8752556
- https://biblio.ugent.be/publication/8759641
- https://biblio.ugent.be/publication/8757746

All look fine. No metadata is missing or incorrectly displayed except for the relations between datasets and publications (example: https://backend.biblio.ugent.be/dataset/8725889).

There are some uppercase to lowercase changes (e.g. access level), but for now, I would not look into that.

Language and classification fields do not exist in the new backend for datasets and are displayed as undetermined which is fine for now.

I will make a new issue on the topic of related records, as we need to check whether this info is transferred to GISMO (for FRIS reporting).

**Comment by mietcls** [comment]
@sdebodt Thank you for looking into this and doing the work. I misunderstood before. Does that mean we can close this one, and refer to the new one?

**Comment by sdebodt** [comment]
Yes, it can be closed. Based on the examples I looked at the necessary metadata for datasets is now also shown in the frontend (public website).
