### ISSUE TITLE
change "add author" to "add creator" for datasets

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#255]
**Describe the improvement**
There is an "add author" button and also the popup mentions authors instead of creators. Replace author by creator for datasets.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/146907029-2131590c-efb4-41c5-89a5-392f9b7abc51.png)

![image](https://user-images.githubusercontent.com/72742841/146906873-e01be811-7547-47bc-8fb7-5fd133b85471.png)

**Comment by nicolasfranck** [comment]
@sdebodt because they are authors. I guess the title of the tab "Creators" is wrong. Not @nics ?

**Comment by nics** [comment]
@nicolasfranck the librecat field is `author`, but the labels in dataset context should be Creator, so dialog title should be Add creator
