### ISSUE TITLE
allow to change order of creators of a dataset and authors of a publication

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#256]
**Describe the improvement**
Currently, creators are ordered according to the order in the DataCite metadata. However, when manually adding creators, they are added at the end of the list of creators. Could a creator be dragged and dropped to it's correct position? This could be useful for authors of publications as well (I thought we originally had some functionality to do that for publications?).

**Comment by sdebodt** [comment]
develop "add below other author/creator" to modify author/creator list at a certain position in the author/creator list.

later further improve e.g. with drag option or other

**Comment by nics** [comment]
ok

**Comment by nics** [comment]
contributors are draggable now

**Comment by sdebodt** [comment]
nice ;-)!
