### ISSUE TITLE
If embargoed access is chosen, make embargo period mandatory

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#258]
**Describe the improvement**
Currently, when I select "embargoed access" and do not provide an embargo period, I can still publish the dataset. When selecting "embargoed access" both "embargo period" and "access level after embargo" should be mandatory.

**Comment by nicolasfranck** [comment]
@sdebodt @nics and that should only be applied WHEN you publish, or just on the moment you fill this in?

**Comment by sdebodt** [comment]
@nicolasfranck, currently, for datasets, the mandatory fields are checked upon clicking the "Publish to Biblio" button. So I would be consistent with that. Maybe add an asterisk next to the fields though, if possible.

**Comment by nicolasfranck** [comment]
well just asking, because the reporting of errors during the publish step isn't all that user friendly (as there is no form to specify the problems)

**Comment by nicolasfranck** [comment]
Adding an asterisk to a conditional field can be misleading, not?

**Comment by nicolasfranck** [comment]
will be fixed by https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/641

**Comment by sdebodt** [comment]
> Adding an asterisk to a conditional field can be misleading, not?

yes, indeed. The input boxes are greyed out if  "embargoed access" is not chosen, but the field names themselves not. I would then maybe add another tooltip for "embargo period" and "access level after embargo period" saying "Mandatory if access is embargoed".

**Comment by nics** [comment]
merged into librecat dev
