### ISSUE TITLE
warn me when adding a dataset/publication with a DOI that already exists in Biblio

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#259]
**Describe the improvement**
Currently, you can add metadata for a dataset with a particular DOI multiple times. I would like to be warned that a dataset record for that DOI already exists. Or even stronger, I should not be able to add a dataset with a DOI that already exists.

Similarly, a publication should not be entered twice.

**Comment by nicolasfranck** [comment]
As datasets are mostly added not manually, but in batch, come back to this issue when we have a solution to create an error report for batch errors.

**Comment by sdebodt** [comment]
Datasets are added manually (one by one) only. I want a check that warns the user such that he does not create a record with a DOI that already is used in another record.

**Comment by nics** [comment]
@sdebodt there's a check in place now for dataset doi import, can you test?

**Comment by sdebodt** [comment]
@nics I tested on dev. I get the popup in the screenshot when providing a DOI of a dataset that already exists. 
Small remark, maybe only show the dataset title once?

Can this be done for publications too?

![image](https://user-images.githubusercontent.com/72742841/154230836-3dde770f-8313-474d-8f16-d96b2e7343de.png)

**Comment by sdebodt** [comment]
to do for publications. 
new ticket will be made for batch import.

**Comment by nics** [comment]
ok
