### ISSUE TITLE
improved login by making UGent button blue?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#265]
**Describe the improvement**
To indicate to users that the preferred way to login is by clicking the "UGent" button, could this button be colored blue instead of the "Sign in" button. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150812369-5dd6252d-28e0-400b-acc2-3e6126ffb0b6.png)

**Comment by nicolasfranck** [comment]
Would be better if local accounts where either "hidden" or banned to the bottom.
Those local accounts are for administration only anyway

**Comment by nics** [comment]
Dialog is only visible in development to give others the chance to think about improvements
