### ISSUE TITLE
cannot import multiple publications with WoS export file

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#266]
**Describe the improvement**
After uploading a WoS export file in the "Add multiple publications" workflow, I get an error and I return to step 2 (see screenshot). No publication draft is made.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150815477-ce181e94-f851-407d-a0f9-9bb02c7578cc.png)

https://backend.bibliotest.ugent.be/

**Comment by nicolasfranck** [comment]
@sdebodt can you upload the wos export file?

**Comment by sdebodt** [comment]
I can select a file from the file explorer, but after shortly showing a turning wheel, I am redirected to step 2.

**Comment by nicolasfranck** [comment]
@sdebodt can you upload the wos export file here?

**Comment by sdebodt** [comment]
ah, ok.
[savedrecs_WOS.txt](https://github.com/ugent-library/biblio-backend/files/7932510/savedrecs_WOS.txt)

**Comment by nicolasfranck** [comment]
Should be fixed by https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/645

**Comment by sdebodt** [comment]
Is this fixed or will it be?

**Comment by nicolasfranck** [comment]
it should be, but I am not sure if that version of librecat is already deployed. @nics ?

**Comment by nics** [comment]
@sdebodt this can be tested now

**Comment by sdebodt** [comment]
I tested this on dev and the upload of a WoS file is working.
