### ISSUE TITLE
buttons not reactive in IE11

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#267]
**Describe the improvement**
Several buttons do not work in IE11 (see version in screenshot). I did not test exhaustively as normally I test in Chrome.

- 3 dots next to publication in Publications overview
- buttons on right-hand side of publication details page (Edit, Add project, ...)

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150817880-3f454f2d-313d-4e89-88c6-fe396cf61e2d.png)

**Comment by nicolasfranck** [comment]
IE11, that is like 7 years old. Is this within the requirements? @nics ?

**Comment by nics** [comment]
no, but i'll pass it on to the designer, if there's an easy fix we might as well apply it

**Comment by sdebodt** [comment]
:-) maybe not to bother. I normally do not use it, it is the default one installed on my laptop. I tried it because of another comment I received on the positioning of buttons.
