### ISSUE TITLE
provided "Research field" disappears after clicking + to add another research field

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#268]
**Describe the improvement**
When I select a research field from the drop-down, it is filled in in the text box. When clicking + to add another research field, a second text box appears.  However, the previously selected research field is not shown, the first text box is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150818804-c37b980d-ba37-4abf-a8f9-1b4d814e1820.png)

https://backend.bibliotest.ugent.be/

**Comment by nics** [comment]
ok
