### ISSUE TITLE
use modal to input information (especially publication/dataset details)

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#271]
**Describe the improvement**
After completing a metadata section (especially "publication details"), you often end at the bottom of the section. However, to be able to save, you need to scroll back to the top. Could "cancel" and "save" buttons be added at the end of the section as well?
Or allow to scroll within publication details, such that bar of this panel is "frozen"?
Or move "Save" button higher?

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150820937-b5bd7e57-711d-4bc8-bd67-7161e05d298f.png)

**Comment by sdebodt** [comment]
Instead of moving the save button, we will make the way to input information more uniform. 

Currently, the publication/dataset details are added in the form shown on the publication page after clicking "edit". We want to replace this with an input modal as is used to add projects, edit authors/creators, etc. By using this modal/popup, there is no save button needed any longer. The modal can take the complete height of the screen.

The main page will show a read-only version of the content of the publication/dataset details.

Also replace with modal:
- conference details
- additional information

**Comment by nics** [comment]
ok
