### ISSUE TITLE
Remove full text title and description

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#273]
**Describe the improvement**
The popup to add metadata on the level of the full text document contains a text box for title. Is this used in the old Biblio? With what intent? Can we see this document title somewhere besides in the popup?

I would suggest to remove this field (if not used in the old Biblio) or to change the field name from "Title" to "Document title".

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/151001046-c29a8c86-d981-41ab-8d9b-5804c35a863b.png)

**Comment by mietcls** [comment]
As I understood from talking to the reviewers, Title and Description were never looked at nor reviewed in the old back-end.

<img width="636" alt="Schermafbeelding 2022-05-18 om 16 44 53" src="https://user-images.githubusercontent.com/1572885/169069831-84d97446-121b-491a-a2ac-42a7767bfef6.png">

**Comment by sdebodt** [comment]
OK, then I suggest to remove the full text title as it is confusing.

**Comment by mietcls** [comment]
@nicolasfranck We don't use it at all so we can remove it completely.
