### ISSUE TITLE
add help in linked dataset/publication popups

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#275]
**Describe the improvement**
To add a linked dataset/publication, a popup is opened when clicking "Add dataset/publication". In this popup, add the sentence "Select one or more datasets/publications as already registered in Biblio".

Similar to help in project popup (https://github.com/ugent-library/biblio-backend/issues/241)

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/151003370-c8ab280e-5006-465a-8eb5-67708fa70507.png)

**Comment by nics** [comment]
ok
