### ISSUE TITLE
Provide examples for text fields while filling out forms

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#278]
# Story

Add examples and guidance for text fields as **help text.**

## Component
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text

![Image](https://user-images.githubusercontent.com/1572885/185958895-3b945501-7411-49d1-b67e-75c942db7757.png)

### DOI (in publication details)
"e.g. https://doi.org/10.1093/plcell/koc126 or 10.1093/plcell/koc126"
![Image](https://user-images.githubusercontent.com/1572885/187266088-bbdfb4d9-df2d-43f1-9f6d-3f16b6f5cd1e.png)

### Publication year (in publication details)
"e.g. 2022"
![Image](https://user-images.githubusercontent.com/1572885/187266020-9c8badc3-71f6-4e3f-b97b-852d0bddfe4a.png)

### Other license (in full text details)
"e.g. https://creativecommons.org/licenses/by/4.0"
![Image](https://user-images.githubusercontent.com/1572885/187266525-ad055781-bc55-4f52-9fcc-578cc377595d.png)

## Replacements
Some fields still have a placeholder text – however this is not an accessible pattern. We will replace it with help text.

Publication details
![Image](https://user-images.githubusercontent.com/1572885/185960083-acdf77cf-92e1-40f2-880b-3e421d7112dc.png)

Dataset identifier
![Image](https://user-images.githubusercontent.com/1572885/185960601-ed1a9a8c-fefe-4418-a2bd-bdbf653b5d76.png)

Dataset details
![Image](https://user-images.githubusercontent.com/1572885/185960835-e7649c19-7d7c-4ca7-8aa8-f8b4d2e3c3cd.png)

## Removals

To avoid confusion, bugs or UX problems we will also remove some placeholders.

Dataset title
![Image](https://user-images.githubusercontent.com/1572885/185960668-e1d65241-acc9-441a-81f2-2f28be6176f8.png)

Dataset abstract
![Image](https://user-images.githubusercontent.com/1572885/185961056-d89a3d32-d35b-440f-b20e-fbaa9eecf853.png)

# Context
In the old Biblio, suggestions for values were made by given examples in grey text in the text box.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/151006768-8aa16e4f-6fe0-45c1-a255-a5ba94c64486.png)

**Comment by nicolasfranck** [comment]
Note: also known as placeholders

**Comment by nicolasfranck** [comment]
@sdebodt for everything? In the old interface there were sometimes too many placeholders in my opinion.

**Comment by nicolasfranck** [comment]
TODO: placeholder not too dark? Can hardly see the difference with filled in values

e.g. "Other license" is not filled in, and so shows its placeholder:

<img width="1158" alt="Screenshot 2022-04-21 at 12 00 31" src="https://user-images.githubusercontent.com/494636/164431425-8ebe90fe-36a1-4c51-9ea9-6dbf9dd27f5a.png">

**Comment by sdebodt** [comment]
A few additional placeholders to add (not urgent):

**Publications:**
- [ ] DOI: https://doi.org/10.1093/plcell/koc126 or 10.1093/plcell/koc126
- [ ] Publication year: 2022
- [ ] Other license: https://creativecommons.org/licenses/publicdomain/

**Comment by sdebodt** [comment]
revisit when approach for helper text below input fields is developed.

**Comment by mietcls** [comment]
Will be fixed by #346

**Comment by mietcls** [comment]
Good to know, the https://creativecommons.org/licenses/publicdomain/ website has been retired. I'll make the same suggestion as for the datasets under "other licenses".

**Comment by nicolasfranck** [comment]
so any style guides on how to do this?

**Comment by mietcls** [comment]
@nicolasfranck the component link in the issue shows the design and the html for it: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text. Is that sufficient or did you mean anything else?
