### ISSUE TITLE
improve project search

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#289]
**Describe the improvement**
To identify a relevant project, a search needs to be done in the Add project pop up. Sometimes, the search results are not correct. 

"agriculture in": no results (screenshot 1)
"agriculture in Europe": 2 results (screenshot 2)

Can partial text matching be added? Otherwise the user needs to know the exact word or combination of words, which would mean that he would probably needs to search ResearchExplorer/GISMO first.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/152768798-dec826da-0226-4ea9-b825-aedafb02689f.png)
![image](https://user-images.githubusercontent.com/72742841/152769063-ac15fc47-02fd-437c-82a9-f5fed96a3c98.png)

**Comment by nicolasfranck** [comment]
@sdebodt the examples you provided are not the result of lack of partial text matching, at least at first sight.
Partial text matching is more like "agri" that should match "agriculture". If nothing matches
for "agriculture", then there is something wrong with that index.

**Comment by nicolasfranck** [comment]
```
template: layouts/htmx:7:2: executing "layouts/htmx" at <yield>: error calling yield: template: publication/projects/_modal_hits:17:40: executing "publication/projects/_modal_hits" at <pathFor "publication_projects_add_to_publication" "id" $.D.Publication.ID "project_id" $hit.ID>: error calling pathFor: mux: variable "PL_ERA_IP_6_2008/6/2008" doesn't match, expected "^[^/]+$"
```
Results are found, but biblio-backend breaks on their identifiers when they contain forward slashes

**Comment by sdebodt** [comment]
Indeed, the partial text match is something that I would implement in addition to the fix for the example that I showed where using two words gives a different result than using three words of the project title.

**Comment by nics** [comment]
- partial match search works now (can use some future refinement)
- fix project ids with slashes

**Comment by sdebodt** [comment]
It seems that too many results are now returned...

![image](https://user-images.githubusercontent.com/72742841/155955431-26be3c51-2f6c-44ba-87ec-70e377d0d485.png)

**Comment by nics** [comment]
also known id search returns results with other ids

**Comment by nics** [comment]
@nicolasfranck can you take a look?

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/librecat
