### ISSUE TITLE
temporarily remove collapse/expand button for header

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#291]
**Describe the improvement**
Currently, it is confusing as to what the collapse/expand button does. Some users think this button expands/collapses the metadata sections, while it actually expands/collapse the summary header. This could be caused by the placement of the button next to the metadata tabs. 

Short term action is to remove this button. 

Longer term action is to rethink the design of the header to save space (less information in header) and/or to automatically collapse it when scrolling down. Less information could be only the title, status, biblio id.

**Comment by nics** [comment]
ok

**Comment by sdebodt** [comment]
The expand/collapse button has been removed and the header only contains the title as intended.
![image](https://user-images.githubusercontent.com/72742841/154266718-1abb15c6-7832-4f58-b15e-610dfcc14af5.png)

However, after editing the dataset details, the complete header appears again.
![image](https://user-images.githubusercontent.com/72742841/154266857-331a7a42-744d-494c-b9db-987745be88fc.png)

**Comment by nics** [comment]
ok
