### ISSUE TITLE
change author to creator in affiliation 

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#306]
**Describe the improvement**
In the creator popup for datasets, the title is adapted to "Creator" but in the section where you can indicate the UGent members, it says "author". Can this be changed to creator?

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/155357526-a640f3ec-bf49-48a3-8695-2a6bd81b6b14.png)

**Comment by nicolasfranck** [comment]
Isn't the label itself a bit problematic? I mean, a label like "UGent creator" with options "External creator" and "UGent creator" doesn't make sense to me. Also goes for "Ugent author" of course"

**Comment by sdebodt** [comment]
yes, this change of column header is described in https://github.com/ugent-library/biblio-backend/issues/323

**Comment by nics** [comment]
fixed by #333

**Comment by sdebodt** [comment]
One more to change from "Author" to "Creator": blue "Confirm" button.
![image](https://user-images.githubusercontent.com/72742841/166646905-df062fab-9403-486b-8ca2-995f537cda0e.png)

**Comment by netsensei** [comment]
Should be fixed now (see next deploy to dev)
