### ISSUE TITLE
biblio ids start from 1 on dev

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#313]
**Describe the improvement**
On dev, biblio ids for records recently generated (up to 3 weeks ago) are not continuing on existing ids but started at id = 1, id =2, ...

This is the case for publications and datasets.

Is this intentional/because of the dev database linked to this instance since 3 weeks?

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/156327300-20a66536-4ed2-49ae-92b6-008ea3d18242.png)
![image](https://user-images.githubusercontent.com/72742841/156327408-26340549-ef71-4422-92f9-38536c40c2f1.png)

![image](https://user-images.githubusercontent.com/72742841/156327817-7402841d-3223-4510-90d5-fc1661c4891c.png)

**Comment by nics** [comment]
@sdebodt fixed now
