### ISSUE TITLE
extend validation on license to "Other license" field

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#314]
**Describe the improvement**
The validation for datasets at point of publishing checks whether a license is provided in the "License" field. If that field is empty, but a license (free text) is provided in the "Other license" field, an error is given when publishing. Validation should check both fields. If one of both is filled, no error should be given.

![image](https://user-images.githubusercontent.com/72742841/156329380-31b5ff4d-7271-448f-a7df-3254452155a8.png)

**Comment by nics** [comment]
see https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/1ebdf0ed89ceeb2042331b00684b78c8eba58c21
