### ISSUE TITLE
conference contribution vs proceedings paper

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#315]
**Describe the improvement**
Currently, conference contributions can be added in two ways
- publication type "Conference Contribution" > Conference type "Preprint", "Poster", "Abstract", "Other"
- publication type "Journal article" > Article type "Proceeding paper"

Is there a particular reason why it was implemented like this? If I am not mistaken, in the old Biblio, proceeding papers are part of Conference Contribution.

**Comment by netsensei** [comment]
Should be fixed with next roll out.
