### ISSUE TITLE
change of access level from embargo to open does not result in empty embargo period

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#316]
**Describe the improvement**
When changing the access level from "embargoed access" to "open access", the "embargo period" and "access level after embargo" should be cleared.

I was able to publish a dataset with access level "open access" and the embargo period filled in (see screenshot), so validation is not yet checking this.

(Note: for publications, the embargo period and access level after embargo fields disappear when changing from UGent access to open access. The fields are cleared upon save. --> OK)

Original implementation: https://github.com/ugent-library/biblio-backend/issues/217#issuecomment-994853370 (disabling as described here does not work anymore)

https://backend.bibliotest.ugent.be/dataset/8630402

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/158138218-727e3913-e17d-4838-8650-bf7b2face964.png)

**Comment by netsensei** [comment]
Should be fixed with next release to `dev` environment.

**Comment by sdebodt** [comment]
Embargo period and access level after embargo are greyed out when moving from embargoed access to open access. Entered values are still visible in Edit mode. When subsequently changing from open access to embargoed access, values for embargo period and access level after embargo are cleared. I would expect the previously greyed out values to be shown in the last step or that the values are immediately cleared when selecting open access.
