### ISSUE TITLE
easier assignment of UGent affiliation to authors

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#322]
**Describe the improvement**
Currently, users consider assigning the UGent affiliation to authors as time consuming as a new window needs to be opened for each new author.

Two complementary options:

- change in design (e.g. by adding affiliation in main view instead of in the add/edit modal)
- automation of assignment of affiliation (e.g. by checking if authors are UGent members, by checking whether the affiliation can be retrieved from CrossRef/DataCite, by checking whether the ORCID can be useful)

Split up into multiple stories:
- First steps:
  - Show affiliation in overview #465 
  - I can add authors and editors to a record: https://github.com/ugent-library/biblio-backend/issues/397
- Next steps:
  - I can see my department added to "departments" when I create a record https://github.com/ugent-library/biblio-backend/issues/482
- Advanced steps: Departments are automatically suggested based on added authors
  - https://github.com/ugent-library/biblio-backend/issues/505

**Comment by mietcls** [comment]
@sdebodt Is this also important for secretariats, or mostly for reviewers?

**Comment by mietcls** [comment]
Suggestions

Repositioning information: move authors and editors underneath publication details
- for researchers, this view will become simpler (as for the librarians, see https://github.com/ugent-library/biblio-backend/issues/426

![Authors affiliation - researcher](https://user-images.githubusercontent.com/1572885/175903107-48005409-cb6f-4d72-858a-6e2a5bdcf110.png)

- for curators and reviewers, it will be repositioned
![Authors affiliation - librarian](https://user-images.githubusercontent.com/1572885/175903211-6ff076d3-28ed-4d58-b110-1d12fd75096b.png)


Adding affiliations:
1. Add affiliation to authors table
![Authors affiliation 2](https://user-images.githubusercontent.com/1572885/175901448-da2543c3-f1db-4e20-8ca0-8a5974116c63.png)
2. Add affiliation information to affiliation in authors table (can be implemented later)
![Authors affiliation](https://user-images.githubusercontent.com/1572885/175901454-3b1c852a-5266-4af3-862a-b5fcb89f8d52.png)
3. Automated suggestions (can be refined later)

**Comment by mietcls** [comment]
Updated the story with the different stories that came out of this one. Will label it as duplicate.
