### ISSUE TITLE
unexpected terms and privacy notice upon first login

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#327]
**Describe the improvement**
As also reported by Inge, unexpected terms and privacy notice was shown upon first login.

De gebruiksvoorwaarden en privacybeleid verwijzen ook naar arteveldehogeschool en de app waddist.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/162401776-74b17e78-2765-41ae-b692-740bdd28dcad.png)

**Comment by sdebodt** [comment]
It was an observation from someone in the test group (beginning of April), so https://backend.bibliotest.ugent.be/.

**Comment by mietcls** [comment]
Probably to be picked up with Inuits.

**Comment by mietcls** [comment]
Did this also appear in the non-test version? https://backend.biblio.ugent.be/

**Comment by mietcls** [comment]
To be watched, need to find a way to reproduce

**Comment by mietcls** [comment]
Closing for now until it reappears
