### ISSUE TITLE
show who registered the publication/dataset

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#329]
**Describe the improvement**
Currently, in the backend, users cannot see who has registered the record. e.g. for records that the user is author/creator of, that user might not be the person that did the registration.

Also reviewers need to see who did the registration.

**Comment by mietcls** [comment]
https://github.com/ugent-library/biblio-backend/issues/471 is a duplicate – however will add the nuance on what to show in overview VS detail page
