### ISSUE TITLE
report on what needs to be improved upon publish

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#331]
**Describe the improvement**
Upon clicking publish, errors can be given that metadata is missing. To help the user to identify what is missing and where to add it, create an overview with link to relevant field.

Current summary shows all sections in green, while mandatory metadata is missing and/or an error is reported.

"There are some problems with your input."  what is wrong? message is e.g. given when fake data for ISSN or WoS ID is entered.

Complementary to completeness bars? Or direct completeness bars for this purpose?

**Comment by mietcls** [comment]
What are the business rules applied now for displaying a success in the summary?
If they are not clear yet, I would op to hide the summary page until we have that sorted – as we are creating a false sense of security.

**Comment by mietcls** [comment]
Replaced by validation upon publish

<img width="1003" alt="Schermafbeelding 2022-08-23 om 10 17 07" src="https://user-images.githubusercontent.com/1572885/186108297-38e3d962-f460-4f64-a825-a92fc55a71fb.png">
