### ISSUE TITLE
license after embargo period cannot be added

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#332]
**Describe the improvement**
When access level of a publication is set to UGent access or private access, the license field to select a CC license is not shown. Consequently, in case of embargo, if the access level is open after the embargo period, the user cannot select a CC license (but only "Other license").

When "Access level after embargo" is set to "Open access", the license field (for CC licenses) should appear.

**Screenshots**

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/72742841/163221526-330bb36d-f8e7-43b0-9c37-094b65aa2b4a.png)

**Comment by netsensei** [comment]
The entire logic had been grown organically across a set of different JavaScript files. The framework we use to wire in interactivity, leverages server-side rendering of HTML fragments instead. I have ported and consolidated the entire conditional logic, which steers how this feature behaves, towards the back-end.

Once released on the `dev` branch, this will require renewed testing to ensure the form keeps behaving as intended.

**Comment by sdebodt** [comment]
I think this is completed.
