### ISSUE TITLE
add links to new research tips for dataset registration

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#335]
**Describe the improvement**
More elaborate documentation is being developed on the registration of datasets (and publications) using the new Biblio backend.

Consequently, updates of tooltips/links in Biblio backend to add the links to new research tips is needed.

- [x] General tip on registration of datasets: https://onderzoektips.ugent.be/en/tips/00002054/ 
Not sure where to add this one. Maybe as an additional sentence in the first step of the registration workflow?
- [x] Step-by-step guidance: https://onderzoektips.ugent.be/en/tips/00002055/
Same here. Also add in the first step of the workflow?
- [x] Data format: https://onderzoektips.ugent.be/en/tips/00002058/
Extend existing tooltip
- [x] License: https://onderzoektips.ugent.be/en/tips/00002057/
Extend existing tooltip
- [x] Access level: https://onderzoektips.ugent.be/en/tips/00002057/
Extend existing tooltip
- [x] Projects: https://onderzoektips.ugent.be/en/tips/00002060/
Add link to line "Select one or more projects..." in "Select projects" popup
- [x] Creators: https://onderzoektips.ugent.be/en/tips/00002059/
Add tooltip next to "Creators" in main title bar of the Creators panel
- [x] Publications: https://onderzoektips.ugent.be/en/tips/00002061/
Add tooltip next to "Related publications" in main title bar of the Related publications panel as well as add to sentence "Select one or more publications..." in the "Select publications" popup.

- [x] Data repositories: https://onderzoektips.ugent.be/en/tips/00002071/
If your dataset is not yet in an external repository, have a look at [our research tip on sharing data in a data repository](https://onderzoektips.ugent.be/en/tips/00002071/)

**Comment by nicolasfranck** [comment]
See https://github.com/ugent-library/biblio-backend/pull/343

**Comment by sdebodt** [comment]
@nicolasfranck, I have added an extra research tip link above, for instructions on how to share data in a repository (to be added in the first step of the add dataset workflow).

**Comment by nics** [comment]
ok

**Comment by sdebodt** [comment]
For the documentation in step 1 of the add dataset workflow, there is now redundant info.

"If your dataset is not yet in an external repository, have a look at [our research tip on sharing data in a data repository](https://onderzoektips.ugent.be/en/tips/00002071/)" should move to the panel "Dataset not yet in external repository?" and the original sentence should be removed.

![image](https://user-images.githubusercontent.com/72742841/166951603-1a8eaf41-4fcd-4bde-a2ba-6a1c858fade4.png)

**Comment by nics** [comment]
@sdebodt done
