### ISSUE TITLE
add links to new research tips for publication registration

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#336]
**Describe the improvement**
More elaborate documentation is being developed on the registration of publications (and datasets (described in https://github.com/ugent-library/biblio-backend/issues/335)) using the new Biblio backend.

Consequently, updates of tooltips/links in Biblio backend to add the links to new research tips is needed.

- [x] General tip on registration of publications: https://onderzoektips.ugent.be/en/tips/00002064/ 
Not sure where to add this one. Maybe as an additional sentence in the first step of the registration workflow?
- [x] Step-by-step guidance: https://onderzoektips.ugent.be/en/tips/00002065/
Same here. Also add in the first step of the workflow?
- [x] Different full text versions: https://onderzoektips.ugent.be/en/tips/00002066/
Add to tooltip next to "Publication version" in full text popup.
- [x] Access level full text:  https://onderzoektips.ugent.be/en/tips/00002066/#Howtochoosetherightaccesslevelinbiblio
Add to tooltip next to "Acess level" in full text popup
- [x] WoS import: https://onderzoektips.ugent.be/en/tips/00002067/
replace link "Web of Science import instructions" below upload box
- [x] other import: https://onderzoektips.ugent.be/en/tips/00002068/
add link "import instructions BibTex or RIS" below upload box (to check with @nics whether these file types are expected for the second upload box)
- [x] Projects: https://onderzoektips.ugent.be/en/tips/00002060/
Add link to line "Select one or more projects..." in "Select projects" popup
- [x] Datasets: https://onderzoektips.ugent.be/en/tips/00002061/
Add tooltip next to "Related datasets" in main title bar of the Related datasets panel as well as add to sentence "Select one or more datasets..." in the "Select datasets" popup.

**Comment by nics** [comment]
ok

**Comment by sdebodt** [comment]
> @sdebodt fixed https://onderzoektips.ugent.be/en/tips/00002065/ but `https://onderzoektips.ugent.be/en/tips/00002066/#Howtochoosetherightaccesslevelinbiblio?` should be renamed

I changed the link to https://onderzoektips.ugent.be/en/tips/00002066/#ChoosetherightaccesslevelinBiblio
