### ISSUE TITLE
Replace tooltips by help text below the input element

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#339]
Currently we are misusing tooltips to show help texts for an input.
Tooltips should be short, as they disappear when the mouse pointer
gets out of focus. That becomes even more problematic when you want to add links
inside that tooltip that cannot be clicked because the tooltip closes too fast.

Why not add a help text below the input element? They are never out of sight.

Example: https://getbootstrap.com/docs/5.0/forms/validation/#server-side

See also:

#335 
#336

@nics @mietcls @netsensei

**Comment by mietcls** [comment]
I prefer help text as well, as it provides the context when you need it immediately. If we don't overuse it I'm 100% pro (I do see a lot of times where it's used –we could invent a pattern where we add "info" as an external link to be clicked).

**Comment by sdebodt** [comment]
The help text is a good suggestion for short guidance. However, in some cases the text we want to show is much longer and in other cases we want to mainly have a link to a research tip.

**Comment by nicolasfranck** [comment]
> I prefer help text as well, as it provides the context when you need it immediately. If we don't overuse it I'm 100% pro (I do see a lot of times where it's used –we could invent a pattern where we add "info" as an external link to be clicked).

Yup, some "help/info" link that can be clicked to open

**Comment by netsensei** [comment]
Closing this issue. I've created a separate user story with a set of concrete tasks and acceptance criteria.

#346
