### ISSUE TITLE
Librecat API throws an invalid response on a potential validation error on the "Year" field

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#34]
**Describe the bug**

When saving a publication ("publication details") via the Librecat API, Librecat doesn't return proper errors which can be handled on the Go side. This problem pertains to this class of errors:

* Changing "Year" field with a string (eg. "1999abc") yields an empty object as a JSON response (`{ }`)

**To Reproduce**

1. Use Postman or CURL
2. Get a record via the API as a JSON object
3. Change the values of the record accordingly
4. Post the updated record to the API and read the output returned by the API.

**Expected behavior**

Proper errors where applicable.

The current logic just merges whatever `form.Values` it receives from a POST request into the `Publication` struct. This allows form injection on the client side.  We need a separate `publication_details` struct (DTO / Data Transfer Object) on the server side which mirrors the available fields on the form. When the POST returns, only the values which are defined in the DTO will be used to merge in the final `Publication` model which will be send to the API.

**Comment by netsensei** [comment]
Needs testing of the API. Might be a API response which doesn't work on validation.

**Comment by nicolasfranck** [comment]
Somewhere deep down the rabbit hole I see this exception in the ElasticSearch log:

```
Caused by: java.lang.IllegalArgumentException: Invalid format: "1999abc" is malformed at "abc"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187) ~[joda-time-2.10.1.jar:2.10.1]
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826) ~[joda-time-2.10.1.jar:2.10.1]
	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parse(DateFieldMapper.java:249) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.mapper.DateFieldMapper.parseCreateField(DateFieldMapper.java:457) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:295) ~[elasticsearch-6.5.4.jar:6.5.4]
```

but the data is accepted by the LibreCat schema, is stored in the database..

**Comment by nicolasfranck** [comment]
`ugent/fixes/index_publication.fix` should delete the year field before indexing if it is not 4 digits

**Comment by nicolasfranck** [comment]
For all 256K records I see the following values in the field `year` 

* `""`: 2417
* `"s.d."`: 7538
* valid: rest

@nics 

I checked this locally, so the results may be cluttered by local tests of imports.

**Comment by nicolasfranck** [comment]
cf. https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/592

**Comment by nics** [comment]
@nicolasfranck I think this can be closed now?

**Comment by nicolasfranck** [comment]
yes
