### ISSUE TITLE
provide guidance on add publication methods

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#341]
# Story

Provide guidance on add publication methods.

## Clarification

The first step of the add publications workflow consists of a choice between 4 methods (WoS, identifier, manual, BiBTex). Add guidance such that users know what each method entails and which method is recommended.

# Success criteria

- [ ] With each step our researcher public is informed of the best option
- [ ] The entire card is clickable
- [ ] The radio and label are bound together

# Implementation

## Example

<img width="1038" alt="Schermafbeelding 2022-08-24 om 12 19 10" src="https://user-images.githubusercontent.com/1572885/186394267-cc30a90b-1692-41ef-9413-ec167f2434b5.png">

## Component

https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-radio-card.html#component-02-radio-cards-2-lines

> PROBLEM: current component is in violation with HTML5 guidelines. A label is a block level element, that cannot contain other elements inline. We are allowed to use elements such as `<span>`, `<small>` and `<input>` elements inside. Right now we use `<div>` and another `<label>` element inside. Furthermore we use the aria-selected attribute on the label element as well.
Checked on https://validator.w3.org.

To be fixed in a different issue.

### Text

**Import from Web of Science**
Import one or more publications. This option will give you the most complete results.

**Import via an identifier**
 You can use DOI, PubMed ID or arXiv ID. A good second option.

**Enter manually**
 Create a publication record from scratch using a template. Recommended for publications such as dissertations.

**Import via BibTex**
Can import multiple publications via library files.  Use this option if there is no Web of Science import or identifier import is available.

# Context

It's not always clear which option to choose for your specific case.

## Current implementation

![Image](https://user-images.githubusercontent.com/1572885/186392142-aac3c0f6-2682-4277-9807-7f37ebbf48cc.png)

**Comment by sdebodt** [comment]
@sdebodt to provide helper text

**Comment by sdebodt** [comment]
asked for feedback.nMyriam and Inge are on holidays this week, so response not expected before May 10th.

**Comment by sdebodt** [comment]
After consultation with Myriam and Inge, we propose to adapt the first step of the publication workflow using this text (for methods and according guidance)

- Import from Web of Science: the most comprehensive approach for import of one or more publications, preferred when publications are included in WoS
- Import via an identifier: import of one publication based on DOI, PubMed ID or arXiv ID
- Enter manually: create a publication record from scratch (e.g. a dissertation) using a template
- Import via BibTex: less comprehensive approach for import of one or more publications e.g. from an existing reference library file

**Comment by mietcls** [comment]
To double check: does clicking the boxes still behave weird #398
