### ISSUE TITLE
missing classification from some publications in old biblio backend

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#358]
**Describe the improvement**
Missing classification in old biblio backend: bv. 8752574 in publications overview.

![image](https://user-images.githubusercontent.com/72742841/168028705-fc598506-8b37-48ec-a31f-a537bf1988ab.png)

**Comment by nics** [comment]
ok, resolved in librecat by https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/5900f69fb2614e99da4ee0b026015bebff2a93bb

**Comment by mietcls** [comment]
Is this applicable to new records only, or also backwards compatible?
