### ISSUE TITLE
records reviewed in old backend can still be edited in new backend

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#359]
**Describe the improvement**
A record that has been entered in the new backend, reviewed and put to status "locked" in the old backend can still be edited in the new backend. The status of the record after review is "Biblio Validated". 

Marthe reported that locked records should not be editable anymore.

Both myself and Marthe could edit the record. The status of the record remains "Biblio Validated". Not sure whether the submitter and/or author can still edit.

e.g. https://backend.biblio.ugent.be/publication/8752363

**Comment by nics** [comment]
marthe you and have reviewer rights, normal users have no edit rights anymore

**Comment by sdebodt** [comment]
ok. looks good indeed. I added Dries Moreels as other and then tested logged in as drmoreel. Then edits are not possible.
