### ISSUE TITLE
librcat add file call does not set content type

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#37]

**Comment by nicolasfranck** [comment]
`Content-Type` during download of file: ok

**Comment by nicolasfranck** [comment]
`Content-Type` of response after successfull upload: `application/json`

**Comment by nicolasfranck** [comment]
TODO: remove cookies from calls

**Comment by nicolasfranck** [comment]
https://github.com/ugent-library/biblio-backend/commit/bebaec3046ff59c72ab3f68802cf8567ff67ff84

**Comment by nics** [comment]
ok
