### ISSUE TITLE
biblio frontend glue epic

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#389]
# Epic

When a record is changed in the back-office, that it is adapted in the front-office.
When someone in the front-office wants to do a download, it is downloaded from the back-office (where they are)
Feature switch 
API for back-office (no more cronjobs etc), which the front-office can pull from

Tentative; data model switches

## Success criteria

- [x] ~~fix that converts biblo-backend json to biblio frontend json~~ biblio backend endpoint that serves frontend json
- [x] update biblio frontend index_publications command to use this api
- [x] file resolver

## File resolver

is handled by this apache rewrite rule:
`RewriteRule ^/publication/([0-9]+)/file/([0-9]+)(\..+)?$ /download/$1/$2 [L,PT]`

we have to reimplement the librecat lib/LibreCat/App/Catalogue/Route/file.pm download function in biblio backend

# Future: GRPC
- Communication framework -> lingua franca van het Biblio ecosysteem
- Protocol buffers 🐝 (abstract datamodel schrijven) -> spreken met Biblio engine
- Split off front-end of back-end
- REST API can evolve out of this
- Swagger docs

Later: #695

**Comment by netsensei** [comment]
Biblio frontend = https://biblio.ugent.be

**Comment by nicolasfranck** [comment]
wat moet er hier gebeuren?

**Comment by nics** [comment]
first task is a fix that converts biblo-backend json to biblio frontend json

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/40

**Comment by mietcls** [comment]
Mentioning https://github.com/ugent-library/biblio-backend/issues/494 for GISMO

**Comment by nics** [comment]
see https://github.ugent.be/Universiteitsbibliotheek/biblio/commit/19b4c1e530d7f1f0b8d29b11941742ef2e2a7dba
