### ISSUE TITLE
I can delete a publication from the publication overview page

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#4]
**Story**

As an user (author, reviewer,...) I can delete a publication entirely from the system. This allows me to clean up unwanted, stale,... publications and their associated data.

**Success criteria**

- [x] The "actions" menu contains an option "Delete".  This menu is available on the summary of a publication on the publication overview page, and the publication detail page.
- [x] When I click on "Delete", I can see a modal popup asking for confirmation with two buttons "cancel" and "delete"
- [x] When I click "Cancel", the popup closes and I'm returned to the publication overview. Nothing happens.
- [x] When I click "Delete", the publication (metdata) with all associated artefacts (files, datasets, etc.) is "soft deleted" from the system.
- [x] After deleting, the "publication overview page" is completely reloaded. This will show an updated list of publications minus the deleted publication.

**Additional information*

=> The mockups seem to be missing a confirmation message that the publication was successfully deleted from the system. Clicking "Delete" simply reloads the page without any obvious cues that anything concrete has happened.

**Comment by phochste** [comment]
@netsensei what does this "delete" mean in archiving context? E.g. does this include deleting publications that were already part of the scholarly/institutional record?

**Comment by nics** [comment]
@phochste same soft delete behaviour that the current backend has

**Comment by netsensei** [comment]
Changed the story to "soft deleting" the record and its associated artefacts.
