### ISSUE TITLE
volume and issue not extracted during doi-based import

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#404]
**Describe the improvement**
Although the CrossRef metadata contains the volume and issue of a journal, this info is not filled in the Biblio form.

example: 
- Biblio ID: https://backend.bibliotest.ugent.be/publication/8630817 
- DOI: https://doi.org/10.1093/plphys/kiac067
- CrossRef metadata: https://api.crossref.org/v1/works/10.1093/plphys/kiac067

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/172845515-29c8ead3-6064-4a41-ab01-b1df20c5f661.png)

**Comment by nicolasfranck** [comment]
@sdebodt @nics the current implementation in the branch "snapstore"
implements it correctly: https://github.com/ugent-library/biblio-backend/blob/snapstore/internal/backends/crossref/client.go#L186

So blues skies coming your way

**Comment by mietcls** [comment]
Todo: test

**Comment by sdebodt** [comment]
I tested this on eliot1 and it was fine.
