### ISSUE TITLE
credit role of authors cannot be removed

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#409]
**Describe the improvement**
Not able to deselect author credit role, once you have selected a credit role.

**Comment by nicolasfranck** [comment]
Update: to be seen after rebuild of flow charts

**Comment by mietcls** [comment]
@nicolasfranck which flow charts are you referring to?

**Comment by nicolasfranck** [comment]
@netsensei told me that the complete layout of the modals of the contributors would be rewritten by Emily, not?

**Comment by nics** [comment]
@nicolasfranck yes correct
