### ISSUE TITLE
article type should not be set to "Original article" when saving in edit mode

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#411]
**Describe the improvement**
When a publication record for a journal article is created, the Article type is empty. However, after clicking edit, the Article type is automatically set to "Original article" (the first one in the list), even though the use did not set the Article type. This is the case for both import based on DOI as well as WoS import (and I guess the BibTex import as well).

Out of scope:
- Extract the Article type from the metadata automatically. Logged in https://github.com/ugent-library/biblio-backend/issues/495

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/173822441-0ccddf2c-1b1a-4cb2-a246-f58ea1f3d949.png)

![image](https://user-images.githubusercontent.com/72742841/173822477-b967d756-b6e4-44ce-812f-b920f7b359e3.png)

**Comment by mietcls** [comment]
This one will be easier to do when the foundations have been completed.

To do: make it possible to select an empty option.

**Comment by mietcls** [comment]
@nicolasfranck do you need a mapping for an empty selection?

**Comment by nicolasfranck** [comment]
@mietcls no, I was merely reacting to Stefanie's remark "If possible, extract the Article type from the metadata automatically."

**Comment by sdebodt** [comment]
We can keep it empty right now and check later if automation is possible.

**Comment by mietcls** [comment]
I'll make a separate issue out of it.
