### ISSUE TITLE
When someone else is editing the same publication, I get a warning

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#416]
# Story (adapted since 17/08/2022)

When someone else is editing the same publication, I get warned.

# Success criteria
- [ ] I am informed someone else is editing as well, and I might lose my changes
- [ ] I get the opportunity to quickly copy my outstanding changes, so I do not lose them

# Solution

There are two ways of being informed: via a modal and an alert in the header of the form.

A modal appears the moment Biblio notices there is a conflict. The modal informs the researcher something went terribly wrong.
The inline alert in the header of the form keeps the researcher informed of the problem after closing the modal, but still gets the opportunity to copy the changes.
If the researcher tries to publish again, they'll see the modal again to avoid any confusion.

### Component
<img width="949" alt="Schermafbeelding 2022-08-17 om 14 02 01" src="https://user-images.githubusercontent.com/1572885/185113675-541c3a62-ef51-47bf-aab4-d671cc69f2a4.png">
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-09-modal-blank-slate](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-09-modal-blank-slate)

### Title
**Cannot publish changes. Please copy your edits and refresh the page.**
### Text
The content you are editing has been changed by someone else. You can edit the document again after refreshing.
### Action
Close

### Component
<img width="1440" alt="Schermafbeelding 2022-08-17 om 14 08 20" src="https://user-images.githubusercontent.com/1572885/185114725-5ff1140a-e535-4466-aeb3-08cab741fdf8.png">
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-alerts.html#component-03-b-alert-danger](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-alerts.html#component-03-b-alert-danger)

### Body
The publication you are editing has changed by someone else.  Please copy your edits and refresh the page.

# Out of scope
- Conflict resolution where you can see who has edited what, and pick "the winner"

**Comment by mietcls** [comment]
Suggestion for content and layout, do adapt if needed @emilyvandewalle!

# Content
The content you are editing has changed.  Please copy your edits and refresh the page.

# Possible outcomes

## Researchers

### context
![Image](https://user-images.githubusercontent.com/1572885/175911170-13990166-0d43-40cc-9a61-d4b6094321ea.png)
### warning on top
![Image](https://user-images.githubusercontent.com/1572885/175911168-7c776c45-2d20-4d6f-81a4-c5235734f78a.png)
### when they click save
![Image](https://user-images.githubusercontent.com/1572885/175911169-d1b139df-aa2f-49e3-87fe-57953a220835.png)

## Librarians

### context
![Image](https://user-images.githubusercontent.com/1572885/175910849-485c3d54-05c2-440c-a1f5-2d77b6630cf6.png)
### warning on top
![Image](https://user-images.githubusercontent.com/1572885/175910850-8fce00c6-f74f-4290-83f6-4f668b2745c9.png)
### when they click save
![Image](https://user-images.githubusercontent.com/1572885/175910851-676fc9ec-b07b-4712-84fa-8aae7f153468.png)

**Comment by mietcls** [comment]
Do you still have any remarks here @emilyvandewalle, @nics or @netsensei?

**Comment by nics** [comment]
hi @mietcls can't the 'warning on top' variant be easily missed if it's scrolled out of the viewport?

**Comment by mietcls** [comment]
@nics true. I would suggest:
- Get a modal when it happens.
- Be able to close the modal to copy your changes, but still have the message on top – we could move it in the header instead of in the form.
- Show the modal again if you try to hit "publish" again.

**Comment by emilyvandewalle** [comment]
Looks good to me! 

I think showing a modal when it happens could be good as it disrupts the editing and makes sure the user acknowledges it. I also think it's a good idea to keep the message in the overview as well 👍
 
Maybe we can use a [modal with a danger blankslate](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-09-modal-blank-slate), what do you think?

<img width="942" alt="image" src="https://user-images.githubusercontent.com/36261498/179183284-88fe5ffe-77c2-4a23-8cd4-0d6d770c1d45.png">

**Comment by mietcls** [comment]
That will definitely come in handy. Thanks!

**Comment by mietcls** [comment]
Later: be proactive about showing that there is an other person editing

**Comment by netsensei** [comment]
This has been implemented everywhere. We might need some additional testing just to ensure things work in a consistent and correct manner.
