### ISSUE TITLE
Anchor links to tabs on the detail pages don't work

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#42]
**Describe the bug**

On the detail page of a publication / dataset, several tabs are shown: description, full text, authors & editors,...  These tabs are dynamically loaded. The even have an anchor link (e.g. http://localhost:3001/publication/8158110#contributors-content)

When directly navigating to an anchor link, the corresponding tab isn't loaded. The default "description" tab is always shown.

**To Reproduce**

1. Go to the detail page of a publication.
2. Right click on a tab link and copy the link. e.g. authors & editors) the corresponding link will have an anchor.
3. open a new browser tab, copy & paste the link. Then go to the page.
4. Notice how the page shown is always the "description" tab.

**Expected behavior**

I want to see the correct tab loaded when I navigate directly to an anchor link.

**Comment by nics** [comment]
ok
