### ISSUE TITLE
Balance labels in horizontal forms to the right

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#428]
# Story [adapted since 18/08/2022]

Balance the labels closer to the input field, by aligning the text to the right.

![Image](https://user-images.githubusercontent.com/1572885/185416953-7f633231-59b8-49b1-a5cc-bca3c7c16e73.png)

# Context

UX bug that makes inputting fields and reviewing slower. In the forms, the white space between the fields is smaller than the space between the field and the labels to the left of it. That causes the gestalt laws (groupings) to get out of balance, and makes it harder to link field and label together.

![Image](https://user-images.githubusercontent.com/1572885/185417654-3ec60002-a84e-4882-9d7b-9ab2fe12f010.png)

One solution is grouping the labels and the fields closer together.
Another is going back to a vertical structure.

Solution provided based on the discussion below.

# Implementation

- [Documentation example of a horizontal form with right aligned labels](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-horizontal)
- [Publication form with right aligned labels](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html)

**Updates in _settings.bootstrap.scss**
Changed margin bottom from 1.6rem to 2.4rem to increase the spacing between form groups

```
$form-group-margin-bottom:              2.4rem;
```

**Updates in content/scss/bootstrap-additions/_forms.scss**
Added this code to right align the labels according to the responsive grid setup

```
[class^='col-sm-'].col-form-label {
  @include media-breakpoint-up(sm) {
    justify-content: flex-end;
  }
}

[class^='col-md-'].col-form-label {
  @include media-breakpoint-up(md) {
    justify-content: flex-end;
  }
}
```

**Comment by mietcls** [comment]
Can this be solved with CSS only, so we only need to import it?

**Comment by mietcls** [comment]
We can try the suggestion at #328 by Emily to solve the Gestalt Laws issue (grouping) – and if this one proves people to fill out slower or not find information, we can try stacking the labels and the inputs, and review the white space.

**Comment by emilyvandewalle** [comment]
Sounds good to test it out and change if it would slow down the input, let me know if I should provide an example in HTML of the publication form with stacked labels and inputs as well 👍 

- [Documentation example of a horizontal form with right aligned labels ](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-horizontal)
- [Publication form with right aligned labels](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html)

**Updates in _settings.bootstrap.scss**
Changed margin bottom from 1.6rem to 2.4rem to increase the spacing between form groups

```
$form-group-margin-bottom:              2.4rem;
```

**Updates in content/scss/bootstrap-additions/_forms.scss**
Added this code to right align the labels according to the responsive grid setup

```
[class^='col-sm-'].col-form-label {
  @include media-breakpoint-up(sm) {
    justify-content: flex-end;
  }
}

[class^='col-md-'].col-form-label {
  @include media-breakpoint-up(md) {
    justify-content: flex-end;
  }
}
```

**Comment by mietcls** [comment]
Great!

**Comment by nicolasfranck** [comment]
In the examples the word "required" is set to the right of the label.
As that word has always the same length the labels would align nicely,
but not every field needs a "required". Wouldn't lead to a situation like this:

```
<label> REQUIRED <input>
         <label> <input>

````

**Comment by mietcls** [comment]
@nicolasfranck that's okay for now, we'll have to find a way to balance it nicely indeed. This issue tackles the problem that not everyone knows the meaning of the asterisk (like us ITers do), let's start with that.
