### ISSUE TITLE
Re-add "Supplementary Material" as document type

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#434]
**Describe the improvement**
In the old biblio backend, the file type "Supplementary Material" was available. We would like to have this available in the new backend as well. For cases where researchers have made their data available as supplementary material instead of as data in a repository.

Confirmed by Myriam, Inge and Anniek T.

![image](https://user-images.githubusercontent.com/72742841/176667382-9b8a2e85-668f-48c9-8721-18879dc4c0cb.png)

**Comment by nicolasfranck** [comment]
@nics those are the files with `relation` `dataset`, which confused me a bit?
Or is the name a misconception?

**Comment by sdebodt** [comment]
We guess that it was removed at some point to stimulate users to register a dataset instead. As datasets are now a seperate component and no longer a publication type, we want to re-introduce supplementary material to cover these cases in which the authors did not submit the data to a repository but added it as supplementary material to a publication.
