### ISSUE TITLE
opt-out to open access check box

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#440]
# Story

Add opt-out of open access checkbox for auto accepted manuscript versions of journal articles.

## Context

This is the **only** new feature coming for the launch, because we need to comply to the new UGent publication policy.

## Success criteria

- [ ] Show check box for opt-out when publication type = "Journal Article" AND publication version = "AAM"
- [ ] After access level panes and embargo
- [ ] Visible to reviewers as well
- [ ] Link to research tip

### Opt out off
<img width="1440" alt="Schermafbeelding 2022-08-24 om 11 11 26" src="https://user-images.githubusercontent.com/1572885/186379439-355253c6-71f2-4731-baa3-e4175fcd9a79.png">

### Opt out on
<img width="1440" alt="Schermafbeelding 2022-08-24 om 11 11 18" src="https://user-images.githubusercontent.com/1572885/186379505-85879f7a-7afc-4820-8291-da7fb28d7ac2.png">

## Text

Checkbox label
**Opt out** of making the Auto Accepted Manuscript version of this scientific journal article open access automatically.

Help text
Ghent University assumes permission from authors to make the AAM version of their scientific journal articles published in 2023 or later publicly accessible in Biblio after embargo, based on the Belgian Open Access regulation.

Research tip [TODO]
Temporary link: https://onderzoektips.ugent.be/en/tips/00001734/

### Component

[Checkbox](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-inputs.html#component-06-checkbox) and [help text](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text) 

### Code example
```
<div class="form-row">
  <div class="form-group col">
    <div class="custom-control custom-checkbox">
      <input class="custom-control-input" id="customCheck2" type="checkbox">
      <label class="custom-control-label" for="customCheck2">
        <b>Opt out</b> of making the Auto Accepted Manuscript version of this scientific journal article open access automatically.
        <small class="form-text text-muted">Ghent University assumes permission from authors to make the AAM version of their scientific journal articles published in 2023 or later publicly accessible in Biblio after embargo, based on the&nbsp;<a class="c-link" href="TO-BE-FOUND-THE-CORRECT-LINK">Belgian Open Access regulation</a>.</small>
      </label>
    </div>
  </div>
</div>
```

# Context

## Context for researchers and supporting staff:

The Belgian Open Access regulation [add link to research tip when available] gives authors of scientific journal articles the right to make their AAM publicly available after an embargo of 6 or 12 months (depending on discipline), regardless of publisher policies or terms of publishing agreements.

Without opt-out, Ghent University assumes permission from authors to make the AAM version of their scientific journal articles published in 2023 or later openly accessible in Biblio after embargo, in line with the Belgian Open Access regulation. See university policy [add link to research tip when available].

If you do not opt out, a Biblio reviewer will set the "access level after embargo period" for your AAM to open access and set an embargo period if you forget to do so yourself.

## Current implementation

![image](https://user-images.githubusercontent.com/72742841/177159206-1d5612c8-bf35-4b25-84c1-190714e81155.png)

**Comment by mietcls** [comment]
@nics & @netsensei Based on Stefanie's input I've created an example of what the opt-out for AAM versions of journal articles could look like. It does imply conditional behaviour, as it's only for AAM versions of journal articles. What do you think?

@sdebodt as a placeholder I've added the current researchtip that speaks about open access regulation, we can add the other link when it's available. If we can point to a better spot than this one in the meantime, give me a shout.

**Comment by mietcls** [comment]
Suggestion:
- "Fix it for me"
- "I know what I'm doing"

**Comment by sdebodt** [comment]
The check box should reflect whether authors wish to actively opt-out, as this possibility is described in the publication policy. In practice, it has value in knowing whether reviewers need/can fix it, but that is not what we want users to indicate.

**Comment by mietcls** [comment]
@sdebodt no worries, it's more the mindset that I noted down during a meeting – as it's clear that this is complex for a lot of people.

**Comment by mietcls** [comment]
Related https://github.com/ugent-library/biblio-backend/issues/538
