### ISSUE TITLE
Publication type cannot be corrected

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#441]
# Story

Publication type cannot be corrected.

## Context

In some cases, the publication type is not correct in the metadata of CrossRef and consequently also incorrectly assigned in Biblio. To be able to correct these cases, the publication type needs to be editable. However, currently the publication type is fixed. Editing of the publication type was possible in the old backend.

e.g. 10.1038/s41590-022-01214-1
https://www.webofscience.com/wos/woscc/full-record/WOS:000805549900004

Publication type should be "Miscellaneous" but is set to "Journal article" during DOI-based import.

### Screenshots
WoS import:
![screenshot1](https://user-images.githubusercontent.com/72742841/177175251-6adbf291-0f9a-45b9-9c86-a7b1ef6fcc13.png)

DOI import:
![screenshot2](https://user-images.githubusercontent.com/72742841/177175318-ebb9b67a-7803-4325-a8b9-17403ba71833.png)

# Solution
In the first phase can add two warning to the field so the user is informed but not blocked.

## 1. Add information label or helper text

Example info label
<img width="497" alt="Schermafbeelding 2022-08-18 om 09 04 01" src="https://user-images.githubusercontent.com/1572885/185331812-bba2688a-df35-41fe-ad34-6ab1029c3382.png">
<img width="516" alt="Schermafbeelding 2022-08-18 om 09 04 05" src="https://user-images.githubusercontent.com/1572885/185332085-4f47ae2a-f876-4b84-a4d7-254dab6f4c2c.png">

Example helper text
<img width="927" alt="Schermafbeelding 2022-08-18 om 09 17 27" src="https://user-images.githubusercontent.com/1572885/185333715-157089f2-3752-48e9-b473-cfcbf79e8a88.png">

Text
**Changing the publication type might result into data loss.**

### Component

Horizontal form
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-horizontal

Info text
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-01-form-standard](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-01-form-standard)

Helper text
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text)

## 2. Inform user upon change

Example
<img width="506" alt="Schermafbeelding 2022-08-18 om 09 11 13" src="https://user-images.githubusercontent.com/1572885/185332354-351b7223-9faf-4230-ba45-d0d610463a92.png">

Text
**Changing the publication type might result into data loss.**
The fields below are dependant on the publication type. Changing the publication type will replace some fields. Once a field is replaced, the data cannot be recovered.

Component:
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-05-modal-headerless](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-05-modal-headerless)

**Comment by nicolasfranck** [comment]
And changing type is/was in the old backend not without risk: it enables some fields, and removes others that no longer apply within that new type.

Conversion rules need to be discussed.

**Comment by mietcls** [comment]
What are the conversion rules right now?

# First suggestion
In the first phase can add two warning to the field so the user is informed but not blocked.

## 1. Add information label or helper text

Example info label
<img width="497" alt="Schermafbeelding 2022-08-18 om 09 04 01" src="https://user-images.githubusercontent.com/1572885/185331812-bba2688a-df35-41fe-ad34-6ab1029c3382.png">
<img width="516" alt="Schermafbeelding 2022-08-18 om 09 04 05" src="https://user-images.githubusercontent.com/1572885/185332085-4f47ae2a-f876-4b84-a4d7-254dab6f4c2c.png">

Example helper text
<img width="927" alt="Schermafbeelding 2022-08-18 om 09 17 27" src="https://user-images.githubusercontent.com/1572885/185333715-157089f2-3752-48e9-b473-cfcbf79e8a88.png">

Text
**Changing the publication type might result into data loss.**

### Component

Horizontal form
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-horizontal

Info text
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-01-form-standard](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-01-form-standard)

Helper text
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text)

## 2. Inform user upon change

Example
<img width="506" alt="Schermafbeelding 2022-08-18 om 09 11 13" src="https://user-images.githubusercontent.com/1572885/185332354-351b7223-9faf-4230-ba45-d0d610463a92.png">

Text
**Changing the publication type might result into data loss.**
The fields below are dependant on the publication type. Changing the publication type will replace some fields. Once a field is replaced, the data cannot be recovered.

Component:
[https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-05-modal-headerless](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-05-modal-headerless)

**Comment by mietcls** [comment]
@nicolasfranck @nics @netsensei is this a way we can go for feature parity without adding too much load? If yes, can it go to "launch"?

**Comment by nics** [comment]
> @nicolasfranck @nics @netsensei is this a way we can go for feature parity without adding too much load? If yes, can it go to "launch"?

yes

**Comment by nics** [comment]
resolved by 7a4b02e212069992de4815e98fe22fa0c05748e5 and 55b464d4e535f7536f232b32a428fb3bf3c8ca6d
