### ISSUE TITLE
remove reliance on positions in actions, use id's for nested objects

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#445]

**Comment by nicolasfranck** [comment]
https://metacpan.org/pod/Data::ULID

**Comment by nicolasfranck** [comment]
The use of an `id` is only problematic for a relation like `author`, where it has a special meaning.

cf. https://github.com/ugent-library/biblio-backend/issues/460

**Comment by nics** [comment]
fixed by #461
