### ISSUE TITLE
Pagination links do not work after importing from crossref or bibtex

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#458]
After a crossref or bibtex import (add multiple), a page is rendered
with all the imported publications. This is done on path `/publication/add-multiple/import`
as the file was posted to that path.

But the pagination links do not work:

```
/publication/add-multiple/import?page=1
/publication/add-multiple/import?page2
```

Understandingly, as there is no route for `GET /add-multiple/import`,
but there is a route `GET /publication/add-multiple/{batch_id}/description`

So redirect to `/publication/add-multiple/{batch_id}/description` after a successfull
import?

**Comment by nics** [comment]
yes!
