### ISSUE TITLE
Show UGent affiliation in overview

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#465]
# Context

Show the UGent affiliation in the affiliation overview columns, so researchers, reviewers and administrative support can easily see which one is faulty or missing.

## Success criteria

I can see the UGent affiliation in the record without having to edit the author or editor.

# Solution

Add affiliation to authors table
![Authors affiliation](https://user-images.githubusercontent.com/1572885/175901454-3b1c852a-5266-4af3-862a-b5fcb89f8d52.png)

## Not in scope

Step 2:
Add affiliation information to affiliation in authors table
![Authors affiliation 2](https://user-images.githubusercontent.com/1572885/175901448-da2543c3-f1db-4e20-8ca0-8a5974116c63.png)

Step 3:
Automated suggestions (can be refined later)

Step 4:
Thinking of dropdown patterns (see original ticket #322 ).

**Comment by mietcls** [comment]
Sidenote: we can probably remove the department section. We do need to check whether we can add the departments automatically and correct them as well if needed.

**Comment by mietcls** [comment]
@sdebodt I've noticed sometimes there's an extra department displayed that cannot be automatically derived from a researcher, such as connections to knowledge institutions like imec:

![Image](https://user-images.githubusercontent.com/1572885/186194743-a49dc433-7e61-4518-87c6-5a687f694c5f.png)
![Image](https://user-images.githubusercontent.com/1572885/186194742-11d2357b-f381-468f-917f-72065188700c.png)

This means the department section should probably stay, to catch these collaborations – however it should be moved to the "authors & editors" tab.

Currently the department section is also not automatically derived from the author's departments (or at least not in my tests), but this is a feature we can consider after we've reached feature parity.

**Comment by sdebodt** [comment]
@mietcls Currently, only UGent departments are linked to UGent employees. "Departments" such as VIB and IMEC are actually not departments but complete research/knowledge institutes (also affiliated to other university). In the current setup, these should indeed be added manually as they are not linked to UGent employees in the HR system. 

OK to look into automation of adding departments based on employee records in a later stage. Note that we already automatically add the department of the logged in person. This functionality will be lost when we move the department info to the Authors and Editors tab and do not automated assignment of departments.

**Comment by nics** [comment]
> Keep this stored in the record itself (and so keep a historical record), or add this as an enrichment for viewing only? In the old interface, it looks like an enrichment. @nics ?

the id's of all affiliations are already stored in the record ... or do you mean something else?

**Comment by mietcls** [comment]
Note:
- Should we show the timestamp of the different departments?

**Comment by sdebodt** [comment]
The department should indeed by the department that the author/creator belonged to at the time of writing/creating, as the publication/dataset is research output of that department.

No need to actually keep a time stamp, I would say. If needed, one can look up which department a UGent employee belonged to at a certain time in the HR SAP database (where GISMO also takes it's data from).
