### ISSUE TITLE
Using hyphens while searching for authors or editors does not work

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#473]
# Description of the Bug

Whenever trying to add the author "Tove Holm-Larsen" as an author, and using "Holm-Larsen" as a last name the system does not find the author. When leaving out the dash, e.g. using "Holm Larsen" it does seem to work.

## To Reproduce
1. Go to eliot1 environment
2. Add or edit a publication
3. Go to the Authors & Editors tab, and click on "Add Author"
4. Add Last name "Holm-Larsen"
5. Click "UGent author" radio button
6. See "This author is not a UGent employee or student."

## Expected behavior

Expected to find Tove Holm-Larsen as an UGent author.

### With dash

Search
![Image](https://user-images.githubusercontent.com/1572885/187161881-e9c2006b-b335-44de-81b5-77f9c7d041b0.png)

Result
![Image](https://user-images.githubusercontent.com/1572885/187161752-c24dfad0-97ee-4a7a-8101-5ca10d649b9f.png)

### Without dash

Search
![Image](https://user-images.githubusercontent.com/1572885/187161979-9f2e4861-4611-47ae-8a35-eb4199b7996b.png)

Result
![Image](https://user-images.githubusercontent.com/1572885/187161716-67592ad7-aac8-4309-b6ab-94d97094941c.png)

# Desktop (please complete the following information):
 - OS: macOS Monterey
 - Browser: Safari 
 - Version 15.5

## Additional context
Also reported by review team (Windows)

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/44

**Comment by nics** [comment]
@mietcls seems to work correctly after merging the pr

**Comment by mietcls** [comment]
@nics Huzzah it does, you can enjoy the closing 🍡 ✅
