### ISSUE TITLE
I can add or edit a WoS type when adding a publication manually or importing it via WoS, via DOI or via BibTeX

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#475]
# Story

As a librarian, I have to be able to add a WoS type – even when the record was added manually or imported (via WoS, DOI or BibTeX).

## Success criteria

As a librarian ...
- [ ] I can edit the WoS type of a record that has been imported via WOS
- [ ] I can edit the WoS type of a record that has been created manually
- [ ] I can edit the WoS type of a record that has been imported via DOI
- [ ] I can edit the WoS type of a record that has been imported via BibTeX

# Context

## Current implementation
Not possible for the above cases.

### WoS import
![Image](https://user-images.githubusercontent.com/1572885/187235887-8c1bf4cd-d92a-41a5-b116-56c5f780074d.png)

### Manual creation
![Image](https://user-images.githubusercontent.com/1572885/187235386-a914ed9f-3fa8-4926-a03a-e795805ea544.png)

### DOI import
![Image](https://user-images.githubusercontent.com/1572885/187235480-6ffd4afb-51f4-434a-a70c-610e14b82c60.png)

### BibTeX import
![Image](https://user-images.githubusercontent.com/1572885/187236181-52c78db9-b139-47d2-a0b5-d4392727f1d6.png)

## Old back-end
![Image](https://user-images.githubusercontent.com/1572885/187197684-75b21bcb-fcbb-4674-a7b9-d273d8e45ca1.png)

**Comment by nics** [comment]
@mietcls this should already be fixed
