### ISSUE TITLE
Missing fields for book: Series title, Volume, Edition

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#476]
# Description issue

In the current interface, some fields are missing for publication type "book".

## Expected behaviour

See these fields in the overview and in the edit screen:

- [ ] Series title
- [ ] Volume
- [ ] Edition

Overview details screen:
![Image](https://user-images.githubusercontent.com/1572885/187211437-4494743a-9a89-4b97-ac70-67749d52b8da.png)

Edit details screen:
![Image](https://user-images.githubusercontent.com/1572885/187211519-dbe232fa-54ca-4f42-b63c-11d8eb1be97b.png)

### Old interface
![Image](https://user-images.githubusercontent.com/1572885/187210927-04250e5d-46b7-4b14-868a-751705dfdf64.png)

### Current new interface

![Image](https://user-images.githubusercontent.com/1572885/187211224-68900547-4e7b-429b-8fb2-12654bfe718d.png)
![Image](https://user-images.githubusercontent.com/1572885/187211225-80d7b363-0111-4594-b163-5470ba8de64a.png)

**Comment by nicolasfranck** [comment]
@mietcls duplicate issue? Seems to be solved already

**Comment by mietcls** [comment]
@nicolasfranck we have four (book, book chapter, editor issue and editor book):
- This one (book)
- https://github.com/ugent-library/biblio-backend/issues/478
- https://github.com/ugent-library/biblio-backend/issues/479
- https://github.com/ugent-library/biblio-backend/issues/477

But if it's already fixed be my guest to close it!
