### ISSUE TITLE
Missing fields for editor issue: Volume, Issue

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#479]
# Description issue

In the current interface, some fields are missing for publication type "editor – issue".

## Expected behaviour

See these fields in the overview and in the edit screen:

- [ ] Volume
- [ ] Issue

Overview details screen:
![187213977-3fcdd654-d7ed-47c6-b7e9-d4cf443bf9ef](https://user-images.githubusercontent.com/1572885/187689915-e4d810ea-a324-4355-9aa0-4bb98f713e51.png)

Edit details screen:
![187213937-48f19a05-1792-4488-940b-0cd9bb1db508](https://user-images.githubusercontent.com/1572885/187689885-a21b28de-7a40-435a-8002-61c70d4dc567.png)

### Old interface
![Image](https://user-images.githubusercontent.com/1572885/187213710-4160b040-f6f5-42c2-84e3-2749098883a3.png)

### Current new interface

![Image](https://user-images.githubusercontent.com/1572885/187211224-68900547-4e7b-429b-8fb2-12654bfe718d.png)
![Image](https://user-images.githubusercontent.com/1572885/187211225-80d7b363-0111-4594-b163-5470ba8de64a.png)

**Comment by nicolasfranck** [comment]
@mietcls so fields "volume" and "edition" are missing from type "book"? The title suggest "issue editor"..

**Comment by mietcls** [comment]
@nicolasfranck Thanks for catching that one :-)

**Comment by mietcls** [comment]
Went a bit cross-eyed _issue_ instead of editor.
