### ISSUE TITLE
filter voor department

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#48]
(met verwoording van de codes, ook in detailview zou de verwoording bij de code moeten staan)

**Comment by nicolasfranck** [comment]
filter bestaat ook in librecat, maar wordt daar "Faculty" genoemd (maar wel gefilterd als `department=<department>`.
In biblio-backend best `Organisation` gebruiken

**Comment by nics** [comment]
organization with a z

**Comment by nics** [comment]
resolved by #67
