### ISSUE TITLE
Clarify "license" and "other license" fields

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#481]
# Story

Both "license" and "other license" are now required fields.
However, one of both is fine. This first dropdown shows a preferred list, but the free text field allows for other (older) licenses). 

This is not clear from the interface.

![schermafbeelding_2022-08-25_om_10 00 08](https://user-images.githubusercontent.com/1572885/186610403-220337ec-6fc8-4c74-9601-6d442c24aa79.png)

Related: #561 

## Success criteria
_(copy can still be adapted)_

- [ ] I can select the following options:
  - [x] cc license (as listed on screenshot above – no edits as this has to resolve as PDX)
  - [x] I can indicate there is a license, it is just not an option in this list
  "The license is not listed here"
- [ ] Whenever I select "The license is not listed here" – the "Other license" field is shown, where I can fill out the license.
- [ ] #697
"A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights"
- [ ] `TBD if possible` Whenever a license is imported that is not part of the default options:
  - [ ] We select "The license is not listed here" in the dropdown field
  - [ ] We show the "Other license" field
  - [ ] We fill out the license in the "Other license" field
- [ ] Remove "I don't know option"
- [ ] Remove "In copyright (no license)" – it apparently does not exist for datasets

Front-office (current suggestion for publications as well, as listed in https://github.com/ugent-library/biblio-backend/issues/659):
![Schermafbeelding 2022-10-10 om 17 02 38](https://user-images.githubusercontent.com/1572885/194896737-f3ccc89d-33d4-45dc-89cd-f5f541511105.png)

# Context

For publications, it works a bit different:
- Current implementation https://github.com/ugent-library/biblio-backend/issues/650
- https://github.com/ugent-library/biblio-backend/issues/559 (full-blown flow for later, which will be reworked)

**Comment by sdebodt** [comment]
In the screenshot above, I notice that "No license (in copyright)" has moved to the drop-down menu, while it was a check box available for all access levels in the past. The dropdown should only appear when open access is chosen to avoid that open licenses are added to content that is not open access.

**Comment by mietcls** [comment]
@sdebodt to clarify;

Which dropdown should appear when open access is chosen?
When can we not see which dropdown?
When can we use the checkbox for "No license (in copyright)", and what effect does it have?

**Comment by mietcls** [comment]
@sdebodt Thank you for clarifying, I will adjust accordingly

**Comment by mietcls** [comment]
After discussion and seeing the current implementation, we will adjust later:

Publications
- This is a short list for now, that will be extended later – preferably via API
- We will find a way to make this user friendly for researchers and administrative support – perhaps with a decision tree to help (such as the concept of http://chooser-beta.creativecommons.org)

Foreseen issue current implementation + how to fix it later:
- The current implementation might have maintenance issues if custom possibilities are part of the list (treated as closed source by FRIS) – and if we cannot ingest the SPDX list of FRIS automatically (via API). If this is the case, we will have to think of a way to implement this without having to update manually. We will:
  - Not make our internal maintenance problem a users’s problem by adding an extra step to complete (not a separate button, check or dropdown). We cannot justify having 10.000 people do an extra click for each publication.
  - Find a way to populate the list automatically via the FRIS API (SPDX licenses) + add the "custom" non-SPDX licenses so we solve our maintenance problem later.

For now:
- Double check if the API is already part of the implementation
- If not, we keep the current implementation to avoid triple work – and fix it when the SPDX license update needs to happen (API implementation).

Note: non-SPDX licenses are treated as closed by FRIS.

**Comment by mietcls** [comment]
@sdebodt thanks for the elaboration.

"We said to only revisit this when we also address the front-end functionality to select a license." – I'm not 100% sure if we mean the same thing. But if this means not for the launch in November, we are aligned ;-)

**Comment by sdebodt** [comment]
We will first evaluate in how far users are able to select the appropriate license based on the limited CC license list and how often they use the "Other license" field. So the extension to the SPDX license list is not expected to be needed in the near future. My guess would be that we address this in the second half of 2023 at the earliest.

**Comment by mietcls** [comment]
Thanks! Adapted.

Referencing #559 where I'll be writing down and sketching the larger issue we are describing here.

**Comment by mietcls** [comment]
Suggested solution B: make one of both options required
![Image](https://user-images.githubusercontent.com/1572885/190969334-0fd80511-1761-45ba-b074-f01f02fa6100.png)

## Example code

Note: I removed the info, it should however remain.

```
<div class="form-group row">
  <label class="col-3 col-form-label" for="license">
    License&nbsp;<abbr class="required" title="Required">*</abbr>
  </label>
  <div class="col-3">
    <label class="form-label" for="license">Choose a license</label>
    <select class="custom-select form-control" name="license">
      <option></option>
      <option value="CC0-1.0">CC0 (1.0)</option>
      <option value="CC-BY-4.0">CC BY (4.0)</option>
      <option value="CC-BY-SA-4.0">CC BY-SA (4.0)</option>
      <option value="CC-BY-NC-4.0">CC BY-NC (4.0)</option>
      <option value="CC-BY-ND-4.0">CC BY-ND (4.0)</option>
      <option value="CC-BY-NC-SA-4.0">CC BY-NC-SA (4.0)</option>
      <option value="CC-BY-NC-ND-4.0">CC BY-NC-ND (4.0)</option>
      <option value="InC">No license (in copyright)</option>
    </select>
  </div>
</div>
<div class="form-group row justify-content-end">
  <div class="col-9">
      <label class="form-label" for="other_license">Or enter an other license</label>
      <input class="form-control" name="other_license" type="text" value="test">
      <small class="form-text text-muted">e.g. https://creativecommons.org/licenses/publicdomain/</small>
  </div>
</div>
```

Conditional logic might be the better solution if this requires an equal amount of work.

**Comment by mietcls** [comment]
@netsensei apparently no copyright is not used in datasets context – as it is a very vague legal field. We can remove this one too.

**Comment by netsensei** [comment]
Do you mean "In copyright (no license" option?

**Comment by netsensei** [comment]
Done:

* Whenever I select "The license is not listed here" – the "Other license" field is shown, where I can fill out the license
* Remove "I don't know option"
* Remove "In copyright (no license)" – it apparently does not exist for datasets
* Sanity check of CC lists vs. publications
* Fixed issue: if an imported CC license is not in our list, it will be written to the "Other license" field. The license field gets the "License not in list" value.

**Comment by netsensei** [comment]
@mietcls closing this issue for now. Might need validation though thru follow up tickets
