### ISSUE TITLE
I can see my department added to "departments" when I create a record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#482]
# Story

I can see my department added to "departments" when I create a record.

# Context

As reported; this is very convenient for librarians. Even if when they add a record their own department is automatically added – it outweighs having to add it for researchers and secretary staff if they forget it. If we would leave it out we would need to add validation for departments as well, which is tedious for researchers and staff alike.

## Success criteria

- [x] When I create a record, my **current** department is automatically added to the record.
- [x] I can always remove my department if it is not relevant afterwards

## New interface
No automatic retrieval of department upon creation of record
![Image](https://user-images.githubusercontent.com/1572885/187276372-ab9f2e58-8ebd-421a-a0ce-ae9be4742b5c.png)

## Old interface
Automatic retrieval of department upon creation of record
![Image](https://user-images.githubusercontent.com/1572885/187276466-642e700c-141e-45c7-993f-15545aaceeb0.png)

**Comment by nicolasfranck** [comment]
So where should the department be fetched from?

* from the logged in user?
* from the contributor list (so a unique list)?

I guess the second one, as departments are about the publication/dataset itself (and not the one doing the task)? In that case, the departments can only be filled during creation, when that creation also imports contributors. Afterwards, indeed it should be left alone..

**Comment by mietcls** [comment]
@nicolasfranck what do you mean by contributor list?

Right now we're going for feature parity, and that means option one. If it takes the same amount of time to implement I can inquire whether option two would be desired for the reviewers and curators.

**Comment by nicolasfranck** [comment]
@mietcls none of them is difficult. So option one, i.e. the departments from the logged in user? So that assumes that the researcher is entering his/her own publications, right?

**Comment by mietcls** [comment]
> Discussed with the reviewers; 90% of the cases this is convenient as secretarial staff are usually from the same department, and it is only and issue for reviewers themselves. They find this far more convenient that this goes automatically.

Yes, as described in this comment, it covered 90% of the cases. They'd prefer to get it automatically instead of no department.

However, I can't assess the value of the contributor list yet – can you describe to me how the contributor list would work?

**Comment by netsensei** [comment]
Implemented this.

When creating one / multiple new dataset(s) / publication(s), the "department" field will be automatically populated with the department assigned to the logged-in user who is creating the record.

* If the logged-in user is assigned to multiple departments, the first department in their list will be picked.
* If a librarian impersonates another user, the department from that user is used instead of the department of the librarian.
* If a user isn't a assigned to any departments, the field will be left blank. 

Librarians and researchers alike can see this and are able to remove the suggested department from the record(s).

**Comment by netsensei** [comment]
@mietcls Can you test this and close this if this works for you?

**Comment by mietcls** [comment]
Works!
