### ISSUE TITLE
Empty doi leads to (external) link to "https://doi.org" in detail view

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#488]
# Bug story

e.g. record 1000229. In the detailed view, you see a link, without text (as there is no doi),
which leads to https://doi.org/ as there nothing to add after that base url.

## Steps to reproduce
- Go to publication or dataset
- Scroll to details
- See icon link and click

What it looks like
![Image](https://user-images.githubusercontent.com/1572885/187673290-bd1ef62f-cfd4-410f-bcff-e221a570c831.png)

# Expected behaviour

Do not show the url icon, only show it is empty:
![Image](https://user-images.githubusercontent.com/1572885/187673199-e7c47220-98ab-4af4-9326-a5729e54f7d7.png)

**Comment by mietcls** [comment]
Thanks, updated with more information @nicolasfranck
