### ISSUE TITLE
Put authors and editors in one line in list overview

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#499]
# UX crash

Authors and editors should be displayed inline instead of stacked, to improve overview and spacing.

## Steps to reproduce
- Go to publications or datasets overview

What it looks like
![Image](https://user-images.githubusercontent.com/1572885/187656156-d4608bfa-5fa2-4d9d-92e2-fffee263cf45.png)
![Image](https://user-images.githubusercontent.com/1572885/187656157-05c9c043-8887-4c64-93f4-59119349db38.png)
![Image](https://user-images.githubusercontent.com/1572885/187656158-01ced558-4509-442b-960f-622435797303.png)

HTML
![Image](https://user-images.githubusercontent.com/1572885/187656515-8336017c-8683-452f-8286-e9eb1ba1178c.png)

## Expected behaviour

Use this component:
Author list https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-author-list.html
or 
Meta list horizontal https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-meta-list.html#component-02-c-meta-list-horizontal

On one line
![Image](https://user-images.githubusercontent.com/1572885/187656376-bb7748bc-4f7a-425d-bc56-f38af4f8d5e4.png)
![Image](https://user-images.githubusercontent.com/1572885/187656377-02c09cec-5319-44af-b3fa-7d216619b7c7.png)

HTML
![Image](https://user-images.githubusercontent.com/1572885/187656214-63389c52-b214-4237-9b0c-604c5bdd1616.png)

# Context
New css update has broken a couple of UI elements https://github.com/ugent-library/biblio-backend/issues/486

**Comment by netsensei** [comment]
@mietcls This one seems fixed for both datasets and publications. I'm closing this.
