### ISSUE TITLE
Create separate tab "Messages" (AKA "Biblio Activity")

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#508]
# Story

As a librarian, researcher or administrative support, I can see a separate "Messages" tab, to see extra information of a record for librarians, researchers and administrative supporters alike.

Related to epics
- https://github.com/ugent-library/biblio-backend/issues/511
- https://github.com/ugent-library/biblio-backend/issues/514
- Epic about messaging: https://github.com/ugent-library/biblio-backend/issues/512

## Success criteria

- [x] The tab is only visible to everyone logged in
- [x] The tab is at the end of the row
- [x] The functionality inside might be visible or invisible to researchers, defined per functionality.

# Context

This tab will contain librarian tags (#511), internal librarian notes ( ), messaging between researchers and librarians (already available as a simple text field, but will be moved and extended later) and history of a record (later stage, also visible to researchers.

Functionality visible for librarians
- Tags (librarians only)
- Internal field (librarians only)
- Message about record (communication text field visible to everyone)
<img width="1317" alt="187878910-64b53efd-1370-44a3-9dd2-2a60f60bf213" src="https://user-images.githubusercontent.com/1572885/188409370-6364a396-a3e6-459d-96d1-4715d4b13ab4.png">

> Note: "Biblio Activity" will be called "Messages"

Functionality visible for researchers and administrative support:
- Message about record (communication text field visible to everyone)
<img width="1317" alt="187878910-64b53efd-1370-44a3-9dd2-2a60f60bf213 kopie" src="https://user-images.githubusercontent.com/1572885/188409191-dc982a23-4dbe-4b6b-a812-3bb5080c08c9.png">

> Note: "Biblio Activity" will be called "Messages"

Later stage for librarians
https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/biblio-activity.html
![Image](https://user-images.githubusercontent.com/1572885/187878806-340051fa-aae1-4da0-ba9a-d93ee06b7785.png)

> Note: "Biblio Activity" will be called "Messages & History"

Later stage for researchers
https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/researcher/publication-detail/biblio-review.html
<img width="1306" alt="187878806-340051fa-aae1-4da0-ba9a-d93ee06b7785" src="https://user-images.githubusercontent.com/1572885/188409884-e5c4c951-d558-4736-8951-e5046980b311.png">

> Note: "Biblio Activity" will be called "Messages & History"

# Out of scope
- Adding the functionalities inside
- Visible to a researcher
- Activity of a record visible to everyone

**Comment by nics** [comment]
@mietcls is this only for publications, or also for datasets?

**Comment by mietcls** [comment]
@nics I would also create it for datasets if possible and low impact, what is the impact here?

**Comment by nics** [comment]
low impact, mostly copypaste

**Comment by mietcls** [comment]
Then it would be nice so they can also use the review tags to start building up their workflow in the future. Would you prefer two issues?

**Comment by nics** [comment]
no need

**Comment by nics** [comment]
@mietcls added basic implementation for publications and datasets

**Comment by mietcls** [comment]
@nics Works well for both, only the "Message" that is displayed is the content of the "Librarian note" – I think there's a mapping going wrong here.

I will add help text for researchers and reviewers to make it complete.
