### ISSUE TITLE
As a librarian, I can add "librarian" tags to a record to communicate with colleagues

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#510]
# Story

As a librarian, I can add **_librarian_ tags**, visible only to other librarians so I can communicate with them efficiently about those records via filters.

Full story on epic https://github.com/ugent-library/biblio-backend/issues/511
Extended, out of scope implementation: https://github.com/ugent-library/biblio-backend/issues/536

## Success criteria

- [x] As a librarian I can add librarian tags to a specific record
- [x] I can scroll through the different tags (contact @mietcls when coming to this part if css input needed)
- [x] As a librarian I can see the librarian tags added to a specific record added by my colleagues
- [x] As a librarian I can remove librarian tags from a specific record, whether they are added by myself or a colleague 
- [x] I can filter immediately on the created librarian tags in the publication and dataset overview

# Implementation

### Overview
Available in the "Biblio activity" tab
<img width="1318" alt="Schermafbeelding 2022-09-01 om 11 15 15" src="https://user-images.githubusercontent.com/1572885/187885858-185fd138-5bc6-4a16-b336-56506543677b.png">

Adding and removing tags
- Add new tag with "+" button
- Remove tag with trash button
- Scrollable
<img width="607" alt="Schermafbeelding 2022-09-05 om 09 47 40" src="https://user-images.githubusercontent.com/1572885/188396882-29537cf2-4d42-4c6a-9b92-beeb4bc6996c.png">

#### Buttons
Buttons: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-btn-types.html

Trash button example:

```
<button class="btn btn-link-muted btn-icon-only ml-3 form-value-delete" type="button">
  <i class="if if-delete"></I>
  <div class="sr-only">Delete</div>
</button>
```

#### Inline example
```
<div class="mb-3 form-value">
  <div class="d-flex">
    <input class="form-control" name="alternative_title[0]" data-tmpl-name="alternative_title[{i}]" type="text">
    <button class="btn btn-outline-primary btn-icon-only ml-3 form-value-add" type="button">
      <i class="if if-add"></i>
      <div class="sr-only">Add</div>
    </button>
  </div>
</div>
```

# Context

## Future implementation (out of scope)
![Image](https://user-images.githubusercontent.com/1572885/187865310-d7cc0fa3-4a2d-47bb-a1fd-f4360016ac46.png)

## Old back-end

Multiple tags:
![Image](https://user-images.githubusercontent.com/1572885/187864616-f972ee57-99f8-414e-b5d1-47c2c1666f39.png)

New tag: click "+"
![Image](https://user-images.githubusercontent.com/1572885/187864662-aea06e5d-8b38-43b0-8a5f-ceb9e95630ec.png)

**Comment by mietcls** [comment]
Options
- Find a good keyword manager in vanilla js
- or use "keyword" implementation for now – improve later.

**Comment by mietcls** [comment]
Testing already worked smoothly, I can see tags and notes added from different librarians.

**Comment by nics** [comment]
@mietcls this can be closed?

**Comment by mietcls** [comment]
@nics let's close it I'll test later then
