### ISSUE TITLE
List all accessibility issues

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#513]
# Story

List all accessibility issues

# Found issues

## 1. Fix HTML for helper text to comply to accessibility

To comply to accessibility needs add "p" tag, nested with a "small" tag, instead of "div" tag.

### Context

Current code:
<img width="906" alt="Schermafbeelding 2022-09-01 om 10 31 41" src="https://user-images.githubusercontent.com/1572885/187869907-e8c83a4a-d949-4503-ad2e-49c71dcb455f.png">

Expected code:
```
<div class="form-group is-invalid">
    <label class="col-form-label" for="input-error-01">Label<span class="badge badge-secondary badge-sm">Required</span>
    </label>
    <input class="form-control is-invalid" type="text" id="input-error-01" />
    <p><small class="invalid-feedback">Inline validation error.</small></p>
</div>
<div class="form-group">
    <label class="col-form-label" for="input-error-02">Label<span class="badge badge-secondary badge-sm">Required</span>
    </label>
    <input class="form-control is-invalid" type="text" id="input-error-02" />
    <p><small class="invalid-feedback">Inline validation error.</small></p>
</div>
```

**Comment by netsensei** [comment]
Just noticed: the `small.invalid-feedback` has a `display:none` so the validation error isn't displayed.

**Comment by mietcls** [comment]
@netsensei Ha I think this assumes logic; it's best to remove it then from the css?

**Comment by mietcls** [comment]
Oh, this one was still under construction by me, it was a placeholder for all the accessibility issues, but superb this one is already fixed :D
