### ISSUE TITLE
As a librarian, I can add an "internal librarian message" to communicate with my colleagues about a record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#515]
# Story

As a librarian, I can add an **_internal librarian_ message**, visible only to other librarians so I can communicate with them about those records.

View full story at https://github.com/ugent-library/biblio-backend/issues/514

## Success criteria
- [x] As a librarian I can see the messages my colleagues and myself typed.
- [x] As a librarian I can add and remove information from this message field.
- [x] Researchers can not see this message

# Implementation

View and edit librarian message:
![Image](https://user-images.githubusercontent.com/1572885/187883489-1d67e10e-f7bf-47e5-b037-06a777d176f3.png)

We can use the card component with a text area (preference):
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-cards.html#component-02-b-card-with-header
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-inputs.html#component-02-textarea

Or a modal interaction with the card "edit" (existing interaction):
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-cards.html#component-03-b-card-with-toolbar
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-03-modal-large
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-inputs.html#component-02-textarea

# Context

## Old back-end
![Image](https://user-images.githubusercontent.com/1572885/187883443-ae9f7ea7-079c-47cf-8814-6e0caf16f048.png)

## New design
![Image](https://user-images.githubusercontent.com/1572885/187882329-573b0ddb-a22f-43da-a066-2b0a51684b93.png)

**Comment by nics** [comment]
@mietcls i think this can also be closed
