### ISSUE TITLE
Move "Librarian record message" to researchers to "Messages" (AKA "Biblio activity") tab

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#516]
# Story

As a librarian, I can add a **_librarian_ message** to communicate with researchers (and other librarians). Currently it's located in the record details page, but it should go to the activity tab.

Full story on epic https://github.com/ugent-library/biblio-backend/issues/512

## Success criteria

- [x] As a librarian I can add a librarian message to a specific record for a researcher
- [x] As a librarian I can see the messages added to a specific record added by my colleagues
- [x] As a librarian I can remove messages from a specific record, whether they are added by myself or a colleague
- [x] As a researcher I can see the message in the "Biblio activity" tab

Visibility
- The visibility of this note by researchers is defined here https://github.com/ugent-library/biblio-backend/issues/512

# Implementation

### Overview
Available in the "Biblio activity" tab: Librarian record message (on the right)
![Image](https://user-images.githubusercontent.com/1572885/187891537-6b9b7749-b513-4a44-b827-a53c8af49e68.png)

### Adding and removing a message
- I can add and remove messages by typing

### Overview (with librarian message)

```
<div class="row">
  <div class="col-lg-6">
    <div class="card mb-6">
      <div class="card-header">
        <div class="bc-toolbar">
          <div class="bc-toolbar-left">
            <h3 class="card-title">Librarian tags</h3>
          </div>
          <div class="bc-toolbar-right">
            <button class="btn btn-outline-primary" type="button" data-toggle="modal" data-target="#editTags">
              <i class="if if-edit"></I>
              <div class="btn-text">Edit</div>
            </button>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="badge-list">
          <a class="badge badge-secondary" href="/biblio/reviewer/publications/overview.html">funding to do: belgium</a>
          <a class="badge badge-secondary" href="/biblio/reviewer/publications/overview.html">group author publication</a>
          <a class="badge badge-secondary" href="/biblio/reviewer/publications/overview.html">funding to do: cost</a>
          <a class="badge badge-secondary" href="/biblio/reviewer/publications/overview.html">cc-by-2.0</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card mb-6">
      <div class="card-header">
        <div class="bc-toolbar">
          <div class="bc-toolbar-left">
            <h3 class="card-title">Librarian note</h3>
          </div>
        </div>
      </div>
      <div class="card-body">
        <textarea class="form-control" placeholder="" rows="4"></textarea><p><small class="form-text text-muted">Add internal notes here.</small></p>
      </div>
    </div>
  </div>
</div>

```

# Context

## Old back-end

Typing
![Image](https://user-images.githubusercontent.com/1572885/187891127-ac9d5e48-e1f5-490d-acdc-66803b568ab7.png)

Viewing
![Image](https://user-images.githubusercontent.com/1572885/187891166-e72d8ce0-e643-43a7-ba5a-4bc4fe81aeb9.png)

**Comment by nics** [comment]
@mietcls can this be closed?
it's not super efficient now, with edit and save buttons, but it works

**Comment by mietcls** [comment]
@nics I just tested it, the above checks are correct but I noticed researchers can't edit the message (forgot to add that check).

Result when I click edit:
![Schermafbeelding 2022-09-06 om 16 31 04](https://user-images.githubusercontent.com/1572885/188662049-69d6e323-5976-49c2-b901-3ce0a2a5835e.png)

Do I create a new issue so you can close this one?

**Comment by nics** [comment]
@mietcls there was an edit button even if you didn't have rights to edit the record, should be ok now

**Comment by mietcls** [comment]
@nics I can't see the edit button anymore, but I'll close this issue because the gist works and create a new one for this specific part – as it was not one of the success criteria here: https://github.com/ugent-library/biblio-backend/issues/573
