### ISSUE TITLE
As a librarian, I have a dashboard available that shows me new, unreviewed records without classification.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#517]
# Story

As a librarian, I have a dashboard available that shows me new, unreviewed records without classification.

## Success criteria
- [ ] [after sidebar switch is done] I can navigate towards a separate menu item to view records without classification
- [x]  I can view records to be handled per faculty
- [x] I can view records to be handled per type of record
- [ ] I can **apply quick filters**: click on number of records to be handled, and go to the records overview (datasets or publication), immediately with the correct filters applied
- [ ] Add SOCs knowledge institutions such as imec, VIB, UZ and GUK

### Out of scope
- I can view records to be handled that are not assigned to a faculty just yet, or only affiliated to "University of Ghent"
- Filter records to be handled per publication year (was broken before too)
- View the total of accepted dossiers per record type (dataset, publication), per department, per document type (was not correct in previous version either)
- Viewing records to be picked up later again
- Types of datasets
- Totals
- I can see when the latest numbers came in to upgrade performance perception

# Implementation
Prototype: https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/dashboard.html

## Feature parity version
![Image](https://user-images.githubusercontent.com/1572885/187908137-6f71459f-0e1e-4f53-b7ee-f5ec9647baed.png)

Code example:
```
<div class="card-header">
  <div class="bc-toolbar">
    <div class="bc-toolbar-left">
      <h3 class="card-title">Public with classification U</h3>
    </div>
    <div class="bc-toolbar-right">
      <p>Last updated: 2 September 2022 13:17</p>
    </div>
  </div>
</div>
```

## With librarians request knowledge institutions
![Image](https://user-images.githubusercontent.com/1572885/190425001-de7de170-cd6d-451f-8345-12d4d39801ef.png)

# Context

## Old back-end

Notes:
- Filtering per year did not work
- Total of accepted numbers was not correct
![Image](https://user-images.githubusercontent.com/1572885/187902421-cda98614-c0d2-4ef0-9870-2d181b63134f.png)

**Comment by mietcls** [comment]
"Laatste update" message would be good to upgrade performance perception

**Comment by mietcls** [comment]
Note: if there is no department or faculty selected, or only "Ghent University" -> add a column for these exceptions

**Comment by mietcls** [comment]
Note: Do not load as homepage because it is too slow

**Comment by mietcls** [comment]
Split off "no department" fancy feature and only solve if we cannot find a better solution

**Comment by mietcls** [comment]
@netsensei If we need to split off different data because the load is too much, we can do it like so:

![Image](https://user-images.githubusercontent.com/1572885/191250001-20e3af78-da59-4432-9b52-64a286a1242c.png)

**Code example**
Next to the primary sidebar

```
<div class="c-sub-sidebar c-sidebar--bordered">
  <div class="bc-navbar bc-navbar--xlarge bc-navbar--bordered-bottom">
      <div class="bc-toolbar">
          <div class="bc-toolbar-left">
              <div class="bc-toolbar-item">
                  <h4 class="bc-toolbar-title">Dashboard</h4>
              </div>
          </div>
      </div>
  </div>
  <div class="c-sub-sidebar__menu my-6">
      <nav>
          <ul class="c-sub-sidebar-menu">
              <li class="c-sub-sidebar__item c-sub-sidebar__item--active">
                  <a href="#">
                      <span class="c-sidebar__label">Publications</span>
                  </a>
              </li>
              <li class="c-sub-sidebar__item">
                  <a href="#">
                      <span class="c-sidebar__label">Datasets</span>
                  </a>
              </li>
          </ul>
      </nav>
  </div>
</div>
```

**Comment by netsensei** [comment]
Two dashboards have been added:

* With Classification = U
* With publication status = Accepted

With:

* Shows records per faculty
* Shows records per type
* Has an aggregate "all" column for each axis
* Each cell links to a quickfilter search list.
* Has SOC knowledge institutions.

**Comment by netsensei** [comment]
Done. @mietcls Needs to be tested.

**Comment by mietcls** [comment]
@netsensei thanks! The reviewers will love this.

Tested:
- The dashboard is visible to researchers, can we hide it for them?
- The reviewers did not mention HOART, HOGENT, HOWEST, IBBT – the screen overflows a bit now. There's a couple of things we can do, what do you think?
  - Can we split up the dashboard in: "Public with classification U – faculties" and "Public with classification U – SOC knowledge institutions"? This implies the "all" columns would be split up as well, for faculties and for SOCs.
  - Can we remove the sidebar on the left "Dashboard – Publications" for now, since the navigation is not being used?
  - We can add a horizontal scroll.
- The accepted records were out of scope as they did not function as expected in the previous dashboard, and were unused. I can ask if it proves to be useful now, but if not we might have to hide them as they did not explicitly need it.

**Comment by netsensei** [comment]
@mietcls I've added 4 different sections now:

* Publications - Faculties
  * Classification U
  * Classification Accepted
* Publications - SOCS
  * Classification U
  * Classification Accepted
* Datasets - Faculties
* Datasets - SOCS

Deployed & ready to be tested.

**Comment by mietcls** [comment]
Great! Works smoothly and does not overflow. This will make things more transparant from the get go 🥳

**Comment by netsensei** [comment]
Closing!
