### ISSUE TITLE
Web of science type has the wrong label on edit after WoS import

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#518]
# Description of bug

Web of science type can not be edited and has the wrong label after WoS import

## Reproduce

1. Go to [the eliot environment](https://eliot1.ugent.be/biblio-backend/curation/publication)
2. Add a publication
3. Import a WoS file
4. Go to details
5. Edit
6. Scroll down to WoS type

### WoS import
![Image](https://user-images.githubusercontent.com/1572885/187936848-9719c0ea-1039-4597-b148-336aa5ccb417.png)

![Image](https://user-images.githubusercontent.com/1572885/187275597-cfdc0f4f-0060-475a-94a8-29f42b8e86a7.png)

### DOI, manual or BibTeX import
![Image](https://user-images.githubusercontent.com/1572885/187938689-2de2b056-2cc2-455f-916c-36b3938e5ef9.png)

## Expected behavior

TO BE DISCUSSED:

For researchers:
![Image](https://user-images.githubusercontent.com/1572885/187964824-656c2a1b-3ac5-45da-99f5-78a672c84e32.png)

For librarians:
#475 

### Related
Filter on WoS type https://github.com/ugent-library/biblio-backend/issues/528

## Out of scope
- A dropdown list
- Or a free input field with suggestions
- Viewing the label as in the publication detail view (non-edit) after WoS import (probably not desired as you want to be able to correct the type)
![Image](https://user-images.githubusercontent.com/1572885/187937838-2e6228bc-ff57-41c2-803a-94885c915bc8.png)

# Technical info
 - OS: MacOS Monterey 12.5.1
 - Browser:
   - Safari version 15.6.1 (17613.3.9.1.16)
   - Firefox version 104.0 (64-bit)
   - Chrome version 104.0.5112.101

**Comment by mietcls** [comment]
Oh, I don't know how to test that, is there a way to view the librecat "as myself"?

**Comment by nics** [comment]
@mietcls no easy way to test that in the old interface without losing your admin rights

these are the fields that only admins can see:
        - reviewer_note
        - reviewer_tags
these are the fields that only admins can edit:
        - classification
        - wos_type
