### ISSUE TITLE
I can filter on UGent / non UGent records

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#523]
# Story

I can filter on the affiliation type of publication(UGent or non-UGent) so I can see which records need more or less dedicated curation or reviewing.

## Out of scope
Not for datasets yet as it is not in the UI yet.

# Context old Biblio
![Image](https://user-images.githubusercontent.com/1572885/187952997-a0a1a1cd-03ab-4284-8af7-5aa07d75c0a6.png)

## Success criteria
- [ ] Available for publications
View other success criteria on https://github.com/ugent-library/biblio-backend/issues/519

# Implementation and context
View design and components on https://github.com/ugent-library/biblio-backend/issues/519

**Comment by nicolasfranck** [comment]
@mietcls is that filter useful for datasets? It does not exist yet for datasets, so also not editable in the UI

**Comment by mietcls** [comment]
@nicolasfranck good point, if it's not there do not implement for datasets. Will it never be there, or is it just hidden for now?

**Comment by nicolasfranck** [comment]
@mietcls I do not know. @nics ?

**Comment by nics** [comment]
i haven't been asked to add this - since a related publication is required, and publications have the flag, it can be derived anyway

**Comment by nicolasfranck** [comment]
@nics not really. A dataset has its own "authors", not?

**Comment by mietcls** [comment]
I can inquire, for now only for publications seems okay.

**Comment by nics** [comment]
yes true, it could be a ugent publication that uses someone else’s dataset
thing is, the semantics of the ugent field are really vague
i interpret it as ’something to do with ugent research output’, but your point of view is equally valid
