### ISSUE TITLE
I can filter on the file type of a publication record (as a librarian?)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#525]
# Story

As a librarian, I can filter on the file type of a publication record to support me in following-up on records.

Filters:
- Full text
- Related Information
- Supplementary Material
- Table of Contents
- Accompanying Website
- Colophon/Title Page
- Data Fact Sheet
- Data Management Plan
- Peer Review Report
- Software
- Contract/Agreement

# Context old Biblio
![Image](https://user-images.githubusercontent.com/1572885/187954817-098ba56e-4a57-4bc2-84a8-b8a3efd63f5f.png)

## Success criteria
- [ ] Available for publications
View other success criteria on https://github.com/ugent-library/biblio-backend/issues/519

# Implementation and context
View design and components on https://github.com/ugent-library/biblio-backend/issues/519

**Comment by nics** [comment]
yes they are, better just file type

**Comment by mietcls** [comment]
Perfect
