### ISSUE TITLE
I can filter on the VABB type of a publication record (as a librarian?)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#526]
# Story

As a librarian, I can filter on VABB type of a publication record so I can follow up in time.

Filters:
- VABB-1
- VABB-2 
- VABB-3 
- VABB-4 
- VABB-5 

# Context old Biblio
![Image](https://user-images.githubusercontent.com/1572885/187955109-69fab843-fcb2-4c3b-b187-94a70f38336b.png)

## Success criteria
- [ ] Available for publications
View other success criteria on https://github.com/ugent-library/biblio-backend/issues/519

# Implementation and context
View design and components on https://github.com/ugent-library/biblio-backend/issues/519

**Comment by nics** [comment]
@nicolasfranck yes this should be part of the record

**Comment by nicolasfranck** [comment]
Reminder: when importing from biblio-backend, then update fix `add_vabb_data` in biblio itself, as attributes `vabb_id`, `vabb_type` and `vabb_year` are already present.

**Comment by nicolasfranck** [comment]
Reminder: @nics as this will be part of the record, and not updated by any user, when/where should this be updated?
