### ISSUE TITLE
I can filter on WoS type of a publication record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#528]
# Story

As a librarian, I can filter on the WoS type of a publication so I can see which records need follow-up.

Filters depend on the type that has been imported or added.

# Context old Biblio
![Image](https://user-images.githubusercontent.com/1572885/187959620-b99e7c24-4aaf-43f0-b039-38658b75633b.png)
![Image](https://user-images.githubusercontent.com/1572885/187959621-2597fa1c-2212-4d54-8b44-1816503d0dc9.png)

## Success criteria
- [ ] Available for publications
View other success criteria on https://github.com/ugent-library/biblio-backend/issues/519

# Related
Editing WoS type #518 

# Implementation and context
View design and components on https://github.com/ugent-library/biblio-backend/issues/519

**Comment by nicolasfranck** [comment]
See https://github.com/ugent-library/biblio-backend/pull/552 (closed)
