### ISSUE TITLE
I can filter on the publishing year of a record (publications and datasets)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#529]
# Story

I can filter on the publishing year of publication or dataset so I can see which records need follow-up in time.

Filters depend on the publication years that have been registered

# Context old Biblio
![Image](https://user-images.githubusercontent.com/1572885/187960371-5b8640f8-bb5b-4199-8100-eeea4c796860.png)
![Image](https://user-images.githubusercontent.com/1572885/187960372-e0c52e55-9152-4a0e-b660-40ef57b8dde0.png)

## Success criteria
- [x] Available for publications
- [x] Available for datasets
View other success criteria on https://github.com/ugent-library/biblio-backend/issues/519

# Implementation and context
View design and components on https://github.com/ugent-library/biblio-backend/issues/519

**Comment by nicolasfranck** [comment]
@mietcls a dataset does not have a year
