### ISSUE TITLE
dataset - edit details - how should fields change when selecting a different access level.

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#538]
# Story

When editing a dataset, one can select a different
access level and license. Depending on the chosen value,
one or more fields become "relevant" or not, and therefore
should be made either editable or disabled.

e.g. no use to render/edit a field like "embargo period"
when the access level is set to "open access", as it
produces confusion.

##  Success criteria

**Access level**
- [ ] Whenever I have not selected an access level; or have selected open, restricted or closed: no embargo fields are visible
- [ ] Whenever I selected embargoed access two fields appear:
  - [ ] Access level after embargo (with dropdown options "open access" and "restricted access")
  - [ ] Embargo end (calendar field)

**License**
- [ ] Whenever I have not selected a license, or I have selected one of the "CC" licenses: the "Other license" field is not visible
- [ ] Whenever I have selected "Other license": the "Other license" field is visible

## Flowchart

Static flowchart:
![Image](https://user-images.githubusercontent.com/1572885/189934539-c6c63b82-6783-4fac-a407-aa60839969d8.png)

Live updated flowcharts:
- Simple flow
- Explicit conditional values

# Design

### Access level
![Image](https://user-images.githubusercontent.com/1572885/189935924-616dc095-e79b-48c3-851d-add25239f37f.png)

### Licenses
NOTE: It needs to be "Other license" in the dropdown, not "Add another license".
![Image](https://user-images.githubusercontent.com/1572885/190970540-92a71c5a-83d2-4b35-8521-b3c927157784.png)

## Implementation
- Suggestion: you can use the class `d-none` to hide information.
- You can leave the "required" label for "required" options, but no need to validate.

**Comment by netsensei** [comment]
Consider both:

* Conditional rules -> What are the decision making pathways / matrix that leads a researcher to a valid outcome?
* UI / UX => chucking all fields in the form creates (a) confusion and (b) makes it hard to implement conditions / triggers. Shouldn't we re-think how this component communicates deciding on licensing e.g. wizard style? only show fields when relevant? in a separate modal?

**Comment by mietcls** [comment]
Will be rewriting https://github.com/ugent-library/biblio-backend/issues/440 for this one

**Comment by mietcls** [comment]
@netsensei I have created a design iteration on this one **for publications** https://github.com/ugent-library/biblio-backend/issues/559 – and added a flowchart as well (with different views).

To be iterated upon before we build, so we don't have to pivot in development.

Very much in contrast with the simple version in the **datasets view** that lacks opportunity to educate people to make an informed decision, and to reduce load when doing this for the first time. However this is much faster for experienced people.

The solution probably lies somewhere in the middle.
<img width="1089" alt="Schermafbeelding 2022-09-12 om 14 50 15" src="https://user-images.githubusercontent.com/1572885/189658187-f3c2a285-4f2c-466b-917e-3a318b94f29b.png">

I will make an alternative for datasets.

**Comment by mietcls** [comment]
@nicolasfranck is this one clear for you? I have added the information in the story on top 👆

**Comment by mietcls** [comment]
Double checked; we will leave in access level after embargo but limit the possibilities to "restricted" and "open" for datasets.

In any case, for datasets "No license (in copyright)" needs to go.

**Comment by mietcls** [comment]
Will be fixed in https://github.com/ugent-library/biblio-backend/issues/562 and https://github.com/ugent-library/biblio-backend/issues/481 for now
