### ISSUE TITLE
Make it possible to delete records from bulk-imported records

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#542]
# Story

I can delete records from my bulk-imported list of records upon import.

Related: extended bulk import options https://github.com/ugent-library/biblio-backend/issues/415 (out of scope)

# Screenshots

It is now only possible at the last stage of bulk importing record to remove unwanted records.

Step 1: import
Step 2: complete details
![Image](https://user-images.githubusercontent.com/1572885/187275241-490983dc-0a56-4d3f-8635-a789cb07f863.png)
Step 3: review
![Image](https://user-images.githubusercontent.com/1572885/187275239-9738012c-0222-48f9-a0e2-2dc8cae4ca82.png)
Last step:
![Image](https://user-images.githubusercontent.com/1572885/187275240-9c767e86-ec42-4957-badf-8d9d4dfd54e7.png)

## Success criteria
- [x] In step 2 "complete details" I can remove the unwanted records that I accidentally uploaded, before clicking the button "publish to Biblio"

## Context old Biblio
In the old Biblio, it is possible to remove accidentally bulk-imported records upon import [screenshot to add]

**Comment by mietcls** [comment]
Especially intense if you have 92 records one cannot delete
![Image](https://user-images.githubusercontent.com/1572885/188868188-7b899a63-b54d-4609-ae29-5ae91fc5bc51.png)

**Comment by netsensei** [comment]
@mietcls Done. Closing this.
