### ISSUE TITLE
Sorting: add "Added (oldest first)" option

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#543]
# Story

Add "Added (oldest first)" option. This pattern is widely used to make sure that we can treat records according to "first in first out" – which is most fair.

# Current implementation
![Image](https://user-images.githubusercontent.com/1572885/187963327-281e94ea-88b4-49ba-99bf-afd7a21d1285.png)
![Image](https://user-images.githubusercontent.com/1572885/187963328-ab022af0-5444-44e8-9db2-515a080a2bd6.png)

# Expected baviour
![Image](https://user-images.githubusercontent.com/1572885/194868575-a50d91f5-4af5-4eb5-baa4-44f23eae52d6.png)
![Image](https://user-images.githubusercontent.com/1572885/194868648-c3d5143e-357c-48d7-9496-8f4c1c5a4612.png)

## Implementation suggestion

Adapted the sequence as well to make sure the most logic option remains on top.

```
<select class="custom-select form-change-submit" name="sort">
  <option value="date-created-asc">Added (oldest first)</option>
  <option value="date-created-desc">Added (newest first)</option>
  <option value="date-updated-desc">Updated (newest first)</option>
  <option value="year-desc">Year (newest first)</option>
</select>
```

# Context

In the old biblio interface we had an extended set of sorting options. Apparently the sorting functionality was not widely used, and quite confusing according to some librarians. Not all of them are needed anymore, so the new set is adapted to that need. There was only one missing "first in first out".

## Old biblio
![Image](https://user-images.githubusercontent.com/1572885/187963185-afbecb32-379a-4aa8-a8bd-0c02d872e7c2.png)

**Comment by netsensei** [comment]
Done

* Added new sort "Added (oldest first)
* Renamed: Publication year (newest first)
