### ISSUE TITLE
Blank states: no results (search)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#544]
# Story

Whenever I enter a search result that shows no records, I get a message so I know what went wrong.

# Expected result

- [x] For datasets
- [x] For publications

## Example
![Schermafbeelding 2022-09-05 om 14 46 42](https://user-images.githubusercontent.com/1572885/188452738-c15ffd7e-85bf-49ff-91d9-b95e073a3274.png)

## Copy
Title: No records found
Text: Adjust your search to find what you are looking for.

## Component
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-blank-slate.html#component-02-c-blank-slate

## Example code
Inside the card body:

```
<div class="card-body p-0">
  <div class="c-blank-slate c-blank-slate-large c-blank-slate-muted">
    <div class="bc-avatar bc-avatar--medium">
      <i class="if if-info-circle"></I>
    </div>
    <h1>No records found.</h1>
    <p>Adjust your search to find what you are looking for.</p>
  </div>
</div>
```

**Comment by nicolasfranck** [comment]
@mietcls isn't this a bit the result of the collapsed facet/filters?

**Comment by mietcls** [comment]
@nicolasfranck just had a short conversation with @nics and @netsensei – I now understand better what the impact is of the intended implementation.
- I will adapt this story to cover the "no search results" case.
- It will not be the case for filters – we'll keep the way filters work for now and adapt according to feedback later (besides the fact that you can combine values within filters, that will change).
