### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#555]
# Story

As a librarian, I can export metadata of records to Excel.

## Success criteria
- [x] As a librarian, I can download metadata of publications as excel
- [x] As a librarian, I can download metadata of datasets as excel
- [x] As a librarian, I can open the metadata in programs such as excel, google sheets and numbers
- [x] The medata contains the same information as in the previous Biblio
- [ ] We rely technically on the visual feedback of the browser to communicate the download process and end

# Implementation

### Static
![Image](https://user-images.githubusercontent.com/1572885/188470343-845999fa-ddd3-40b4-9eca-125ac6a03fc5.png)

### Button with icon and text
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-btn-types.html#component-02-btn-icon-text

## Code examples

# Out of scope

- Providing feedback upon click
- Using the dropdown on the right to house this functionality in together with other functionalities.
![Image](https://user-images.githubusercontent.com/1572885/188470284-b5451c2d-bc0f-4936-b745-51dc6ca3f19f.png)
Related: https://github.com/ugent-library/biblio-backend/issues/550

**Comment by mietcls** [comment]
Note: Keep excel

**Comment by mietcls** [comment]
Note about exporting for researchers in the back, and not front: Anniek said researchers need to use the front, because we cannot filter out the drafts and withdrawns. Okay to leave this out for now.

**Comment by nicolasfranck** [comment]
@mietcls is it important to use the same sorting in the excel export? Elasticsearch has its maximum when doing deep paging, and the only way to circumvent is by filtering on an alphabetical value sequentially.

e.g. each hit has a field "sort". The last hit of the current page for example has value like "00000009". When requesting for the next page you simply request for publications where "sort" is bigger than "00000009". This only works of course by letting us choose the sorting.

Excel can do sorting too, so?

**Comment by mietcls** [comment]
@nicolasfranck When I spoke to Anniek, I understood this was not a big issue. However for the public version (front-office), this one should _not_ be touched.

To be double checked with @nics – some people reuse our excels.
