### ISSUE TITLE
Fix wording for role dropdown in sidebar from "user" to "researcher" and make it fit in prototype

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#556]
# Story

The role "User" will get a more meaningful name, namely "researcher" for now, which will need to fit the sidebar.

## Success criteria
- [x] Adapt "user" to "researcher"
- [x] Make the sidebar wide enough in css
fixed in https://github.com/ugent-library/biblio-ugent-prototype/commit/966bbe723e9a2224648f2d2b417015d3df774b92
- [x] Update css from prototype

Note: You will ONLY see this word when you have a double role (eg people working as a librarian).

# Context

## Current implementation in prototype
Not wide enough to fit the word "researcher"

![Image](https://user-images.githubusercontent.com/1572885/188474007-cc6be1d0-2a94-4e09-95b2-38a309391573.png)

## Future implementation in prototype
A bit wider
![Image](https://user-images.githubusercontent.com/1572885/188474043-17cc4dcf-9891-409a-baec-b98386c3a472.png)
![Image](https://user-images.githubusercontent.com/1572885/188474042-7f9db297-1148-44a5-9bae-35b094df8e03.png)

**Comment by nics** [comment]
done
