### ISSUE TITLE
Embargoed access does not make embargo fields editable for datasets [reformed in #538]

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#562]
# Bug description

[reformulated in #538]

Whenever selecting "embargoed access", the fields to indicate the embargo do not become editable.
It only becomes editable _after_ clicking the save button.

![Image](https://user-images.githubusercontent.com/1572885/188602767-6d4268e1-1ed6-4304-8b27-59e6deb18020.png)

## Steps to reproduce

1. Go to eliot
2. Go to datasets
3. Select a dataset
4. In the "Description" tab, scroll to "Dataset details" and click "Edit"
5. Scroll to "Access level"
6. Select "Embargoed access"
7. Try editing "Embargo period" and "Access level after embargo period"

# Expected behaviour

- [ ] Whenever selecting "embargoed access", the fields to indicate the embargo become editable.
- [ ] Whenever "embargoed access" is not selected, the fields for embargo do not appear.

# Technical info
- OS: MacOS Monterey 12.5.1
- Browser:
  - Safari version 15.6.1 (17613.3.9.1.16)
  - Firefox version 104.0 (64-bit)
  - Chrome version 104.0.5112.101

**Comment by netsensei** [comment]
Should be fixed in https://github.com/ugent-library/biblio-backend/commit/91004343b0ab5995c96942e9a738f786eda6d296
