### ISSUE TITLE
As a researcher or administrative support, when a record is locked I cannot edit it any longer.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#574]
# Story

As a researcher or administrative support, when a record is locked I cannot edit it any longer.

## Success criteria

- [x] Whenever a librarian locks a record, I can see which parts I cannot edit anymore for publications and datasets
  - [x] Remove "Delete" button from overview pages
  - [x] Remove "Delete" buttons from detail page header
  - [x] Remove "Withdrawn" button from header (related https://github.com/ugent-library/biblio-backend/issues/575)
  - [x] Remove dropzone and HR line in Full text documents overview page
  - [x] Remove edit and delete buttons for uploaded Full text documents
  - [x] Remove edit, delete and reorder buttons for contributors tab
  - [x] Remove "remove from publication/dataset" button inside three dots "more" item
- [x] As we cannot use the message field any longer after locking we inform the researcher below the message box they can send an email to biblio@ugent.be (this can be a placeholder for now, copy TBC)

## Out of scope
Will be replaced by a message
- Whenever a librarian locks a record, I can still use the message field

These will be just be removed:
- Replace all "edit" buttons with a disabled "locked-for-edit" button
- Replace all "Add X" buttons with a disabled "locked-for-edit" button
- Replace "Add dataset/publication" button with "locked-for-edit" button

# Implementation inside tabs

## Overview
Remove "Delete" button from overview pages
<img width="1057" alt="Schermafbeelding 2022-09-07 om 14 14 02" src="https://user-images.githubusercontent.com/1572885/188875754-8141bb42-3a86-432b-83e9-e7829cde50cb.png">
<img width="1044" alt="Schermafbeelding 2022-09-07 om 14 14 56" src="https://user-images.githubusercontent.com/1572885/188875831-7fbeb0f1-d6d9-468a-8cee-29871d97d946.png">

### Withdrawn
Remove "withdrawn" and "Delete" button in record details header
<img width="1330" alt="188872946-d4eaa784-26a2-4f28-a83c-bf4dac178d69" src="https://user-images.githubusercontent.com/1572885/188875274-9fb6225a-d4c2-4c4c-8260-bf564cdda5fd.png">
<img width="1331" alt="Schermafbeelding 2022-09-07 om 14 12 36" src="https://user-images.githubusercontent.com/1572885/188875522-e9c432a9-fc37-47bb-bb53-a0fbc994060b.png">

### Regular forms inside tabs
e.g. Publication details in Description
<img width="1298" alt="Schermafbeelding 2022-09-07 om 11 07 02" src="https://user-images.githubusercontent.com/1572885/188842007-66b840fa-441c-4ada-92b0-c81ace25717b.png">

### "Add" forms
e.g. Projects in Description
<img width="1297" alt="Schermafbeelding 2022-09-07 om 11 08 02" src="https://user-images.githubusercontent.com/1572885/188842132-ed221bd3-196a-4e24-90d1-c162fb49d4d7.png">

### Full text
- Remove dropzone
- Replace altering buttons
<img width="1308" alt="Schermafbeelding 2022-09-07 om 11 08 45" src="https://user-images.githubusercontent.com/1572885/188842373-cbb3d1b1-1d76-44f1-9ba9-ee8249906a65.png">

### Contributors: Authors and editors + Creators
- Replace add button
- Remove altering buttons
<img width="1310" alt="Schermafbeelding 2022-09-07 om 11 09 34" src="https://user-images.githubusercontent.com/1572885/188842505-8d71fdec-be56-4a9e-945e-3d1385f44c2b.png">
<img width="1294" alt="Schermafbeelding 2022-09-07 om 11 29 21" src="https://user-images.githubusercontent.com/1572885/188844051-01cbf8e1-ce04-4dcf-9fc2-6f59501da3f9.png">

### Related datasets or publications
- Remove remove button
- Replace add button
<img width="1304" alt="Schermafbeelding 2022-09-07 om 11 10 13" src="https://user-images.githubusercontent.com/1572885/188843287-bea78339-1a7e-48fd-9b68-e6f79bec67b8.png">
<img width="1316" alt="Schermafbeelding 2022-09-07 om 11 25 43" src="https://user-images.githubusercontent.com/1572885/188843389-f9c9b4d4-b832-4324-8945-bf0953267aa6.png">

## Component
Disabled button: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-btn-skins.html#component-08-btn-disabled
Buttons with icons: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-btn-types.html#component-02-btn-icon-text

## Example code
```
<button class="btn btn-outlined-primary disabled" type="button">
    <i class="if if-lock"></i>
    <div class="btn-text">Locked for editing</div>
</button>
```

# As is: keep messaging available for everyone
<img width="691" alt="Schermafbeelding 2022-09-07 om 11 10 39" src="https://user-images.githubusercontent.com/1572885/188844485-edfc4425-eac8-4285-92f7-5d9acc8c27ea.png">

**Comment by nics** [comment]
> Whenever a librarian locks a record, I can still use the message field

@mietcls this wasn't possible in librecat
