### ISSUE TITLE
If a record is withdrawn, I can see it in the record's detail view header

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#581]
# Story

If a record is withdrawn, I can see it in the record's detail view header.

See the context here: https://github.com/ugent-library/biblio-backend/issues/578

## Success criteria

- [ ] The moment a record is withdrawn, I can see it in my record header on the detail page
  - [ ] The status is set to "Biblio Withdrawn"
  - [ ] The general public can not see the withdrawn records in the front-office
  - [ ] The librarians can see the withdrawn record in the back-office
  - [ ] The "importer" (administrative staff / secretary) can see the withdrawn records in the back-office
  - [ ] The contributors (researchers mentioned in the record) can see the withdrawn records in the back-office

# Implementation record header

### Intended Design

Similar to overview:
<img width="1214" alt="Schermafbeelding 2022-09-07 om 11 03 50" src="https://user-images.githubusercontent.com/1572885/188838099-af326e6e-20cf-4ca7-8eb2-18c5b787c3a6.png">
<img width="1328" alt="Schermafbeelding 2022-09-07 om 15 07 56" src="https://user-images.githubusercontent.com/1572885/188886015-9c4778cc-2d42-4a95-ba34-c1573cd68e65.png">

### Design adapted for current Biblio layout
<img width="1328" alt="188885794-7d0d23ad-b727-422a-b9dd-ec1ba38aefa4" src="https://user-images.githubusercontent.com/1572885/190352446-22772458-b084-4879-bd62-dfa1387aa545.png">

### Danger badge
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html#component-01-b-badge-text

### Example code
```
<div class="bc-toolbar-left flex-wrap">
  <div class="bc-toolbar-item my-2">
    <span class="badge badge-pill badge-danger">
      <span class="badge-text">Biblio Withdrawn</span>
    </span>
  </div>
</div>
```

**Comment by mietcls** [comment]
Published in the detail view is the publisher's status, not the biblio visibility – rework

**Comment by netsensei** [comment]
Is fixed. Closing this.
