### ISSUE TITLE
Overviews and lists still show stale records after deleting them from the database & index

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#590]
# Bug description

When I delete a publication or dataset from an overview list, the item isn't removed from the list until I manually reload the entire page.

* I do see a toast that says "Dataset / publication succesfully deleted"
* The item does get the status "deleted" in the database.

# Expected behavior

The overview list / page is updated and the item is removed from the list / page.

# Additional information

The delete handler for publication / dataset will send a `hx-redirect` response header commanding the browser to reload the entire page. However, this reload action is triggered before the elasticsearch index had enough time to sync up with the database. Since the displayed data originates from the index, the end-user gets an outdated view instead of the updated, new situation.

## suggested solutions

* Add a delay in the browser or in the app handler with a spinner, giving enough time to elasticsearch to update itself.
* Wait / listen to the index until we have confirmation that its in sync with the database, only then reload the page.
* UX: don't reload the entire page. Just refresh the view and grey-out the row that was deleted (visual cue). When the page is manually reloaded, it will be no longer there.

**Comment by mietcls** [comment]
Had a short discussion with @netsensei about option 1:

> Add a delay in the browser or in the app handler with a spinner, giving enough time to elasticsearch to update itself.

He showed me the impact of a short delay of 1250ms that could still be acceptable (if we can make it shorter would be great – between 400ms and 1000ms).

- **Visual feedback**: we can give visual feedback in the form of a spinner on the delete button itself. That will improve the feeling of _snappiness_. I'll make an adaption of a spinning button (I only have one in draft now).
  - This will give visual feedback now for the improvised 1250ms delay,
  - If we get automatic feedback from elastic we can use this spinner to cover the actual waiting period.
- **In the future**: we can buy some time with this temporary solution, so we can on the actual messaging system we need.

If needed I can still support by giving other design solutions (e.g. visual feedback in cards itself – but as I understood adding a class to the cards might also have annoying implications).

**Comment by netsensei** [comment]
Closing this for now. Revisiting in the future when we build a more reactive interface / backend.
