### ISSUE TITLE
When I import a dataset which was previously deleted, I see the "Are you sure you want to import this dataset?" dialog box

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#613]
# Bug description

When I import a dataset which was previously deleted, I see the "Are you sure you want to import this dataset?" dialog box. This is confusing to researchers & reviewers since the search or list views don't show the previously deleted dataset.

How to reproduce:

1. Import a dataset (e.g. with DOI 10.5281/zenodo.3613927).
2. Delete the dataset from the overview  list at `/dataset`.
3. Import the dataset again with the same DOI.
4. Notice how the duplicate dataset notification pops up.

# Expected behavior

I don't see a duplicate dataset notification for previously deleted datasets (tombstones). 

# Additional information

Deleted datasets remain in the elastic index with the status "STATUS_DELETED" flag. This is the result of following immutability as a first  principle in our snapshot strategy. This shouldn't be changed. It's okay for tombstones to remain in the search index.

## suggested solutions

When checking for existing datashots, tombstones should be omitted from the duplicate dataset check.

**Comment by nics** [comment]
@netsensei i'll add a filter status=public
