### ISSUE TITLE
As a librarian with multiple roles, I can see a switch that allows me to switch from a "researcher" perspective to a "librarian" perspective.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#633]
# Story

As a librarian with multiple roles, I can see a switch that allows me to switch from a "researcher" perspective to a "librarian" perspective.

## Success criteria

- [ ] From the researcher perspective, I can switch to librarian
- [ ] From the librarian perspective, I can switch to researcher
- [ ] The colour of the sidebar changes to dark gray if I select librarian
- [ ] The colour of the sidebar changes to blue if I select researcher

To see what functionalities change, see https://github.com/ugent-library/biblio-backend/issues/557

### Out of scope
- "veelinvoerders" perspective

# Design

See https://github.com/ugent-library/biblio-backend/issues/557

# Implementation

### Sidebar
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-sidebar.html

For librarians, add class 'c-sidebar--dark-gray' to sidebar

### Dropdown
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-dropdown.html

Nuance, classes added to dropdown:
`btn-outline-light btn-sm btn-block`

### Sidebar

**Librarian perspective**
```
<div class="c-sidebar c-sidebar--dark-gray">
</div>
```

**Researcher perspective**
```
<div class="c-sidebar">
</div>
```

### Dropdown

**Closed from librarian perspective**
`With aria-expanded="false"`
```
<div class="dropdown mx-4 mt-1 mb-5">
  <button class="btn btn-outline-light btn-sm btn-block dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="text-truncate">Librarian</span>
  </button>
  <div class="dropdown-menu" style="">
    <a class="dropdown-item" href="/biblio/researcher/publications/overview.html">Researcher</a>
    <a class="dropdown-item active" href="/biblio/reviewer/publications/overview.html">Librarian</a>
  </div>
</div>
```

**Open from librarian perspective**
`With aria-expanded="true"`
```
<div class="dropdown mx-4 mt-1 mb-5 show">
  <button class="btn btn-outline-light btn-sm btn-block dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <span class="text-truncate">Librarian</span>
  </button>
  <div class="dropdown-menu show" x-placement="bottom-start">
    <a class="dropdown-item" href="/biblio/researcher/publications/overview.html">Researcher</a>
    <a class="dropdown-item active" href="/biblio/reviewer/publications/overview.html">Librarian</a>
  </div>
</div>
```

**Closed from researcher perspective**
```
<div class="dropdown mx-4 mt-1 mb-5">
  <button class="btn btn-outline-light btn-sm btn-block dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Researcher</button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="/biblio/researcher/publications/overview.html">Researcher</a>
    <a class="dropdown-item active" href="/biblio/reviewer/publications/overview.html">Librarian</a>
  </div>
</div>
```

**Comment by nics** [comment]
@mietcls you will need to logout/login

**Comment by mietcls** [comment]
Behaves as expected, thanks @nics
