### ISSUE TITLE
Remove "new" status from exported data

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#634]
**Describe the story**

The status values need an overhaul. We currently have several statuses: new, private, returned, withdrawn, public, deleted. This causes issues e.g. the current data dump on `/vol/share/nsteenla` contains records with status values `new` and `returned`. These cause erratic results when imported in the application. The `status`  values need to be adjusted:

**Expected behavior**

We want to land on these four statuses:

* draft = new record which has never been published before. Freshly made.
* public = record has is currently publicly available / visible publicly.
* withdrawn = record has been withdrawn from the public's eye because it needs re-work.
* deleted = record was deleted. This status indicates that the record shouldn't be visible in the interface. This is a "soft delete" where we keep the deleted record as a "tombstone" but never show in the user interfaces.

**Proposed solution**

* `private` should be renamed to `draft` since we're introducing a separate `withdrawn` status
* `new` doesn't exist anymore and needs to be mapped to `draft`.
* `returned` should be renamed to `withdrawn`.

Tangential to this issue: do we validate field input against closed vocabularies?  The `status` field is an example of this. It's a (a) required field which has a (b) value from the `publication_statuses` vocabulary in `map.go`. If not, the record should be rejected.

This requires changing the statuses in biblio-backend as well as in the librecat export.

**Additional information**

Renaming `returned` to `withdrawn` is related to #575, #625, #580

**Comment by nics** [comment]
there's probably no need to even migrate 'new' records to the new backend

**Comment by mietcls** [comment]
Will we migrate private records / drafts as well?

**Comment by netsensei** [comment]
@mietcls We just discussed in-person: we still are considering keeping "private" around. e.g. the "draft" status could be used in a version-based context: a new draft = "a new version which hasn't been published yet". Whereas "private" could be used as "I don't want to make this version publicly visible"

We need to hash out the semantics a bit more before wrangling existing data.

**Comment by nics** [comment]
@mietcls yes private's need to be migrated, but 'new' (=librecat drafts) records not

**Comment by nics** [comment]
new is now excluded from librecat export: https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/ce8be7cb5840fef614502dcb88ddbfa57bbdfeac
