### ISSUE TITLE
I can still publish/withdraw/delete after a conflict error

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#641]
**Describe the bug**

I've tried to publish / withdraw / delete a dataset / publication, but I got an conflict error dialog telling me that I can't do any of those actions. I close the dialog. When I click on the publish / withdraw / delete buttons from the dataset / publication detail page a second time, I get the confirmation box again: when I confirm, the action goes through without a conflict error.  I did not reload the detail page manually.

It's confusing to see an error dialog when I first try to publish in a conflict situation; and then the action seems to work again when I try it again... without reloading the page.

**To Reproduce**

Set up a conflict situation:

1. Add a new dataset and save as draft.
2. Open a dataset in Window A, hit the "publish" button: you will see the confirmation box.
3. Open a dataset in Window B, hit the "publish" button: you will see the confirmation box.
4. Confirm that you want to publish the dataset in Window B.

Now for the bug:

1. Confirm that you want to publish the dataset in Window A.
2. Notice how this will result in an error dialog.  Close the dialog box. You will land back on the detail page of the dataset.
3. Click "publish" again from the header actions. You will see the confirmation box again.
4. Confirm that you want to publish the dataset a second time.
5. Notice how the dataset is published again: you will get a flash message saying it was published successfully.

**Expected behavior**

It shouldn't be possible to hit publish / withdraw / delete after a conflict error dialog was shown. The page needs to be reloaded to reflect the new situation.  If the dataset was already published, that would imply that the publish button isn't shown again after page reload.

When a "conflict error" dialog is shown after confirmation, something needs to happen after closing the dialog:

* ... the page is reloaded automatically after closing the dialog.
* ... the buttons are disabled until the user manually reloads the page.

**Comment by nics** [comment]
@mietcls @netsensei I made 2 small changes to solve this:
- Publish redirects back to the detail page like withdraw and lock
- Conflict message changed from "Dataset has been modified by another user. Please reload the page." to "Dataset has been modified by another user." because the page gets reloaded for you

can you test if this is intuitive?
