### ISSUE TITLE
When trying to add related publications to a dataset, or vice versa, only publications that the user has made appear, not all publications, even in Librarian view

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#643]
# Description of problem
When trying to add related publications, only publications that the user has made appear, not all publications, even in Librarian view

# Desired behaviour
When in Librarian view and attempting to link to a publication, allow the librarian to search ALL publications in Biblio

**Comment by netsensei** [comment]
Same issue also on publication? Related datasets?

**Comment by mietcls** [comment]
Correct @netsensei
