### ISSUE TITLE
When relating a dataset to a publication, you cannot back out.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#644]
# Description

When relating a dataset to a publication, you cannot back out.

If you click the "add dataset" button on the related datasets tab, you have to add a dataset. The cancel button does not work, and the only way to exit is to close the tab or use the browser's "Back" button.

When I've already added a dataset, there is no back button to be seen.

# Desired outcome

Re-enable the cancel button

## Note
This bug doesn't prevent any important workflows, but would be very frustrating for researchers when trying to link publications and datasets

# Screenshots

![Image](https://user-images.githubusercontent.com/1572885/193266613-3c02d61e-0a38-451f-81f3-a5449906858c.png)

**Comment by netsensei** [comment]
Stumbled across the same error problem. Fixed while working on #416.
