### ISSUE TITLE
I shouldn't be able to manipulate deleted projects, files, departments, links & abstracts

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#647]
**Describe the bug**

When I leave a record (publication, dataset) page open, someone else might have removed projects, files, departments, links & summaries. I see stale information on the page with actionable buttons: edit / delete.

When hitting the "edit" or "delete" buttons, I don't get a notification that those items have been deleted.

**To Reproduce**

1. Open up a publication in Window A
2. Add a department / abstract /...
3. Open up the publication in Window B.
4. Remove the department / abstract / ... in Window B.
5. Go back to Window A. You will see the stale department / abstract / ...
6. Hit the "delete" button of the deleted department / abstract / ...

**Expected behavior**

An notification telling me the record was altered and a request to reload the page.

**Comment by nics** [comment]
@mietcls @netsensei same remark probably applies here https://github.com/ugent-library/biblio-backend/issues/638#issuecomment-1266444539

**Comment by mietcls** [comment]
Since this does not happen a lot, can we prioritise this one for after the launch? For example when there's a new call for publications (December / January)?

**Comment by nics** [comment]
@mietcls yes i'll remove the milestone

**Comment by netsensei** [comment]
See: #638
