### ISSUE TITLE
Dissertation: "Authors & Editors" tab should be renamed to "Authors & Supervisors"

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#648]
**Describe the improvement**

When editing / viewing a "dissertation" publication, the contributors tab is called "Authors & Editors" instead of "Authors & Supervisors".

**Expected behavior**

When editing / viewing a "dissertation" publication, the contributors tab is called "Authors & Supervisors".

**Comment by nics** [comment]
@mietcls those are the roles in use for a dissertation, there's the author of the thesis and then one or more supervisors/promoters

**Comment by mietcls** [comment]
- Affiliations (relevant to people, institutions, ...)
- People & Organisations (a bit more specific but long, very dummy proof)

**Comment by mietcls** [comment]
Will be replaced by https://github.com/ugent-library/biblio-backend/issues/670 for now, after discussing this with the test group. Affiliations is the shortest, and leaves space for projects (controversial but it might be an option).
