### ISSUE TITLE
Full text & Documents – I can fill out document information and be informed

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#653]
# Story

I can fill out document information. Depending whether I select "Full text" as a document type or not, I see different information and more or less fields.

Note: the text in the information alert can still be changed. We will track that in a different issue if needed.

## Success criteria
- [ ] When I choose full text document as document type, I can select the publication type
- [ ] When I choose full text document as document type, I am informed of specific regulations
- [ ] When I choose any other document type, I can not see the publication type nor the specific regulations

# Design

## Empty or non-full-text-selected state
![Schermafbeelding 2022-10-03 om 11 49 1](https://user-images.githubusercontent.com/1572885/193584147-3829f215-a324-4588-95b0-0b028071e5fa.png)

## Full text selected state
![Schermafbeelding 2022-10-03 om 11 47 1](https://user-images.githubusercontent.com/1572885/193582937-38dcefb8-99ae-48ac-b2ae-18b7ede0b1c2.png)

# Implementation

### Alert
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-alerts.html#component-04-b-alert-success

### Select
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html

### Form help text
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text

## Code examples

View full modal example at https://github.com/ugent-library/biblio-backend/issues/650

### Title
`<h3 class="mb-4">Document information</h3>`

### Publication version
Positioned right after the document type:
(form row width can be reused for document type)
```
<div class="form-row">
  <div class="form-group col-md-8 col-lg-5">
    <label class="col-form-label" for="publication_version">Publication version</label>
    <select class="custom-select form-control" name="publication_version">
      <option></option>
      <option value="publishedVersion">Publisher version/Version of record (VoR)</option>
      <option value="authorVersion">Author's original (AO)</option>
      <option value="acceptedVersion">Author accepted manuscript (AAM)</option>
      <option value="updatedVersion">Corrected version of record (CVoR)</option>
    </select>
    <p class="form-text">You are encouraged to <a href="#">upload the the auto accepted manuscript of journal articles</a>, to support public knowledge dissimination.</p>
  </div>
</div>
```

### Divider
`<div class="c-divider"></div>`

### Alert
Positioned after access levels title:
```
<div class="alert alert-success mt-3 mb-5">
  <i class="if if-check-circle">
  </i>
  <div>
    <p>UGent has the right to&nbsp;<strong>open up the auto accepted manuscript of a journal article to the public</strong> after embargo based on the <a href="#">Belgian Open Access Law.</a>
      <br>
      <small>Opt out of this right by sending us an email at <a href="mailto:biblio@ugent.be">biblio@ugent.be</a>.</small>
    </p>
  </div>
</div>
```

**Comment by netsensei** [comment]
Implemented. Works for me. Can be closed.
