### ISSUE TITLE
Full text & Documents – I can add a license or lack thereof

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#656]
# Story

I can add a license or lack thereof

**Note; researchtip to be confirmed, can be edited later.**

## Success criteria
- [ ] I can select a license
  - [ ] I can select CC licenses
    - [ ] CC0 (1.0)
    - [ ] CC BY (4.0)
    - [ ] CC BY-SA (4.0)
    - [ ] CC BY-NC (4.0)
    - [ ] CC BY-ND (4.0)
    - [ ] CC BY-NC-SA (4.0)
    - [ ] CC BY-NC-ND (4.0)
  - [ ] I can select there is no license to reuse the documents, when the rights holder has kept the copyright.
  _"In copyright (no license)"_
  - [ ] For now, I can still select "I don't know"
  _"I don't know the status of the copyright for this publication"_
  - [ ] I can indicate there is a license, it is just not an option in this list
  _"The license is not listed here"_

Related #659 

## Out of scope
- When I select Other license, I can input it in a different field

# Image
![Schermafbeelding 2022-10-06 om 17 38 00](https://user-images.githubusercontent.com/1572885/194356989-9dfca390-df5a-4910-aec1-fa5bc360b4b5.png)

# Code example
View full modal example at https://github.com/ugent-library/biblio-backend/issues/650

### Title
`<h3 class="mb-3">How can other people <strong>reuse</strong> your document?</h3>`

### Select
```
<div class="form-row">
  <div class="form-group col-md-6">
    <label class="col-form-label" for="license">
      License for reuse granted by the rights holder
      <a class="text-muted mx-2" href="#" data-container="body" data-toggle="popover-custom" data-placement="right" data-popover-content="#licenses-tooltip">
        <i class="if if-info-circle if--small"></I>
        <span class="sr-only">More info</span>
      </a>
    </label>
    <select class="custom-select form-control" name="license">
      <option></option>
      <option value="CC0-1.0">CC0 (1.0)</option>
      <option value="CC-BY-4.0">CC BY (4.0)</option>
      <option value="CC-BY-SA-4.0">CC BY-SA (4.0)</option>
      <option value="CC-BY-NC-4.0">CC BY-NC (4.0)</option>
      <option value="CC-BY-ND-4.0">CC BY-ND (4.0)</option>
      <option value="CC-BY-NC-SA-4.0">CC BY-NC-SA (4.0)</option>
      <option value="CC-BY-NC-ND-4.0">CC BY-NC-ND (4.0)</option>
      <option value="copy-held">In copyright (no license)</option>
      <option value="Other">The license is not listed here</option>
      <option value="Other">I don't know the status of the copyright for this publication</option>
    </select>
  </div>
</div>
```
### Tooltip
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-popover.html

### Divider
`<div class="c-divider"></div>`

**Comment by mietcls** [comment]
After consulting with a bunch of stakeholders (Open access team members, review team members, Sarah, Development team, ...)

**In copyright (no license)**
We will not make a difference any longer for copyright between the rights holders; as this is a separate information. It does not matter who decided on the license when asking for a license. If we make clear in the interface the rights holder does this, there is no confusion. We can be agnostic about it in our interface.

**"I don't know"**
We will keep the "I don't know" flag for now, because it is used by some faculties and is handy as a flag for some reviewers. Long term we should find a way to help people navigate this decisions without having to resort to "I don't know".

**Introduction of the flag "Other license (the license is not in this list)"**
- Right now there is no way to indicate that there is a license, but it is just not an option in the list. This can create a confusing situation, as it happens – and now there is a way out.
- This will help the library discover whether we are missing out on important licenses.
- We will not ask people to enter this license in a free-text field. This information would have to be shown in our public facing front-office, and there is a risk of having irrelevant information online for some time. This information should never be live, but we can use this as a way to start our analysis and figure out which license has been granted.
- The reviewers already note down the other license in a "Additional information" field, so we can use this in a later stage in our analysis.

**Comment by netsensei** [comment]
This has been implemented. Awaiting feedback.

**Comment by mietcls** [comment]
Tested this live today, reviewers will do a double test later – but is good for now!
