### ISSUE TITLE
Whenever I enter a search result that shows no records or there are no records to be shown at all, I get a message so I know what went wrong.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#662]
# Story

Whenever I enter a search result that shows no records or there are no records to be shown at all, I get a message so I know what went wrong.

# Expected result

- [ ] For datasets
- [ ] For publications

## Example
![Schermafbeelding 2022-10-06 om 17 46 38](https://user-images.githubusercontent.com/1572885/194358920-3af2cbd2-1bf1-483b-b599-a07273dea434.png)

## Copy
Title: No records to display.
Text: Refine your search or add a new record.
Button for publications: Add publication
Button for datasets: Add datasets

## Component
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-blank-slate.html#component-02-c-blank-slate

## Example code
Inside the card body for publications:

```
<div class="card-body p-0">
  <div class="c-blank-slate c-blank-slate-default c-blank-slate-large">
      <div class="bc-avatar bc-avatar--medium">
          <i class="if if-info-circle"></I>
      </div>
      <h3 class="c-blank-slate-title">No records to display.</h3>
      <p>Refine your search or add a new record.</p>
      <div class="c-button-toolbar">
          <a class="btn btn-outline-primary" href="#">
              <i class="if if-add"></I>
              <div class="btn-text">Add publication</div>
          </a>
      </div>
  </div>
</div>
```

Inside the card body for datasets:

```
<div class="card-body p-0">
  <div class="c-blank-slate c-blank-slate-default c-blank-slate-large">
      <div class="bc-avatar bc-avatar--medium">
          <i class="if if-info-circle"></I>
      </div>
      <h3 class="c-blank-slate-title">No records to display.</h3>
      <p>Refine your search or add a new record.</p>
      <div class="c-button-toolbar">
          <a class="btn btn-outline-primary" href="#">
              <i class="if if-add"></I>
              <div class="btn-text">Add dataset</div>
          </a>
      </div>
  </div>
</div>
```

**Comment by mietcls** [comment]
@nics is this what you expected with the blank state for no search results / no results at all?

**Comment by netsensei** [comment]
@nics @mietcls Implemented but might need some validation if okay.
