### ISSUE TITLE
Remove "Built with LibreCat" from front-office page.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#666]
# Story

Remove "Built with LibreCat." from front-office page.
"Developed by Ghent University Library" can remain.

## Context

LibreCat is going in a different direction, we do not want to market it here now.

## Current situation
In the footer of biblio.ugent.be:
![Image](https://user-images.githubusercontent.com/1572885/194577700-8e5691cf-a2ae-41bf-9570-b3f439d934f8.png)

**Comment by nics** [comment]
done
