### ISSUE TITLE
Change "Authors & Editors" tab label to "People & affiliations"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#670]
# Story

Make Authors & Editors tab fit broader scope of Auhthors, editors, supervisors, contributors and other exceptions.

Confirmed with reviewers & curators.

# Context

- This is a problem for dissertations and datasets, as the label did not cover the load. Suggestions have been made in the past, such as https://github.com/ugent-library/biblio-backend/issues/648
- In the future we might also add departments, the "Published while none of the authors are employed at UGent" checkbox, and maybe even the projects section (very preliminary) to this tab.

**Comment by netsensei** [comment]
Implemented.

I have renamed the tab to "People & Affiliations" on both Datasets and Publications.
