### ISSUE TITLE
"View personal details" when searching for a person links to the wrong location

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#691]
# Bug description

When looking for a person to affiliate them to a record, you get a link "View personal details". It now links to "#" instead of the personal details link.

![Image](https://user-images.githubusercontent.com/1572885/195122345-c074a9f8-6352-493f-8730-5f94f1b1b32d.png)

## Expected result
![Image](https://user-images.githubusercontent.com/1572885/195122236-1d677381-1a6b-49da-bae4-71aadc055353.png)

## Proposed implementation 

- We will now use the phone book link, not the link to the researcher profile, because this one will be most reliable, e.g. https://telefoonboek.ugent.be/en/people/{ugent_id}. On this page a link to the research profile is accessible.
-  We will only show the phone book link if the researcher's membership is active.
- We also show if the researcher is currently an active member or not, by showing expiration date (or "Present" when still active).

Context:
- You can only visit the link when you are signed in. That is not a problem in the back-office, but it is in the front-office (problem for later).
- The phone book links are not persistent. This is a known risk, and we can anticipate on because we have kept information ourselves such as membership dates.

![Schermafbeelding 2022-10-17 om 14 22 04](https://user-images.githubusercontent.com/1572885/196175844-ab54f5d2-9695-4275-a9d9-60380033ae57.png)

### Active member
```
<div class="bc-avatar-text">
  <h3 class="mb-0">
    Karen Büscher<span class="badge badge-pill badge-default ml-3">Active UGent member</span>
  </h3>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">WE06</li>
    <li class="c-meta-item">PS05</li>
  </ul>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">
      <span>UGent membership: 01/01/2020 – Present</span>
    </li>
  </ul>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">
      <span class="mr-2"><i class="if if-ghent-university"></I> 002002254293</span>
      <span class="mr-2"><i class="if if-ghent-university"></I> 802000261734</span>
    </li>
    <li class="c-meta-item">
      <a href="#">
        <i class="if if-external-link"></i>
        <span>View personal details</span>
      </a>
    </li>
  </ul>
</div>
```

### Non-active member
```
<div class="bc-avatar-text">
  <h3 class="mb-0">
  </h3>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">WE06</li>
    <li class="c-meta-item">PS05</li>
  </ul>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">
      <span>UGent membership: 01/01/2020 – 01/01/2022</span>
    </li>
  </ul>
  <ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">
      <span class="mr-2"><i class="if if-ghent-university"></I> 002002254293</span>
      <span class="mr-2"><i class="if if-ghent-university"></I> 802000261734</span>
    </li>
  </ul>
</div>
```

## Context

Across browsers

**Comment by netsensei** [comment]
So, this feature currently doesn't work in the old application:

* It used to link towards the UGent phone book, but that's an external application and it isn't as accessible as it used to be.
* Now it links to a page "biblio.ugent.be/person/<uuid>" which leads to a 404 page

So, the current feature is unreliable. Do we want to keep it in with this release? Or do we leave it out until we get input that this is a necessary feature?
