### ISSUE TITLE
add pubmed and arxiv importers

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#70]
in librecat:

`post '/librecat/rest-api/user/:user_id/publication/import'` should handle imports with `identifier_type` `pubmed_id`
this uses `LibreCat::FetchRecord::epmc` to import the records.

`post '/librecat/rest-api/user/:user_id/publication/import'` should handle imports with `identifier_type` `arxiv_id`
this uses `LibreCat::FetchRecord::arxiv` to import the records.

in go:

`controller.Publications.AddSingleImport` needs to also accept an identifier_type and pass it to `engine.Engine.ImportUserPublications`.

template `templates/publication/add_single.gohtml` needs to have a dropdown `identifier_type` with choices DOI/doi, PubMed/pubmed_id, arXiv/arxiv_id (see ui prototype)

**Comment by nicolasfranck** [comment]
ah crap, I added as identifier_types `arxiv` and `epmc`. Ok? Potato potato..

**Comment by nics** [comment]
arxiv_id and pubmed_id are better

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/579

**Comment by nics** [comment]
resolved by #71
