### ISSUE TITLE
Labels missing in conference edit view

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#710]
# Bug description

Labels missing in conference edit view

## Steps to reproduce

1. Go to publications on Eliot
2. Open a publication
3. Scroll to "conference" in details tab
4. Edit the conference card
5. See labels under the input fields

# Screenshots
![Image](https://user-images.githubusercontent.com/1572885/195813072-96c00c5e-16f1-4459-8b95-f77053e37203.png)

**Comment by nics** [comment]
@mietcls librecat has “YYYY-MM-DD” as placeholder text
