### ISSUE TITLE
Add banner to old Biblio to inform people about upcoming launch

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#713]
# Story

When I visit the old Biblio, I am informed a new version is coming.

# Screenshots
<img width="1187" alt="Schermafbeelding 2022-10-19 om 15 43 17" src="https://user-images.githubusercontent.com/1572885/196708768-1d82c418-6b60-48ca-8673-4a3186c6735c.png">

# Code example
Located in "Messages" block
<img width="644" alt="Schermafbeelding 2022-10-19 om 15 35 28" src="https://user-images.githubusercontent.com/1572885/196706444-0bd8f3d5-d44a-4274-acad-0f1b708fed42.png">

```
<div class="alert alert-success dz-preview dz-file-preview margin0 margin-bottom3" id="8769924">
  <div class="row">
    <div class="col-md-12 col-xs-10">
      <h4 class="margin-top3">Biblio is getting an update on 15 November 2022</h4>
      <p>
        <strong>A new lay-out and structure will enable Biblio to support current and future needs even better.
          <br>
          Trainings and documentation will be available. Got any questions? <a href="https://biblio.ugent.be/contact" target="_blank">Reach out to us</a>.
        </strong>
      </p>
    </div>
  </div>
</div>
```

**Comment by mietcls** [comment]
Inquired with testing team, Stefanie, Inge, Rosemie

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/b6735dfdec6a6c2346e8212dd12da845c4694fb9
