### ISSUE TITLE
Revisit metadata sections order and content

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#75]
**Describe the improvement**
To make clear what metadata can be provided in the "Additional information" section, an alternative name could be preferred.

@sdebodt to check content of "Additional information" section and check with Anniek for alternative.

**Comment by sdebodt** [comment]
A complete revisit of the different metadata sections (content, naming, order) is useful according to Nicolas as this has not been done in the past. @sdebodt to check with Myriam and Anniek.

**Comment by nics** [comment]
@sdebodt this issue is too vague, close and replace with more concrete issues?

**Comment by sdebodt** [comment]
After discussion with Anniek, we propose the following metadata sections and order (based on the metadata for publication type "Journal Article").

**Publication details**
Publication type
Article type
DOI
Classification (of UGent-classification?)
 --
Title  
Alternative title
Journal title  
Short journal title
--
Language
Publishing status
Published while none of the authors are employed at UGent
Publication year
Place of publication
Publisher
--
Volume
Issue
Pages
Number of pages
Article number
Special issue title
--
Web of Science type
Web of Science ID
ISSN
ISBN
PubMed ID
Arxiv ID
ESCI ID

**Projects**
as is
**Departments**
as is
**Conference details**
as is

**Abstract and Keywords**
Abstract
Keywords
Research field

**Links**

**Additional information**
free text field only

**Comment by nicolasfranck** [comment]
@sdebodt in the tab "abstract" I cannot add subdivisions for keywords or other fields. It is restricted to one type only, as that is already structured..

**Comment by nicolasfranck** [comment]
@sdebodt and what about the other types? For some I can suspect what to do, but some like `dissertation` have special fields.

**Comment by sdebodt** [comment]
I did not have the time yet to check for the other publication types. @nicolasfranck, do you only need input on dissertation or also on other publication types?

**Comment by sdebodt** [comment]
@nicolasfranck can we move keywords and disciplines to the second section, below the titles?

**Comment by sdebodt** [comment]
I had a look at the order of the metadata for dissertations and that looks fine to me. There are a few fields for which I wonder whether they are needed, but we can revisit this at a later stage.
Also the order of the metadata for the other publication types are ok.

So I would only move the keywords and research field for all publication types as mentioned above.

**Comment by nicolasfranck** [comment]
@sdebodt isn't the tab not big already? We are moving too much in a cramped space..

**Comment by sdebodt** [comment]
Keywords and research field are a bit lost right now while they are important to complete as they give information on the content of the publication.
Maybe we can play with the spacing between lines of text of a section a bit and then have more sections... let's leave as it is for now and give it some more thought at a later stage.

**Comment by nics** [comment]
@nicolasfranck @sdebodt seems like this can be closed?

**Comment by sdebodt** [comment]
yes, closing
