### ISSUE TITLE
Rename labels to increase user-friendliness

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#76]
**Describe the improvement**
Some labels could be renamed to increase user-friendliness or avoid confusion (e.g. "Send for review" instead of "Publish to Biblio").

Once it is possible to configure this on the front-end, assess which labels need to be changed and suggest alternative names in collaboration with biblio reviewers team.

**Comment by sdebodt** [comment]
- [ ] #152

**Comment by nics** [comment]
I'm going to close this, there are concrete actionable issues now
