### ISSUE TITLE
button groups under modals displayed as overlapping the modal content

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#78]
<img width="1552" alt="Screenshot 2021-11-09 at 13 24 52" src="https://user-images.githubusercontent.com/494636/140924064-29415e5b-c2bc-4e8e-af27-fe3afac1dd71.png">

Result: one cannot close the dialog because the underlying button "Add department"
is blocking the "cancel" button

**Comment by nicolasfranck** [comment]
The problem is already present in the prototype:

<img width="1552" alt="Screenshot 2021-11-15 at 16 20 42" src="https://user-images.githubusercontent.com/494636/141807270-6cde49bb-289a-4011-8024-03d02c2cd3a9.png">

Reproduce:

* change text of button "Edit" of part "Additional information" to something long
* click on the "Add link"
* The "Edit" button of "Additional information" is covering the dialog

@netsensei @nics where to report this?

**Comment by nics** [comment]
i'm not having the same issue with chrome on mac

**Comment by nicolasfranck** [comment]
I'm using chrome on mac
