### ISSUE TITLE
Librecat update embargo cron job replacement

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#780]
# Story

(Before 15 November?)
Create hacky embargo cronjobs for new interface:
To switch access level for records in new interface.

## Context
Unfortunately we cannot make use of the Inuits infrastructure. This means we have to do a temporary hack, or even do some manual work in the meantime.

To be implemented by 15 November: https://github.com/ugent-library/biblio-backoffice/issues/781

**Comment by nicolasfranck** [comment]
See frontoffice handlers`/frontoffice/publication-update-embargo` and `/frontoffice/dataset-update-embargo`
See https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/app/handlers/frontoffice/embargo.go
See https://github.com/ugent-library/biblio-backoffice/pull/759

TODO: cronjob in biblio that calls these routes
