### ISSUE TITLE
add UGent membership to author

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#79]
**Describe the improvement**
When adding or editing an author, I want to be able to indicate whether the author is member of UGent. Currently, I cannot change the membership. All authors are set as "External members" during the "Add a single publication workflow".

**To Reproduce**
If something does not work as expected, which steps did you take?
1. Go to 'Authors & Editors' tab of a draft publication
2. Click on 'pen' to edit an author

**Expected behavior**
In the column "membership, I expect to be able to change "External member" to "UGent member" through an editable field.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/141135039-1d70478c-7029-4923-b33c-1af05f606b21.png)
![image](https://user-images.githubusercontent.com/72742841/141135097-84a232c4-7fbd-467b-a34e-ef93d70e82fb.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 
**Related context**
Is it UGent member of time of publication or today?

**Comment by nics** [comment]
ok now
