### ISSUE TITLE
I cannot change the access level of a full text file

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#80]
**Describe the improvement**
When I added a publication, the access level was automatically set to "open access". When going to the "Full text" tab, I cannot change the access level. I can click on the arrow next to "open access" and get the dropdown, but when clicking on another access level, the dropdown menu disappears but the access level is not changed. I want to be able to change the access level of a full text in the publication page by selecting a different access level in the dropdown menu.

**To Reproduce**
If something does not work as expected, which steps did you take?
1. Go to 'publication' page
2. Click on 'Full text' tab
3. Click on arrow next to "Open acces"
4. Click on "UGent access"

**Expected behavior**
I expect that by clicking on "UGent access", this access level is selected and appears in the bubble and has a check in the dropdown menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/141137704-c03e97c1-babe-4dad-a77b-2af73311f1b9.png)

**Additional context**
related issue: https://github.com/ugent-library/biblio-backend/issues/74

https://onderzoektips.ugent.be/en/tips/00001670/

**Comment by nicolasfranck** [comment]
Updating the access level is possible by opening the edit modal
on the right (click on .. -> edit). Beware though of this [issue](https://github.com/ugent-library/biblio-backend/issues/90)

This select box does give the
false impression that selecting a new
value would update it. 

So .. why do we need two ways to update the access level?
Or is this a mispresentation?

**Comment by nics** [comment]
That's the design, it's a quick way to set the access level. Change select == update access level

**Comment by nics** [comment]
just use the existing PublicationFiles.Update method
