### ISSUE TITLE
Access level shown in publications overview is not correct

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#82]
**Describe the improvement**
The access level shown for a publication in the publications overview does not correspond to the true access level shown in biblio.ugent.be and in the "Full text" tab of the "publication" page. For the example in the screenshots, the access level should be "UGent access".

**To Reproduce**
1. Go to 'Publications overview'
2. Search publication with id 4443560
3. View access level
4. Click on publication to go to "publications" page
4. Click on "Full text" tab
5. Scroll down to Full text and access bubble

**Expected behavior**
Access level in publications overview should match true access level.

**Screenshots**
access level in "full text" tab
![image](https://user-images.githubusercontent.com/72742841/141140890-a1415b65-5637-4c7d-8bff-f634dd08eaa7.png)

access level in "publications overview"
![image](https://user-images.githubusercontent.com/72742841/141140944-64ee1769-0627-4457-a76e-e656053286a7.png)

**Additional context**
related issues: https://github.com/ugent-library/biblio-backend/issues/80

**Comment by nicolasfranck** [comment]
@sdebodt you mean that the access level as shown on the  development server should be the same as on biblio.ugent.be? This is merely test data..

**Comment by nics** [comment]
@nicolasfranck no it has a hardcoded open access value, template needs top be changed
