### ISSUE TITLE
unable to add ORCID to author

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#84]
**Describe the improvement**
Currently authors are added through two fields, a last name and a first name field. In addition, an "ID" icon is shown in the publication summary when it is an author with ORCID. In the author edit view, no ORCID info is shown and it is not possible to add an ORCID to an author. Enable to add an ORCID to an author when this is not part of the DOI or WoS based filled form.

**To Reproduce**
1. Go to 'publications overview'
2. Identify a publication from an author with an ORCID (e.g. Biblio ID: 4419918)
3. View "ID" icon in front of author
4. Go to 'publications' age
4. Click on "Authors & Editors" tab
5. Click on pencil next to author with ORCID

**Expected behavior**
It is expected that it is indicated in the "Authors & Editors" tab whether the author has an ORCID and that an ORCID can be added after clicking the pencil next to the Author.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/141465340-61fea310-5a07-4b49-8c07-fe1c76b15b20.png)
![image](https://user-images.githubusercontent.com/72742841/141465296-b5f97200-461b-4236-a98e-e0433f8e21d5.png)

**Additional context**
Related to issue https://github.com/ugent-library/biblio-backend/issues/85

**Comment by nics** [comment]
There are no plans to allow adding an orcid manually, they are imported or added by connecting your orcid profile. But they should be shown in the dialog.

**Comment by nics** [comment]
resolved by d08073b and 1f1ab83
