### ISSUE TITLE
use CRediT (contributor roles taxonomy) for Author roles

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#86]
**Describe the improvement**
A predefined list of author roles can be chosen from to indicate the type of contributions of an author to a publication. Instead of this list, use CRediT (Contributor Roles taxonomy, https://credit.niso.org/) to populate this predefined list, as this one will be recommended in the publications policy document of UGent. 

**To Reproduce**
1. Go to 'publication' page
2. Click on 'Authors & Editors' tab
3. Click on pencil next to author
4. Select role from list of predefined roles.

**Expected behavior**
I expect to be able to select one or more roles from the CrediT taxonomy for each other.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/141469397-7ae59ca0-5904-45b2-9274-0e3c9f2a31b3.png)

**Additional context**
https://credit.niso.org/implementing-credit/

**Comment by nics** [comment]
ok
