### ISSUE TITLE
Rename "Browse publications" to "Browse publications and datasets"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#893]
# Story

Rename title on front page below: "Browse publications" to "Browse publications and datasets"

## Current situation
<img width="1232" alt="Scherm­afbeelding 2022-12-12 om 10 01 50" src="https://user-images.githubusercontent.com/1572885/207004270-d51ae537-e390-4139-8bcd-b3aad510080b.png">

## Desired situation
<img width="1238" alt="Scherm­afbeelding 2022-12-12 om 10 02 22" src="https://user-images.githubusercontent.com/1572885/207004381-46590453-5a45-49a0-9e23-3377319f1a7f.png">

Out of scope: adding a section with datasets highlighted

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/65
