### ISSUE TITLE
edit file dialog is not scrollable.

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#90]
Reproduce:

* open publication
* go to tab "full text"
* click on the ".." on right of a file, and choose option "Edit.."
* a modal appears, allowing you to edit and save file metadata

Problems:

* if your screen is not height enough, you cannot see or access the top and bottom (where the save and cancel button is!), nor can you scroll to it.

<img width="1552" alt="Screenshot 2021-11-15 at 12 20 22" src="https://user-images.githubusercontent.com/494636/141773348-935c689d-f248-4a53-a4cb-99aa10781d55.png">

**Comment by nicolasfranck** [comment]
Inserting a `form` element into the layout in between `modal` and `modal-body` messes up the whole layout.
If I put the form around the whole modal, the layout problem is gone. I guess the layout
did not take that into account, or did not say where to put the form element itself?

**Comment by netsensei** [comment]
The Mono prototype does take this issue into account. 

1. Open the Mono prototype
2. Navigate to http://localhost:3000/add-publication/multiple/step-3/edit/full-text.html
3. Click on the "edit" button of a single file to see the same pop up.
4. Use the dev tools in the browser to inspect the HTML of the pop up.

You'll notice that the HTML of the popup looks something like this:

```html
<div class="modal-dialog modal-dialog-centered modal-fullscreen modal-dialog-scrollable" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">file.pdf</h2>
        </div>
        <div class="modal-body p-0 overflow-hidden">
            <div class="d-flex h-100">
                <div class="col-6 p-6 overflow-auto">
                    <form action="">
                        <!-- FORM -->
                    </form>
                </div>
                <div class="col-6 border-left bg-light d-flex justify-content-center overflow-auto p-6">
                    <img class="align-self-center h-100 w-auto shadow" src="/images/thumbnail.jpg">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-link" data-dismiss="modal">Cancel</button>
            <button class="btn btn-primary" data-dismiss="modal">Save</button>
        </div>
    </div>
</div>
```

The `overflow-hidden` and `overflow-auto` classes are Bootstrap 4 classes that trigger a scrollbar inside the popup.

**Comment by nics** [comment]
@netsensei the issue was that the form tag also has to enclose the submit button in the modal-footer

**Comment by netsensei** [comment]
Another way of solving this is using `hx-include`:  https://htmx.org/attributes/hx-include/

e.g. `hx-include=".modal-dialog .modal-body form > input"`

This way, the form tag doesn't have to encapsulate both body and footer.
